BEGIN;
INSERT INTO continents (code, name) VALUES ('AF','Africa');
INSERT INTO continents (code, name) VALUES ('NA','North America');
INSERT INTO continents (code, name) VALUES ('OC','Oceania');
INSERT INTO continents (code, name) VALUES ('AN','Antarctica');
INSERT INTO continents (code, name) VALUES ('AS','Asia');
INSERT INTO continents (code, name) VALUES ('EU','Europe');
INSERT INTO continents (code, name) VALUES ('SA','South America');
COMMIT;
ANALYZE;
