BEGIN;
INSERT INTO regions (iso3, iso2, country, name) VALUES
	('GS-GS','GS','SGS','S.Georgia & S.Sandwich Islands'),
	('PM-PM','PM','SPM','St. Pierre & Miquelon'),
	('PM-97501','97501','SPM','Miquelon-Langlade'),
	('PM-97502','97502','SPM','Saint-Pierre'),
	('SA-11','11','SAU','Al Bāḩah'),
	('SA-08','08','SAU','Al Ḩudūd ash Shamālīyah'),
	('SA-12','12','SAU','Al Jawf'),
	('SA-03','03','SAU','Al Madīnah'),
	('SA-05','05','SAU','Al Qaşim'),
	('SA-O1','O1','SAU','Ar Riyāḑ'),
	('SA-04','04','SAU','Ash Sharqīyah'),
	('SA-14','14','SAU','‘Asīr'),
	('SA-06','06','SAU','Ḩā\'il'),
	('SA-09','09','SAU','Jīzān'),
	('SA-02','02','SAU','Makkah'),
	('SA-10','10','SAU','Najrān'),
	('SA-07','07','SAU','Tabūk'),
	('SB-CT','CT','SLB','Capital Territory (Honiara)'),
	('SB-CE','CE','SLB','Central'),
	('SB-GU','GU','SLB','Guadalcanal'),
	('SB-IS','IS','SLB','Isabel'),
	('SB-MK','MK','SLB','Makira'),
	('SB-ML','ML','SLB','Malaita'),
	('SB-TE','TE','SLB','Temotu'),
	('SB-WE','WE','SLB','Western'),
	('SC-SC','SC','SYC','Seychelles'),
	('SD-23','23','SDN','A‘ālī an Nīl'),
	('SD-26','26','SDN','Al Baḩr al Aḩmar'),
	('SD-18','18','SDN','Al Buḩayrāt'),
	('SD-07','07','SDN','Al Jazīrah'),
	('SD-03','03','SDN','Al Kharţūm'),
	('SD-06','06','SDN','Al Qaḑārif'),
	('SD-22','22','SDN','Al Waḩdah'),
	('SD-04','04','SDN','An Nīl'),
	('SD-08','08','SDN','An Nīl al Abyaḑ'),
	('SD-24','24','SDN','An Nīl al Azraq'),
	('SD-01','01','SDN','Ash Shamālīyah'),
	('SD-17','17','SDN','Baḩr al Jabal'),
	('SD-16','16','SDN','Gharb al Istiwā\'īyah'),
	('SD-14','14','SDN','Gharb Baḩr al Ghazāl'),
	('SD-12','12','SDN','Gharb Dārfūr'),
	('SD-10','10','SDN','Gharb Kurdufān'),
	('SD-11','11','SDN','Janūb Dārfūr'),
	('SD-13','13','SDN','Janūb Kurdufān'),
	('SD-20','20','SDN','Jūnqalī'),
	('SD-05','05','SDN','Kassalā'),
	('SD-15','15','SDN','Shamāl Baḩr al Ghazāl'),
	('SD-02','02','SDN','Shamāl Dārfūr'),
	('SD-09','09','SDN','Shamāl Kurdufān'),
	('SD-19','19','SDN','Sharq al Istiwā\'iyah'),
	('SD-25','25','SDN','Sinnār'),
	('SD-21','21','SDN','Wārāb'),
	('SE-K','K','SWE','Blekinge län'),
	('SE-W','W','SWE','Dalarnas län'),
	('SE-I','I','SWE','Gotlands län'),
	('SE-X','X','SWE','Gävleborgs län'),
	('SE-N','N','SWE','Hallands län'),
	('SE-Z','Z','SWE','Jämtlands län'),
	('SE-F','F','SWE','Jönköpings län'),
	('SE-H','H','SWE','Kalmar län'),
	('SE-G','G','SWE','Kronobergs län'),
	('SE-BD','BD','SWE','Norrbottens län'),
	('SE-M','M','SWE','Skåne län'),
	('SE-AB','AB','SWE','Stockholms län'),
	('SE-D','D','SWE','Södermanlands län'),
	('SE-C','C','SWE','Uppsala län'),
	('SE-S','S','SWE','Värmlands län'),
	('SE-AC','AC','SWE','Västerbottens län'),
	('SE-Y','Y','SWE','Västernorrlands län'),
	('SE-U','U','SWE','Västmanlands län'),
	('SE-O','O','SWE','Västra Götalands län'),
	('SE-T','T','SWE','Örebro län'),
	('SE-E','E','SWE','Östergötlands län'),
	('SE-','','SWE',''),
	('SG-SG','SG','SGP','Singapore'),
	('SG-','','SGP',''),
	('SH-SH','SH','SHN','Saint Helena'),
	('SH-AC','AC','SHN','Ascension'),
	('SH-TA','TA','SHN','Tristan da Cunha'),
	('SI-07','07','SVN','Dolenjska'),
	('SI-09','09','SVN','Gorenjska'),
	('SI-11','11','SVN','Goriška'),
	('SI-03','03','SVN','Koroška'),
	('SI-10','10','SVN','Notranjsko-kraška'),
	('SI-12','12','SVN','Obalno-kraška'),
	('SI-08','08','SVN','Osrednjeslovenska'),
	('SI-02','02','SVN','Podravska'),
	('SI-01','01','SVN','Pomurska'),
	('SI-04','04','SVN','Savinjska'),
	('SI-06','06','SVN','Spodnjeposavska'),
	('SI-05','05','SVN','Zasavska'),
	('SI-','','SVN',''),
	('SJ-SJ','SJ','SJM','Svalbard & Jan Mayen Islands'),
	('SJ-21','21','SJM','Svalbard'),
	('SJ-22','22','SJM','Jan Mayen'),
	('SK-BC','BC','SVK','Banskobystrický kraj'),
	('SK-BL','BL','SVK','Bratislavský kraj'),
	('SK-KI','KI','SVK','Košický kraj'),
	('SK-NI','NI','SVK','Nitriansky kraj'),
	('SK-PV','PV','SVK','Prešovský kraj'),
	('SK-TC','TC','SVK','Trenčiansky kraj'),
	('SK-TA','TA','SVK','Trnavský kraj'),
	('SK-ZI','ZI','SVK','Žilinský kraj'),
	('SL-W','W','SLE','Western Area (Freetown)'),
	('SL-E','E','SLE','Eastern'),
	('SL-N','N','SLE','Northern'),
	('SL-S','S','SLE','Southern'),
	('SM-SM','SM','SMR','San Marino'),
	('SM-','','SMR',''),
	('SN-DK','DK','SEN','Dakar'),
	('SN-DB','DB','SEN','Diourbel'),
	('SN-FK','FK','SEN','Fatick'),
	('SN-KL','KL','SEN','Kaolack'),
	('SN-KD','KD','SEN','Kolda'),
	('SN-LG','LG','SEN','Louga'),
	('SN-SL','SL','SEN','Saint-Louis'),
	('SN-TC','TC','SEN','Tambacounda'),
	('SN-TH','TH','SEN','Thiès'),
	('SN-ZG','ZG','SEN','Ziguinchor'),
	('SO-AW','AW','SOM','Awdal'),
	('SO-BK','BK','SOM','Bakool'),
	('SO-BN','BN','SOM','Banaadir'),
	('SO-BR','BR','SOM','Bari'),
	('SO-BY','BY','SOM','BaY'),
	('SO-GA','GA','SOM','Galguduud'),
	('SO-GE','GE','SOM','Gedo'),
	('SO-HI','HI','SOM','Hiiraan'),
	('SO-JD','JD','SOM','Jubbada Dhexe'),
	('SO-JH','JH','SOM','Jubbada Hoose'),
	('SO-MU','MU','SOM','Mudug'),
	('SO-NU','NU','SOM','Nugaal'),
	('SO-SA','SA','SOM','Sanaag'),
	('SO-SD','SD','SOM','Shabeellaha Dhexe'),
	('SO-SH','SH','SOM','Shabeellaha Hoose'),
	('SO-SO','SO','SOM','Sool'),
	('SO-TO','TO','SOM','Togdheer'),
	('SO-WO','WO','SOM','Woqooyi Galbeed'),
	('SR-BR','BR','SUR','Brokopondo'),
	('SR-CM','CM','SUR','Commewijne'),
	('SR-CR','CR','SUR','Coronie'),
	('SR-MA','MA','SUR','Marowijne'),
	('SR-NI','NI','SUR','Nickerie'),
	('SR-PR','PR','SUR','Para'),
	('SR-PM','PM','SUR','Paramaribo'),
	('SR-SA','SA','SUR','Saramacca'),
	('SR-SI','SI','SUR','Sipaliwini'),
	('SR-WA','WA','SUR','Wanica'),
	('ST-P','P','STP','Príncipe'),
	('ST-S','S','STP','Sāo Tomé'),
	('SV-AH','AH','SLV','Ahuachapán'),
	('SV-CA','CA','SLV','Cabañas'),
	('SV-CU','CU','SLV','Cuscatlán'),
	('SV-CH','CH','SLV','Chalatenango'),
	('SV-LI','LI','SLV','La Libertad'),
	('SV-PA','PA','SLV','La Paz'),
	('SV-UN','UN','SLV','La Unión'),
	('SV-MO','MO','SLV','Morazán'),
	('SV-SM','SM','SLV','San Miguel'),
	('SV-SS','SS','SLV','San Salvador'),
	('SV-SA','SA','SLV','Santa Ana'),
	('SV-SV','SV','SLV','San Vicente'),
	('SV-SO','SO','SLV','Sonsonate'),
	('SV-SU','SU','SLV','Usulután'),
	('SY-HA','HA','SYR','Al Ḩasakah'),
	('SY-LA','LA','SYR','Al Lādhiqīyah'),
	('SY-QU','QU','SYR','Al Qunayţirah'),
	('SY-RA','RA','SYR','Ar Raqqah'),
	('SY-SU','SU','SYR','As Suwaydā\''),
	('SY-DR','DR','SYR','Dar’ā'),
	('SY-DY','DY','SYR','Dayr az Zawr'),
	('SY-DI','DI','SYR','Dimashq'),
	('SY-HL','HL','SYR','Ḩalab'),
	('SY-HM','HM','SYR','Ḩamāh'),
	('SY-HI','HI','SYR','Ḩimş'),
	('SY-ID','ID','SYR','Idlib'),
	('SY-RD','RD','SYR','Rīf Dimashq'),
	('SY-TA','TA','SYR','Ţarţūs'),
	('SZ-HH','HH','SWZ','Hhohho'),
	('SZ-LU','LU','SWZ','Lubombo'),
	('SZ-MA','MA','SWZ','Manzini'),
	('SZ-SH','SH','SWZ','Shiselweni'),
	('TC-TC','TC','TCA','Turks & Caicos Islands'),
	('TD-BA','BA','TCD','Batha'),
	('TD-BI','BI','TCD','Biltine'),
	('TD-BET','BET','TCD','Borkou-Ennedi-Tibesti'),
	('TD-CB','CB','TCD','Chari-Baguirmi'),
	('TD-GR','GR','TCD','Guéra'),
	('TD-KA','KA','TCD','Kanem'),
	('TD-LC','LC','TCD','Lac'),
	('TD-LO','LO','TCD','Logone-Occidental'),
	('TD-LR','LR','TCD','Logone-Oriental'),
	('TD-MK','MK','TCD','Mayo-Kébbi'),
	('TD-MC','MC','TCD','Moyen-Chari'),
	('TD-OD','OD','TCD','Ouaddaï'),
	('TD-SA','SA','TCD','Salamat'),
	('TD-TA','TA','TCD','Tandjilé'),
	('TG-C','C','TGO','Centre'),
	('TG-K','K','TGO','Kara'),
	('TG-M','M','TGO','Maritime (Région)'),
	('TG-P','P','TGO','Plateaux'),
	('TG-S','S','TGO','Savannes'),
	('TH-10','10','THA','Krung Thep Maha Nakhon [Bangkok]'),
	('TH-S','S','THA','Phatthaya'),
	('TH-37','37','THA','Amnat Charoen'),
	('TH-15','15','THA','Ang Thong'),
	('TH-31','31','THA','Buri Ram'),
	('TH-24','24','THA','Chachoengsao'),
	('TH-18','18','THA','Chai Nat'),
	('TH-36','36','THA','Chaiyaphum'),
	('TH-22','22','THA','Chanthaburi'),
	('TH-50','50','THA','Chiang Mai'),
	('TH-57','57','THA','Chiang Rai'),
	('TH-20','20','THA','Chon Buri'),
	('TH-86','86','THA','Chumphon'),
	('TH-46','46','THA','Kalasin'),
	('TH-62','62','THA','Kamphaeng Phet'),
	('TH-71','71','THA','Kanchanaburi'),
	('TH-40','40','THA','Khon Kaen'),
	('TH-81','81','THA','Krabi'),
	('TH-52','52','THA','Lampang'),
	('TH-51','51','THA','Lamphun'),
	('TH-42','42','THA','Loei'),
	('TH-16','16','THA','Lop Buri'),
	('TH-58','58','THA','Mae Hong Son'),
	('TH-44','44','THA','Maha Sarakham'),
	('TH-49','49','THA','Mukdahan'),
	('TH-26','26','THA','Nakhon Nayok'),
	('TH-73','73','THA','Nakhon Pathom'),
	('TH-48','48','THA','Nakhon Phanom'),
	('TH-30','30','THA','Nakhon Ratchasima'),
	('TH-60','60','THA','Nakhon Sawan'),
	('TH-80','80','THA','Nakhon Si Thammarat'),
	('TH-55','55','THA','Nan'),
	('TH-96','96','THA','Narathiwat'),
	('TH-39','39','THA','Nong Bua Lam Phu'),
	('TH-43','43','THA','Nong Khai'),
	('TH-12','12','THA','Nonthaburi'),
	('TH-13','13','THA','Pathum Thani'),
	('TH-94','94','THA','Pattani'),
	('TH-82','82','THA','Phangnga'),
	('TH-93','93','THA','Phatthalung'),
	('TH-56','56','THA','Phayao'),
	('TH-67','67','THA','Phetchabun'),
	('TH-76','76','THA','Phetchaburi'),
	('TH-66','66','THA','Phichit'),
	('TH-65','65','THA','Phitsanulok'),
	('TH-54','54','THA','Phrae'),
	('TH-14','14','THA','Phra Nakhon Si Ayutthaya'),
	('TH-83','83','THA','Phuket'),
	('TH-25','25','THA','Prachin Buri'),
	('TH-77','77','THA','Prachuap Khiri Khan'),
	('TH-85','85','THA','Ranong'),
	('TH-70','70','THA','Ratchaburi'),
	('TH-21','21','THA','Rayong'),
	('TH-45','45','THA','Roi Et'),
	('TH-27','27','THA','Sa Kaeo'),
	('TH-47','47','THA','Sakon Nakhon'),
	('TH-11','11','THA','Samut Prakan'),
	('TH-74','74','THA','Samut Sakhon'),
	('TH-75','75','THA','Samut Songkhram'),
	('TH-19','19','THA','Saraburi'),
	('TH-91','91','THA','Satun'),
	('TH-17','17','THA','Sing Buri'),
	('TH-33','33','THA','Si Sa Ket'),
	('TH-90','90','THA','Songkhla'),
	('TH-64','64','THA','Sukhothai'),
	('TH-72','72','THA','Suphan Buri'),
	('TH-84','84','THA','Surat Thani'),
	('TH-32','32','THA','Surin'),
	('TH-63','63','THA','Tak'),
	('TH-92','92','THA','Trang'),
	('TH-23','23','THA','Trat'),
	('TH-34','34','THA','Ubon Ratchathani'),
	('TH-41','41','THA','Udon Thani'),
	('TH-61','61','THA','Uthai Thani'),
	('TH-53','53','THA','Uttaradit'),
	('TH-95','95','THA','Yala'),
	('TH-35','35','THA','Yasothon'),
	('TH-','','THA','Na Tan'),
	('TJ-KR','KR','TJK','Karategin'),
	('TJ-KT','KT','TJK','Khatlon'),
	('TJ-LN','LN','TJK','Leninabad'),
	('TJ-GB','GB','TJK','Gorno-Badakhshan'),
	('TK-TK','TK','TKL','Tokelau'),
	('TM-A','A','TKM','Ahal'),
	('TM-B','B','TKM','Balkan'),
	('TM-D','D','TKM','Daşhowuz'),
	('TM-L','L','TKM','Lebap'),
	('TM-M','M','TKM','Mary'),
	('TN-31','31','TUN','Béja'),
	('TN-13','13','TUN','Ben Arous'),
	('TN-23','23','TUN','Bizerte'),
	('TN-81','81','TUN','Gabès'),
	('TN-71','71','TUN','Gafsa'),
	('TN-32','32','TUN','Jendouba'),
	('TN-41','41','TUN','Kairouan'),
	('TN-42','42','TUN','Kasserine'),
	('TN-73','73','TUN','Kebili'),
	('TN-12','12','TUN','L\'Ariana'),
	('TN-33','33','TUN','Le Kef'),
	('TN-53','53','TUN','Mahdia'),
	('TN-82','82','TUN','Medenine'),
	('TN-52','52','TUN','Monastir'),
	('TN-21','21','TUN','Nabeul'),
	('TN-61','61','TUN','Sfax'),
	('TN-43','43','TUN','Sidi Bouzid'),
	('TN-34','34','TUN','Siliana'),
	('TN-51','51','TUN','Sousse'),
	('TN-83','83','TUN','Tataouine'),
	('TN-72','72','TUN','Tozeur'),
	('TN-11','11','TUN','Tunis'),
	('TN-22','22','TUN','Zaghouan'),
	('TO-TO','TO','TON','Tonga'),
	('TR-01','01','TUR','Adana'),
	('TR-02','02','TUR','Adiyaman'),
	('TR-03','03','TUR','Afyon'),
	('TR-04','04','TUR','Ağrı'),
	('TR-68','68','TUR','Aksaray'),
	('TR-05','05','TUR','Amasya'),
	('TR-06','06','TUR','Ankara'),
	('TR-07','07','TUR','Antalya'),
	('TR-75','75','TUR','Ardahan'),
	('TR-08','08','TUR','Artvin'),
	('TR-09','09','TUR','Aydin'),
	('TR-10','10','TUR','Balıkesir'),
	('TR-74','74','TUR','Bartın'),
	('TR-72','72','TUR','Batman'),
	('TR-69','69','TUR','Bayburt'),
	('TR-11','11','TUR','Bilecik'),
	('TR-12','12','TUR','Bingöl'),
	('TR-13','13','TUR','Bitlis'),
	('TR-14','14','TUR','Bolu'),
	('TR-15','15','TUR','Burdur'),
	('TR-16','16','TUR','Bursa'),
	('TR-17','17','TUR','Çanakkale'),
	('TR-18','18','TUR','Çankırı'),
	('TR-19','19','TUR','Çorum'),
	('TR-20','20','TUR','Denizli'),
	('TR-21','21','TUR','Diyarbakır'),
	('TR-22','22','TUR','Edirne'),
	('TR-23','23','TUR','Elaziğ'),
	('TR-24','24','TUR','Erzincan'),
	('TR-25','25','TUR','Erzurum'),
	('TR-26','26','TUR','Eskişehir'),
	('TR-27','27','TUR','Gaziantep'),
	('TR-28','28','TUR','Giresun'),
	('TR-29','29','TUR','Gümüşhane'),
	('TR-30','30','TUR','Hakkari'),
	('TR-31','31','TUR','Hatay'),
	('TR-76','76','TUR','Iğdir'),
	('TR-32','32','TUR','Isparta'),
	('TR-33','33','TUR','İçel'),
	('TR-34','34','TUR','İstanbul'),
	('TR-35','35','TUR','İzmir'),
	('TR-46','46','TUR','Kahramanmaraş'),
	('TR-78','78','TUR','Karabük'),
	('TR-70','70','TUR','Karaman'),
	('TR-36','36','TUR','Kars'),
	('TR-37','37','TUR','Kastamonu'),
	('TR-38','38','TUR','Kayseri'),
	('TR-71','71','TUR','Kırıkkale'),
	('TR-39','39','TUR','Kırklareli'),
	('TR-40','40','TUR','Kırşehir'),
	('TR-79','79','TUR','Kilis'),
	('TR-41','41','TUR','Kocaeli'),
	('TR-42','42','TUR','Konya'),
	('TR-43','43','TUR','Kütahya'),
	('TR-44','44','TUR','Malatya'),
	('TR-4S','4S','TUR','Manisa'),
	('TR-47','47','TUR','Mardin'),
	('TR-48','48','TUR','Muğla'),
	('TR-49','49','TUR','Muş'),
	('TR-SO','SO','TUR','Nevşehir'),
	('TR-51','51','TUR','Niğde'),
	('TR-52','52','TUR','Ordu'),
	('TR-53','53','TUR','Rize'),
	('TR-54','54','TUR','Sakarya'),
	('TR-SS','SS','TUR','Samsun'),
	('TR-56','56','TUR','Siirt'),
	('TR-57','57','TUR','Sinop'),
	('TR-S8','S8','TUR','Sivas'),
	('TR-63','63','TUR','Şanlıurfa'),
	('TR-73','73','TUR','Şirnak'),
	('TR-59','59','TUR','Tekirdağ'),
	('TR-60','60','TUR','Tokat'),
	('TR-61','61','TUR','Trabzon'),
	('TR-62','62','TUR','Tunceli'),
	('TR-64','64','TUR','Uşak'),
	('TR-65','65','TUR','Van'),
	('TR-77','77','TUR','Yalova'),
	('TR-66','66','TUR','Yozgat'),
	('TR-67','67','TUR','Zonguldak'),
	('TR-45','45','TUR','Manisa'),
	('TR-50','50','TUR','Nevşehir'),
	('TR-55','55','TUR','Samsun'),
	('TR-58','58','TUR','Sivas'),
	('TR-80','80','TUR','Şirnak'),
	('TR-81','81','TUR','Adana'),
	('TR-82','82','TUR','Çankiri'),
	('TR-83','83','TUR','Gaziantep'),
	('TR-84','84','TUR','Kars'),
	('TR-85','85','TUR','Zonguldak'),
	('TR-86','86','TUR','Ardahan'),
	('TR-87','87','TUR','Bartin'),
	('TR-88','88','TUR','Iğdir'),
	('TR-89','89','TUR','Karabük'),
	('TR-90','90','TUR','Kilis'),
	('TR-91','91','TUR','Osmaniye'),
	('TR-92','92','TUR','Yalova'),
	('TR-93','93','TUR','Düzce'),
	('TR-','','TUR','Kktc'),
	('TT-CTT','CTT','TTO','Couva-Tabaquite-Talparo'),
	('TT-DMN','DMN','TTO','Diego Martin'),
	('TT-ETO','ETO','TTO','Eastern Tobago'),
	('TT-PED','PED','TTO','Penal-Debe'),
	('TT-PRT','PRT','TTO','Princes Town'),
	('TT-RCM','RCM','TTO','Rio Claro-Mayaro'),
	('TT-SGE','SGE','TTO','Sangre Grande'),
	('TT-SJL','SJL','TTO','San Juan-Laventille'),
	('TT-SIP','SIP','TTO','Siparia'),
	('TT-TUP','TUP','TTO','Tunapuna-Piarco'),
	('TT-WTO','WTO','TTO','Western Tobago'),
	('TT-ARI','ARI','TTO','Arima'),
	('TT-CHA','CHA','TTO','Chaguanas'),
	('TT-PTF','PTF','TTO','Point Fortin'),
	('TT-POS','POS','TTO','Port of Spain'),
	('TT-SFO','SFO','TTO','San Fernando'),
	('TV-TV','TV','TUV','Tuvalu'),
	('TW-KHH','KHH','TWN','Kaohsiung'),
	('TW-TPE','TPE','TWN','Taipei'),
	('TW-CYI','CYI','TWN','Chiayi'),
	('TW-HSZ','HSZ','TWN','Hsinchu'),
	('TW-KEE','KEE','TWN','Keelung'),
	('TW-TXG','TXG','TWN','Taichung'),
	('TW-TNN','TNN','TWN','Tainan'),
	('TW-CHA','CHA','TWN','Changhua'),
	('TW-HUA','HUA','TWN','Hualien'),
	('TW-ILA','ILA','TWN','Ilan'),
	('TW-MIA','MIA','TWN','Miaoli'),
	('TW-NAN','NAN','TWN','Nantou'),
	('TW-PEN','PEN','TWN','Penghu'),
	('TW-PIF','PIF','TWN','Pingtung'),
	('TW-TTT','TTT','TWN','Taitung'),
	('TW-TAO','TAO','TWN','Taoyuan'),
	('TW-YUN','YUN','TWN','Yunlin'),
	('TZ-01','01','TZA','Arusha'),
	('TZ-02','02','TZA','Dar-es-Salaam'),
	('TZ-03','03','TZA','Dodoma'),
	('TZ-04','04','TZA','Iringa'),
	('TZ-05','05','TZA','Kagera'),
	('TZ-06','06','TZA','Kaskazini Pemba (Pemba North)'),
	('TZ-07','07','TZA','Kaskazini Unguja (Zanzibar North)'),
	('TZ-08','08','TZA','Kigoma'),
	('TZ-09','09','TZA','Kilimanjaro'),
	('TZ-10','10','TZA','Kusini Pemba (Pemba South)'),
	('TZ-11','11','TZA','Kusini Unguja (Zanzibar South)'),
	('TZ-12','12','TZA','Lindi'),
	('TZ-13','13','TZA','Mara'),
	('TZ-14','14','TZA','Mbeya'),
	('TZ-15','15','TZA','Mjini Magharibi (Zanzibar West)'),
	('TZ-16','16','TZA','Morogoro'),
	('TZ-17','17','TZA','Mtwara'),
	('TZ-18','18','TZA','Mwanza'),
	('TZ-19','19','TZA','Pwani (Coast)'),
	('TZ-20','20','TZA','Rukwa'),
	('TZ-21','21','TZA','Ruvuma'),
	('TZ-22','22','TZA','Shinyanga'),
	('TZ-23','23','TZA','Singida'),
	('TZ-24','24','TZA','Tabora'),
	('TZ-25','25','TZA','Tanga'),
	('UA-71','71','UKR','Cherkas\'ka Oblast''),
	('UA-74','74','UKR','Chernihivs\'ka Oblast''),
	('UA-77','77','UKR','Chernivets\'ka Oblast''),
	('UA-12','12','UKR','Dnipropetrovs\'ka Oblast''),
	('UA-14','14','UKR','Donets\'ka Oblast''),
	('UA-26','26','UKR','Ivano-Frankivs\'ka Oblast''),
	('UA-63','63','UKR','Kharkivs\'ka Oblast''),
	('UA-65','65','UKR','Khersons\'ka Oblast''),
	('UA-68','68','UKR','Khmel\'nyts'ka Oblast''),
	('UA-35','35','UKR','Kirovohrads\'ka Oblast''),
	('UA-32','32','UKR','Kyïvs\'ka Oblast''),
	('UA-09','09','UKR','Luhans\'ka Oblast''),
	('UA-46','46','UKR','L\'vivs'ka Oblast''),
	('UA-48','48','UKR','Mykolaïvs\'ka Oblast''),
	('UA-51','51','UKR','Odes\'ka Oblast''),
	('UA-53','53','UKR','Poltavs\'ka Oblast''),
	('UA-56','56','UKR','Rivnens\'ka Oblast''),
	('UA-59','59','UKR','Sums\'ka Oblast''),
	('UA-61','61','UKR','Ternopil\'s'ka Oblast''),
	('UA-05','05','UKR','Vinnyts\'ka Oblast''),
	('UA-07','07','UKR','Volyns\'ka Oblast''),
	('UA-21','21','UKR','Zakarpats\'ka Oblast''),
	('UA-23','23','UKR','Zaporiz\'ka Oblast''),
	('UA-18','18','UKR','Zhytomyrs\'ka Oblast''),
	('UA-43','43','UKR','Respublika Krym'),
	('UA-30','30','UKR','Kyïv'),
	('UA-40','40','UKR','Sevastopol\''),
	('UA-01','01','UKR','Cherkaska'),
	('UA-02','02','UKR','Chernihivska'),
	('UA-03','03','UKR','Chernivetska'),
	('UA-04','04','UKR','Dnipropetrovska'),
	('UA-06','06','UKR','Ivano-Frankivska'),
	('UA-08','08','UKR','Khersonska'),
	('UA-10','10','UKR','Kirovohradska'),
	('UA-13','13','UKR','Kyiv'),
	('UA-15','15','UKR','Lvivska'),
	('UA-16','16','UKR','Mykolaivska'),
	('UA-17','17','UKR','Odeska'),
	('UA-19','19','UKR','Rivnenska'),
	('UA-22','22','UKR','Ternopilska'),
	('UA-24','24','UKR','Volynska'),
	('UA-25','25','UKR','Zakarpatska'),
	('UA-27','27','UKR','Zhytomyrska'),
	('UG-APA','APA','UGA','Apac'),
	('UG-ARU','ARU','UGA','Arua'),
	('UG-BUN','BUN','UGA','Bundibugyo'),
	('UG-BUS','BUS','UGA','Bushenyi'),
	('UG-GUL','GUL','UGA','Gulu'),
	('UG-HOI','HOI','UGA','Hoima'),
	('UG-IGA','IGA','UGA','Iganga'),
	('UG-JIN','JIN','UGA','Jinja'),
	('UG-KBL','KBL','UGA','Kabale'),
	('UG-KBR','KBR','UGA','Kabarole'),
	('UG-KLG','KLG','UGA','Kalangala'),
	('UG-KLA','KLA','UGA','Kampala'),
	('UG-KLI','KLI','UGA','Kamuli'),
	('UG-KAP','KAP','UGA','Kapchorwa'),
	('UG-KAS','KAS','UGA','Kasese'),
	('UG-KLE','KLE','UGA','Kibaale'),
	('UG-KIB','KIB','UGA','Kiboga'),
	('UG-KIS','KIS','UGA','Kisoro'),
	('UG-KIT','KIT','UGA','Kitgum'),
	('UG-KOT','KOT','UGA','Kotido'),
	('UG-KUM','KUM','UGA','Kumi'),
	('UG-LIR','LIR','UGA','Lira'),
	('UG-LUW','LUW','UGA','Luwero'),
	('UG-MSK','MSK','UGA','Masaka'),
	('UG-MSI','MSI','UGA','Masindi'),
	('UG-MBL','MBL','UGA','Mbale'),
	('UG-MBR','MBR','UGA','Mbarara'),
	('UG-MOR','MOR','UGA','Moroto'),
	('UG-MOY','MOY','UGA','Moyo'),
	('UG-MPI','MPI','UGA','Mpigi'),
	('UG-MUB','MUB','UGA','Mubende'),
	('UG-MUK','MUK','UGA','Mukono'),
	('UG-NEB','NEB','UGA','Nebbi'),
	('UG-NTU','NTU','UGA','Ntungamo'),
	('UG-PAL','PAL','UGA','Pallisa'),
	('UG-RAK','RAK','UGA','Rakai'),
	('UG-RUK','RUK','UGA','Rukungiri'),
	('UG-SOR','SOR','UGA','Soroti'),
	('UG-TOR','TOR','UGA','Tororo'),
	('US-AL','AL','USA','Alabama'),
	('US-AK','AK','USA','Alaska'),
	('US-AZ','AZ','USA','Arizona'),
	('US-AR','AR','USA','Arkansas'),
	('US-CA','CA','USA','California'),
	('US-CO','CO','USA','Colorado'),
	('US-CT','CT','USA','Connecticut'),
	('US-DE','DE','USA','Delaware'),
	('US-FL','FL','USA','Florida'),
	('US-GA','GA','USA','Georgia'),
	('US-HI','HI','USA','Hawaii'),
	('US-ID','ID','USA','Idaho'),
	('US-IL','IL','USA','Illinois'),
	('US-IN','IN','USA','Indiana'),
	('US-IA','IA','USA','Iowa'),
	('US-KS','KS','USA','Kansas'),
	('US-KY','KY','USA','Kentucky'),
	('US-LA','LA','USA','Louisiana'),
	('US-ME','ME','USA','Maine'),
	('US-MD','MD','USA','Maryland'),
	('US-MA','MA','USA','Massachusetts'),
	('US-MI','MI','USA','Michigan'),
	('US-MN','MN','USA','Minnesota'),
	('US-MS','MS','USA','Mississippi'),
	('US-MO','MO','USA','Missouri'),
	('US-MT','MT','USA','Montana'),
	('US-NE','NE','USA','Nebraska'),
	('US-NV','NV','USA','Nevada'),
	('US-NH','NH','USA','New Hampshire'),
	('US-NJ','NJ','USA','New Jersey'),
	('US-NM','NM','USA','New Mexico'),
	('US-NY','NY','USA','New York'),
	('US-NC','NC','USA','North Carolina'),
	('US-ND','ND','USA','North Dakota'),
	('US-OH','OH','USA','Ohio'),
	('US-OK','OK','USA','Oklahoma'),
	('US-OR','OR','USA','Oregon'),
	('US-PA','PA','USA','Pennsylvania'),
	('US-RI','RI','USA','Rhode Island'),
	('US-SC','SC','USA','South Carolina'),
	('US-SD','SD','USA','South Dakota'),
	('US-TN','TN','USA','Tennessee'),
	('US-TX','TX','USA','Texas'),
	('US-UT','UT','USA','Utah'),
	('US-VT','VT','USA','Vermont'),
	('US-VA','VA','USA','Virginia'),
	('US-WA','WA','USA','Washington'),
	('US-WV','WV','USA','West Virginia'),
	('US-WI','WI','USA','Wisconsin'),
	('US-WY','WY','USA','Wyoming'),
	('US-DC','DC','USA','District of Columbia'),
	('US-AS','AS','USA','American Samoa'),
	('US-GU','GU','USA','Guam'),
	('US-MP','MP','USA','Northern Mariana Islands'),
	('US-PR','PR','USA','Puerto Rico'),
	('US-UM','UM','USA','United States Minor Outlying Islands'),
	('US-VI','VI','USA','Virgin Islands, U.S.'),
	('US-MH','MH','USA',''),
	('US-','','USA',''),
	('UY-AR','AR','URY','Artigas'),
	('UY-CA','CA','URY','Canelones'),
	('UY-CL','CL','URY','Cerro Largo'),
	('UY-CO','CO','URY','Colonia'),
	('UY-DU','DU','URY','Durazno'),
	('UY-FS','FS','URY','Flores'),
	('UY-FD','FD','URY','Florida'),
	('UY-LA','LA','URY','Lavalleja'),
	('UY-MA','MA','URY','Maldonado'),
	('UY-MO','MO','URY','Montevideo'),
	('UY-PA','PA','URY','Paysandú'),
	('UY-RN','RN','URY','Río Negro'),
	('UY-RV','RV','URY','Rivera'),
	('UY-RO','RO','URY','Rocha'),
	('UY-SA','SA','URY','Salto'),
	('UY-SJ','SJ','URY','San José'),
	('UY-SO','SO','URY','Soriano'),
	('UY-TA','TA','URY','Tacuarembó'),
	('UY-TT','TT','URY','Treinta y Tres'),
	('UY-01','01','URY','Artigas'),
	('UY-02','02','URY','Canelones'),
	('UY-03','03','URY','Cerro Largo'),
	('UY-04','04','URY','Colonia'),
	('UY-05','05','URY','Durazno'),
	('UY-06','06','URY','Flores'),
	('UY-07','07','URY','Florida'),
	('UY-08','08','URY','Lavalleja'),
	('UY-09','09','URY','Maldonado'),
	('UY-10','10','URY','Montevideo'),
	('UY-11','11','URY','Paysandu'),
	('UY-12','12','URY','Rio Negro'),
	('UY-13','13','URY','Rivera'),
	('UY-14','14','URY','Rocha'),
	('UY-15','15','URY','Salto'),
	('UY-16','16','URY','San Jose'),
	('UY-17','17','URY','Soriano'),
	('UY-18','18','URY','Tacuarembo'),
	('UY-19','19','URY','Treinta y Tres'),
	('UZ-QR','QR','UZB','Qoraqalpoghiston Respublikasi (Karakalpakstan, Respublika)'),
	('UZ-AN','AN','UZB','Andijon (Andizhan)'),
	('UZ-BU','BU','UZB','Bukhoro (Bukhara)'),
	('UZ-FA','FA','UZB','Farghona (Fergana)'),
	('UZ-JI','JI','UZB','Jizzakh (Dzhizak)'),
	('UZ-KH','KH','UZB','Khorazm (Khorezm)'),
	('UZ-NG','NG','UZB','Namangan'),
	('UZ-NW','NW','UZB','Nawoiy (Navoi)'),
	('UZ-QA','QA','UZB','Qashqadaryo (Kashkadar\'ya)'),
	('UZ-SA','SA','UZB','Samarqand (Samarkand)'),
	('UZ-SI','SI','UZB','Sirdaryo (Syrdar\'ya)'),
	('UZ-SU','SU','UZB','Surkhondaryo (Surkhandar\'ya)'),
	('UZ-TO','TO','UZB','Toshkent (Tashkent)');
COMMIT;
ANALYZE;
