BEGIN;
INSERT INTO regions (iso3, iso2, country, name) VALUES
	('AD-AD','AD','AND','Andorra'),
	('AD-','','AND',''),
	('AE-AZ','AZ','ARE','Abū Zaby (Abu Dhabi)'),
	('AE-AJ','AJ','ARE','‘Ajmān'),
	('AE-FU','FU','ARE','Al Fujayrah'),
	('AE-SH','SH','ARE','Ash Shāriqah (Sharjah)'),
	('AE-DU','DU','ARE','Dubayy (Dubai)'),
	('AE-RK','RK','ARE','R'as al Khaymah'),
	('AE-UQ','UQ','ARE','Umm al Qaywayn'),
	('AF-BDS','BDS','AFG','Badakhshān'),
	('AF-BDG','BDG','AFG','Bādghīs'),
	('AF-BGL','BGL','AFG','Baghlān'),
	('AF-BAL','BAL','AFG','Balkh'),
	('AF-BAM','BAM','AFG','Bāmīān'),
	('AF-FRA','FRA','AFG','Farāh'),
	('AF-FYB','FYB','AFG','Fāryāb'),
	('AF-GHA','GHA','AFG','Ghaznī'),
	('AF-GHO','GHO','AFG','Ghowr'),
	('AF-HEL','HEL','AFG','Helmand'),
	('AF-HER','HER','AFG','Herāt'),
	('AF-JOW','JOW','AFG','Jowzjān'),
	('AF-KAB','KAB','AFG','Kabul (Kābol)'),
	('AF-KAN','KAN','AFG','Kandahār'),
	('AF-KAP','KAP','AFG','Kāpīsā'),
	('AF-KNR','KNR','AFG','Konar (Kunar)'),
	('AF-KDZ','KDZ','AFG','Kondoz (Kunduz)'),
	('AF-LAG','LAG','AFG','Laghmān'),
	('AF-LOW','LOW','AFG','Lowgar'),
	('AF-NAN','NAN','AFG','Nangrahār (Nangarhār)'),
	('AF-NIM','NIM','AFG','Nīmrūz'),
	('AF-ORU','ORU','AFG','Orūzgān (Urūzgā'),
	('AF-PIA','PIA','AFG','Paktīā'),
	('AF-PKA','PKA','AFG','Paktīkā'),
	('AF-PAR','PAR','AFG','Parwān'),
	('AF-SAM','SAM','AFG','Samangān'),
	('AF-SAR','SAR','AFG','Sar-e Pol'),
	('AF-TAK','TAK','AFG','Takhār'),
	('AF-WAR','WAR','AFG','Wardak (Wardag)'),
	('AF-ZAB','ZAB','AFG','Zābol (Zābul)'),
	('AG-AG','AG','ATG','Antigua & Barbuda'),
	('AI-AI','AI','AIA','Anguilla'),
	('AL-BR','BR','ALB','Berat'),
	('AL-BU','BU','ALB','Bulqizë'),
	('AL-DL','DL','ALB','Delvinë'),
	('AL-DV','DV','ALB','Devoll'),
	('AL-DI','DI','ALB','Dibër'),
	('AL-DR','DR','ALB','Durrës'),
	('AL-EL','EL','ALB','Elbasan'),
	('AL-FR','FR','ALB','Fier'),
	('AL-GR','GR','ALB','Gramsh'),
	('AL-GJ','GJ','ALB','Gjirokastër'),
	('AL-HA','HA','ALB','Has'),
	('AL-KA','KA','ALB','Kavajë'),
	('AL-ER','ER','ALB','Kolonjë'),
	('AL-KO','KO','ALB','Korcë'),
	('AL-KR','KR','ALB','Krujë'),
	('AL-KC','KC','ALB','Kucovë'),
	('AL-KU','KU','ALB','Kukës'),
	('AL-LA','LA','ALB','Laç'),
	('AL-LE','LE','ALB','Lezhë'),
	('AL-LB','LB','ALB','Librazhd'),
	('AL-LU','LU','ALB','Lushnjë'),
	('AL-MM','MM','ALB','Malësia e Madhe'),
	('AL-MK','MK','ALB','Mallakastër'),
	('AL-MT','MT','ALB','Mat'),
	('AL-MR','MR','ALB','Mirditë'),
	('AL-PQ','PQ','ALB','Peqin'),
	('AL-PR','PR','ALB','Përmet'),
	('AL-PG','PG','ALB','Pogradec'),
	('AL-PU','PU','ALB','Pukë'),
	('AL-SR','SR','ALB','Sarandë'),
	('AL-SK','SK','ALB','Skrapar'),
	('AL-SH','SH','ALB','Shkodër'),
	('AL-TE','TE','ALB','Tepelenë'),
	('AL-TR','TR','ALB','Tiranë'),
	('AL-TP','TP','ALB','Tropojë'),
	('AL-VL','VL','ALB','Vlorë'),
	('AM-ER','ER','ARM','Erevan'),
	('AM-AG','AG','ARM','Aragacotn'),
	('AM-AR','AR','ARM','Ararat'),
	('AM-AV','AV','ARM','Armavir'),
	('AM-GR','GR','ARM','Geģark'unik''),
	('AM-KT','KT','ARM','Kotayk''),
	('AM-LO','LO','ARM','Loŕy'),
	('AM-SH','SH','ARM','Širak'),
	('AM-SU','SU','ARM','Syunik''),
	('AM-TV','TV','ARM','Tavuš'),
	('AM-VD','VD','ARM','Vayoc Jor'),
	('AO-BGO','BGO','AGO','Bengo'),
	('AO-BGU','BGU','AGO','Benguela'),
	('AO-BIE','BIE','AGO','Bié'),
	('AO-CAB','CAB','AGO','Cabinda'),
	('AO-CCU','CCU','AGO','Cuando-Cubango'),
	('AO-CNO','CNO','AGO','Cuanza Norte'),
	('AO-CUS','CUS','AGO','Cuanza Sul'),
	('AO-CNN','CNN','AGO','Cunene'),
	('AO-HUA','HUA','AGO','Huambo'),
	('AO-HUI','HUI','AGO','Huíla'),
	('AO-LUA','LUA','AGO','Luanda'),
	('AO-LNO','LNO','AGO','Lunda Norte'),
	('AO-LSU','LSU','AGO','Lunda Sul'),
	('AO-MAL','MAL','AGO','Malange'),
	('AO-MOX','MOX','AGO','Moxico'),
	('AO-NAM','NAM','AGO','Namibe'),
	('AO-UIG','UIG','AGO','Uíge'),
	('AO-ZAI','ZAI','AGO','Zaïre'),
	('AQ-AQ','AQ','ATA','Antarctica'),
	('AR-C','C','ARG','Capital federal'),
	('AR-B','B','ARG','Buenos Aires'),
	('AR-K','K','ARG','Catamarca'),
	('AR-X','X','ARG','Córdoba'),
	('AR-W','W','ARG','Corrientes'),
	('AR-H','H','ARG','Chaco'),
	('AR-U','U','ARG','Chubut'),
	('AR-E','E','ARG','Entre Ríos'),
	('AR-P','P','ARG','Formosa'),
	('AR-Y','Y','ARG','Jujuy'),
	('AR-L','L','ARG','La Pampa'),
	('AR-F','F','ARG','La Rioja'),
	('AR-M','M','ARG','Mendoza'),
	('AR-N','N','ARG','Misiones'),
	('AR-Q','Q','ARG','Neuquén'),
	('AR-R','R','ARG','Río Negro'),
	('AR-A','A','ARG','Salta'),
	('AR-J','J','ARG','San Juan'),
	('AR-D','D','ARG','San Luis'),
	('AR-Z','Z','ARG','Santa Cruz'),
	('AR-S','S','ARG','Santa Fe'),
	('AR-G','G','ARG','Santiago del Estero'),
	('AR-V','V','ARG','Tierra del Fuego'),
	('AR-T','T','ARG','Tucumán'),
	('AS-AS','AS','ASM','American Samoa'),
	('AS-60','60','ASM','As'),
	('AT-1','1','AUT','Burgenland'),
	('AT-2','2','AUT','Kärnten'),
	('AT-3','3','AUT','Niederösterreich'),
	('AT-4','4','AUT','Oberösterreich'),
	('AT-5','5','AUT','Salzburg'),
	('AT-6','6','AUT','Steiermark'),
	('AT-7','7','AUT','Tirol'),
	('AT-8','8','AUT','Vorarlberg'),
	('AT-9','9','AUT','Wien'),
	('AT-01','01','AUT','Burgenland'),
	('AT-02','02','AUT','Kärnten'),
	('AT-03','03','AUT','Niederösterreich'),
	('AT-04','04','AUT','Oberösterreich'),
	('AT-05','05','AUT','Salzburg'),
	('AT-06','06','AUT','Steiermark'),
	('AT-07','07','AUT','Tirol'),
	('AT-08','08','AUT','Vorarlberg'),
	('AT-09','09','AUT','Wien'),
	('AU-NSW','NSW','AUS','New South Wales'),
	('AU-QLD','QLD','AUS','Queensland'),
	('AU-SA','SA','AUS','South Australia'),
	('AU-TAS','TAS','AUS','Tasmania'),
	('AU-VIC','VIC','AUS','Victoria'),
	('AU-WA','WA','AUS','Western Australia'),
	('AU-ACT','ACT','AUS','Australian Capital Territory'),
	('AU-NT','NT','AUS','Northern Territory'),
	('AW-AW','AW','ABW','Aruba'),
	('AX-211','211','ALA','Mariehamns stad'),
	('AX-212','212','ALA','Ålands landsbygd'),
	('AX-213','213','ALA','Ålands skärgård'),
	('AZ-MM','MM','AZE','Naxçivan'),
	('AZ-AB','AB','AZE','Äli Bayramli'),
	('AZ-BA','BA','AZE','Baki'),
	('AZ-GA','GA','AZE','Gäncä'),
	('AZ-LA','LA','AZE','Länkäran'),
	('AZ-MI','MI','AZE','Mingäçevir'),
	('AZ-NA','NA','AZE','Naftalan'),
	('AZ-SA','SA','AZE','Şäki'),
	('AZ-SM','SM','AZE','Sumqayit'),
	('AZ-SS','SS','AZE','Şuşa'),
	('AZ-XA','XA','AZE','Xankändi'),
	('AZ-YE','YE','AZE','Yevlax'),
	('AZ-ABS','ABS','AZE','Abşeron'),
	('AZ-AGC','AGC','AZE','Ağcabädi'),
	('AZ-AGM','AGM','AZE','Ağdam'),
	('AZ-AGS','AGS','AZE','Ağdas'),
	('AZ-AGA','AGA','AZE','Ağstafa'),
	('AZ-AGU','AGU','AZE','Ağsu'),
	('AZ-AST','AST','AZE','Astara'),
	('AZ-BAB','BAB','AZE','Babäk'),
	('AZ-BAL','BAL','AZE','Balakän'),
	('AZ-BAR','BAR','AZE','Bärdä'),
	('AZ-BEY','BEY','AZE','Beyläqan'),
	('AZ-BIL','BIL','AZE','Biläsuvar'),
	('AZ-CAB','CAB','AZE','Cäbrayil'),
	('AZ-CAL','CAL','AZE','Cälilabad'),
	('AZ-CUL','CUL','AZE','Culfa'),
	('AZ-DAS','DAS','AZE','Daşkäsän'),
	('AZ-DAV','DAV','AZE','Däväçi'),
	('AZ-FUZ','FUZ','AZE','Füzuli'),
	('AZ-GAD','GAD','AZE','Gädäbäy'),
	('AZ-GOR','GOR','AZE','Goranboy'),
	('AZ-GOY','GOY','AZE','Göyçay'),
	('AZ-HAC','HAC','AZE','Haciqabul'),
	('AZ-IMI','IMI','AZE','Imişli'),
	('AZ-ISM','ISM','AZE','Ismayilli'),
	('AZ-KAL','KAL','AZE','Kälbäcär'),
	('AZ-KUR','KUR','AZE','Kürdämir'),
	('AZ-LAC','LAC','AZE','Laçin'),
	('AZ-LAN','LAN','AZE','Länkäran'),
	('AZ-LER','LER','AZE','Lerik'),
	('AZ-MAS','MAS','AZE','Masalli'),
	('AZ-NEF','NEF','AZE','Neftçala'),
	('AZ-OGU','OGU','AZE','Oğuz'),
	('AZ-ORD','ORD','AZE','Ordubad'),
	('AZ-QAB','QAB','AZE','Qäbälä'),
	('AZ-QAX','QAX','AZE','Qax'),
	('AZ-QAZ','QAZ','AZE','Qazax'),
	('AZ-QOB','QOB','AZE','Qobustan'),
	('AZ-QBA','QBA','AZE','Quba'),
	('AZ-QBI','QBI','AZE','Qubadlı'),
	('AZ-QUS','QUS','AZE','Qusar'),
	('AZ-SAT','SAT','AZE','Saatli'),
	('AZ-SAB','SAB','AZE','Sabirabad'),
	('AZ-SAD','SAD','AZE','Sädäräk'),
	('AZ-SAH','SAH','AZE','Şahbuz'),
	('AZ-SAK','SAK','AZE','Şäki'),
	('AZ-SAL','SAL','AZE','Salyan'),
	('AZ-SMI','SMI','AZE','Şamaxı'),
	('AZ-SKR','SKR','AZE','Şämkir'),
	('AZ-SMX','SMX','AZE','Samux'),
	('AZ-SAR','SAR','AZE','Şärur'),
	('AZ-SIY','SIY','AZE','Siyäzän'),
	('AZ-SUS','SUS','AZE','Şuşa'),
	('AZ-TAR','TAR','AZE','Tärtär'),
	('AZ-TOV','TOV','AZE','Tovuz'),
	('AZ-UCA','UCA','AZE','Ucar'),
	('AZ-XAC','XAC','AZE','Xaçmaz'),
	('AZ-XAN','XAN','AZE','Xanlar'),
	('AZ-XIZ','XIZ','AZE','Xizi'),
	('AZ-XCI','XCI','AZE','Xocalı'),
	('AZ-XVD','XVD','AZE','Xocavänd'),
	('AZ-YAR','YAR','AZE','Yardimli'),
	('AZ-YEV','YEV','AZE','Yevlax'),
	('AZ-ZAN','ZAN','AZE','Zängılan'),
	('AZ-ZAQ','ZAQ','AZE','Zaqatala'),
	('AZ-ZAR','ZAR','AZE','Zärdab'),
	('AZ-01','01','AZE','Abşeron'),
	('AZ-02','02','AZE','Ağcabədi'),
	('AZ-03','03','AZE','Ağdam'),
	('AZ-04','04','AZE','Ağdaş'),
	('AZ-05','05','AZE','Ağstafa'),
	('AZ-06','06','AZE','Ağsu'),
	('AZ-07','07','AZE','Şirvan'),
	('AZ-08','08','AZE','Astara'),
	('AZ-09','09','AZE','Baki'),
	('AZ-10','10','AZE','Balakən'),
	('AZ-11','11','AZE','Bərdə'),
	('AZ-12','12','AZE','Beyləqan'),
	('AZ-13','13','AZE','Biləsuvar'),
	('AZ-15','15','AZE','Cəlilabad'),
	('AZ-16','16','AZE','Daşkəsən'),
	('AZ-17','17','AZE','Şabran'),
	('AZ-18','18','AZE','Füzuli'),
	('AZ-19','19','AZE','Gədəbəy'),
	('AZ-20','20','AZE','Gəncə'),
	('AZ-21','21','AZE','Goranboy'),
	('AZ-22','22','AZE','Göyçay'),
	('AZ-23','23','AZE','Haciqabul'),
	('AZ-24','24','AZE','Imişli'),
	('AZ-25','25','AZE','Ismayilli'),
	('AZ-26','26','AZE','Kəlbəcər'),
	('AZ-27','27','AZE','Kürdəmir'),
	('AZ-28','28','AZE','Laçin'),
	('AZ-30','30','AZE','Lənkəran'),
	('AZ-31','31','AZE','Lerik'),
	('AZ-32','32','AZE','Masalli'),
	('AZ-33','33','AZE','Mingəçevir'),
	('AZ-34','34','AZE','Naftalan'),
	('AZ-36','36','AZE','Neftçala'),
	('AZ-37','37','AZE','Oğuz'),
	('AZ-38','38','AZE','Qəbələ'),
	('AZ-39','39','AZE','Qax'),
	('AZ-40','40','AZE','Qazax'),
	('AZ-41','41','AZE','Qobustan'),
	('AZ-42','42','AZE','Quba'),
	('AZ-43','43','AZE','Qubadli'),
	('AZ-44','44','AZE','Qusar'),
	('AZ-45','45','AZE','Saatli'),
	('AZ-46','46','AZE','Sabirabad'),
	('AZ-48','48','AZE','Şəki'),
	('AZ-49','49','AZE','Salyan'),
	('AZ-50','50','AZE','Şamaxi'),
	('AZ-51','51','AZE','Şəmkir'),
	('AZ-52','52','AZE','Samux'),
	('AZ-53','53','AZE','Siyəzən'),
	('AZ-54','54','AZE','Sumqayit'),
	('AZ-56','56','AZE','Şuşa'),
	('AZ-57','57','AZE','Tər-Tər'),
	('AZ-58','58','AZE','Tovuz'),
	('AZ-59','59','AZE','Ucar'),
	('AZ-60','60','AZE','Xaçmaz'),
	('AZ-61','61','AZE','Xankəndi'),
	('AZ-63','63','AZE','Xizi'),
	('AZ-64','64','AZE','Xocali'),
	('AZ-65','65','AZE','Xocavənd'),
	('AZ-66','66','AZE','Yardimli'),
	('AZ-68','68','AZE','Yevlax'),
	('AZ-69','69','AZE','Zəngilan'),
	('AZ-70','70','AZE','Zaqatala'),
	('AZ-71','71','AZE','Zərdab'),
	('BA-BIH','BIH','BIH','Federacija Bosna i Hercegovina'),
	('BA-SRP','SRP','BIH','Republika Srpska'),
	('BB-BB','BB','BRB','Barbados'),
	('BD-1','1','BGD','Barisal bibhag'),
	('BD-1B','1B','BGD','Barisal anchal'),
	('BD-1Q','1Q','BGD','Patuakhali anchal'),
	('BD-2','2','BGD','Chittagong bibhag'),
	('BD-2A','2A','BGD','Bandarban anchal'),
	('BD-2D','2D','BGD','Chittagong anchal'),
	('BD-2E','2E','BGD','Chittagong Hill Tracts'),
	('BD-2F','2F','BGD','Comilla anchal'),
	('BD-2O','2O','BGD','Noakhali anchal'),
	('BD-2T','2T','BGD','Sylhet anchal'),
	('BD-3','3','BGD','Dhaka bibhag'),
	('BD-3G','3G','BGD','Dhaka anchal'),
	('BD-3I','3I','BGD','Faridpur anchal'),
	('BD-3J','3J','BGD','Jamalpur anchal'),
	('BD-3N','3N','BGD','Mymensingh anchal'),
	('BD-3U','3U','BGD','Tangail anchal'),
	('BD-4','4','BGD','Khulna bibhag'),
	('BD-4K','4K','BGD','Jessore anchal'),
	('BD-4L','4L','BGD','Khulna anchal'),
	('BD-4M','4M','BGD','Khustia anchal'),
	('BD-5','5','BGD','Rajshahi bibhag'),
	('BD-5C','5C','BGD','Bogra anchal'),
	('BD-5H','5H','BGD','Dinajpur anchal'),
	('BD-5P','5P','BGD','Pabna anchal'),
	('BD-5R','5R','BGD','Rajshahi anchal'),
	('BD-5S','5S','BGD','Rangpur anchal'),
	('BD-81','81','BGD','Dhaka Division'),
	('BD-82','82','BGD','Khulna Division'),
	('BD-83','83','BGD','Rājshāhi Division'),
	('BD-84','84','BGD','Chittagong'),
	('BD-85','85','BGD','Barisal Division'),
	('BD-86','86','BGD','Sylhet Division'),
	('BD-87','87','BGD','Rangpur Division'),
	('BD-H','H','BGD','Dhaka Division'),
	('BE-BRU','BRU','BEL','Bruxelles-Capitale, Region de (fr), Brussels Hoofdstedelijk Gewest (nl)'),
	('BE-VLG','VLG','BEL','Vlaamse Gewest (nl)'),
	('BE-VAN','VAN','BEL','Antwerpen (nl)'),
	('BE-VLI','VLI','BEL','Limburg (nl)'),
	('BE-VOV','VOV','BEL','Oost-Vlaanderen (nl)'),
	('BE-VBR','VBR','BEL','Vlaams Brabant (nl)'),
	('BE-VWV','VWV','BEL','West-Vlaanderen (nl)'),
	('BE-WAL','WAL','BEL','Wallonne, Region (fr)'),
	('BE-WBR','WBR','BEL','Brabant Wallon (fr)'),
	('BE-WHT','WHT','BEL','Hainaut (fr)'),
	('BE-WLG','WLG','BEL','Liège (fr)'),
	('BE-WLX','WLX','BEL','Luxembourg (fr)'),
	('BE-WNA','WNA','BEL','Namur (fr)'),
	('BF-BAL','BAL','BFA','Balé'),
	('BF-BAM','BAM','BFA','Bam'),
	('BF-BAN','BAN','BFA','Banwa'),
	('BF-BAZ','BAZ','BFA','Bazèga'),
	('BF-BGR','BGR','BFA','Bougouriba'),
	('BF-BLG','BLG','BFA','Boulgou'),
	('BF-BLK','BLK','BFA','Boulkiemdé'),
	('BF-COM','COM','BFA','Comoé'),
	('BF-GAN','GAN','BFA','Ganzourgou'),
	('BF-GNA','GNA','BFA','Gnagna'),
	('BF-GOU','GOU','BFA','Gourma'),
	('BF-HOU','HOU','BFA','Houet'),
	('BF-IOB','IOB','BFA','Ioba'),
	('BF-KAD','KAD','BFA','Kadiogo'),
	('BF-KEN','KEN','BFA','Kénédougou'),
	('BF-KMD','KMD','BFA','Komondjari'),
	('BF-KMP','KMP','BFA','Kompienga'),
	('BF-KOS','KOS','BFA','Kossi'),
	('BF-KOP','KOP','BFA','Koulpélogo'),
	('BF-KOT','KOT','BFA','Kouritenga'),
	('BF-KOW','KOW','BFA','Kourwéogo'),
	('BF-LER','LER','BFA','Léraba'),
	('BF-LOR','LOR','BFA','Loroum'),
	('BF-MOU','MOU','BFA','Mouhoun'),
	('BF-NAO','NAO','BFA','Nahouri'),
	('BF-NAM','NAM','BFA','Namentenga'),
	('BF-NAY','NAY','BFA','Nayala'),
	('BF-NOU','NOU','BFA','Noumbiel'),
	('BF-OUB','OUB','BFA','Oubritenga'),
	('BF-OUD','OUD','BFA','Oudalan'),
	('BF-PAS','PAS','BFA','Passoré'),
	('BF-PON','PON','BFA','Poni'),
	('BF-SNG','SNG','BFA','Sanguié'),
	('BF-SMT','SMT','BFA','Sanmatenga'),
	('BF-SEN','SEN','BFA','Séno'),
	('BF-SIS','SIS','BFA','Sissili'),
	('BF-SOM','SOM','BFA','Soum'),
	('BF-SOR','SOR','BFA','Sourou'),
	('BF-TAP','TAP','BFA','Tapoa'),
	('BF-TUI','TUI','BFA','Tui'),
	('BF-YAG','YAG','BFA','Yagha'),
	('BF-YAT','YAT','BFA','Yatenga'),
	('BF-ZIR','ZIR','BFA','Ziro'),
	('BF-ZON','ZON','BFA','Zondoma'),
	('BF-ZOU','ZOU','BFA','Zoundwéogo'),
	('BG-02','02','BGR','Burgas'),
	('BG-09','09','BGR','Haskovo'),
	('BG-04','04','BGR','Loveč'),
	('BG-05','05','BGR','Montana'),
	('BG-06','06','BGR','Plovdiv'),
	('BG-07','07','BGR','Ruse'),
	('BG-08','08','BGR','Sofija'),
	('BG-01','01','BGR','Sofija-Grad'),
	('BG-03','03','BGR','Varna'),
	('BG-BGS','BGS','BGR','Бургас / Burgas'),
	('BG-BLG','BLG','BGR','Благоевград / Blagoevgrad'),
	('BG-DOB','DOB','BGR','Добрич / Dobrich'),
	('BG-GAB','GAB','BGR','Габрово / Gabrovo'),
	('BG-HKV','HKV','BGR','Хасково / Khaskovo'),
	('BG-JAM','JAM','BGR','Ямбол / Jambol'),
	('BG-KNL','KNL','BGR','Кюстендил / Kjustendil'),
	('BG-KRZ','KRZ','BGR','Кърджали / Kurdzhali'),
	('BG-LOV','LOV','BGR','Ловеч / Lovech'),
	('BG-MON','MON','BGR','Монтана / Montana'),
	('BG-PAZ','PAZ','BGR','Пазарджик / Pazardzhik'),
	('BG-PDV','PDV','BGR','Пловдив / Plovdiv'),
	('BG-PER','PER','BGR','Перник / Pernik'),
	('BG-PVN','PVN','BGR','Плевен / Pleven'),
	('BG-RAZ','RAZ','BGR','Разград / Razgrad'),
	('BG-RSE','RSE','BGR','Русе / Ruse'),
	('BG-SFO','SFO','BGR','София / Sofija'),
	('BG-SHU','SHU','BGR','Шумен / Shumen'),
	('BG-SLS','SLS','BGR','Силистра / Silistra'),
	('BG-SLV','SLV','BGR','Сливен / Sliven'),
	('BG-SML','SML','BGR','Смолян / Smoljan'),
	('BG-SOF','SOF','BGR','София (столица) / Sofija (stolica)'),
	('BG-SZR','SZR','BGR','Стара Загора / Stara Zagora'),
	('BG-TGV','TGV','BGR','Търговище / Turgovishhe'),
	('BG-VAR','VAR','BGR','Варна / Varna'),
	('BG-VID','VID','BGR','Видин / Vidin'),
	('BG-VRC','VRC','BGR','Враца / Vraca'),
	('BG-VTR','VTR','BGR','Велико Търново / Veliko Turnovo'),
	('BH-01','01','BHR','Al Ḩadd'),
	('BH-03','03','BHR','Al Manāmah'),
	('BH-10','10','BHR','Al Minţaqah al Gharbīyah'),
	('BH-07','07','BHR','Al Minţaqah al Wusţa'),
	('BH-05','05','BHR','Al Minţaqah ash Shamālīyah'),
	('BH-02','02','BHR','Al Muḩarraq'),
	('BH-09','09','BHR','Ar Rifā‘'),
	('BH-04','04','BHR','Jidd Ḩafş'),
	('BH-12','12','BHR','Madīnat Ḩamad'),
	('BH-08','08','BHR','Madīnat ‘Īsá'),
	('BH-11','11','BHR','Minţaqat Juzur Ḩawār'),
	('BH-06','06','BHR','Sitrah'),
	('BI-BB','BB','BDI','Bubanza'),
	('BI-BJ','BJ','BDI','Bujumbura'),
	('BI-BR','BR','BDI','Bururi'),
	('BI-CA','CA','BDI','Cankuzo'),
	('BI-CI','CI','BDI','Cibitoke'),
	('BI-GI','GI','BDI','Gitega'),
	('BI-KR','KR','BDI','Karuzi'),
	('BI-KY','KY','BDI','Kayanza'),
	('BI-KI','KI','BDI','Kirundo'),
	('BI-MA','MA','BDI','Makamba'),
	('BI-MU','MU','BDI','Muramvya'),
	('BI-MY','MY','BDI','Muyinga'),
	('BI-NG','NG','BDI','Ngozi'),
	('BI-RT','RT','BDI','Rutana'),
	('BI-RY','RY','BDI','Ruyigi'),
	('BJ-AK','AK','BEN','Atakora'),
	('BJ-AQ','AQ','BEN','Atlantique'),
	('BJ-BO','BO','BEN','Borgou'),
	('BJ-MO','MO','BEN','Mono'),
	('BJ-OU','OU','BEN','Ouémé'),
	('BJ-ZO','ZO','BEN','Zou'),
	('BM-BM','BM','BMU','Bermuda'),
	('BM-01','01','BMU','Devonshire Parish'),
	('BM-02','02','BMU','Hamilton'),
	('BM-03','03','BMU','Hamilton'),
	('BM-04','04','BMU','Paget Parish'),
	('BM-05','05','BMU','Pembroke Parish'),
	('BM-06','06','BMU','Saint George'),
	('BM-07','07','BMU','Saint George’s Parish'),
	('BM-08','08','BMU','Sandys Parish'),
	('BM-09','09','BMU','Smith’s Parish'),
	('BM-10','10','BMU','Southampton Parish'),
	('BM-11','11','BMU','Warwick Parish'),
	('BN-BE','BE','BRN','Belait'),
	('BN-BM','BM','BRN','Brunei-Muara'),
	('BN-TE','TE','BRN','Temburong'),
	('BN-TU','TU','BRN','Tutong'),
	('BO-C','C','BOL','Cochabamba'),
	('BO-H','H','BOL','Chuquisaca'),
	('BO-B','B','BOL','El Beni'),
	('BO-L','L','BOL','La Paz'),
	('BO-O','O','BOL','Oruro'),
	('BO-N','N','BOL','Pando'),
	('BO-P','P','BOL','Potosi'),
	('BO-S','S','BOL','Santa Cruz'),
	('BO-T','T','BOL','Tarija'),
	('BR-DF','DF','BRA','Distrito Federal'),
	('BR-AC','AC','BRA','Acre'),
	('BR-AL','AL','BRA','Alagoas'),
	('BR-AP','AP','BRA','Amapá'),
	('BR-AM','AM','BRA','Amazonas'),
	('BR-BA','BA','BRA','Bahia'),
	('BR-CE','CE','BRA','Ceará'),
	('BR-ES','ES','BRA','Espírito Santo'),
	('BR-GO','GO','BRA','Goiás'),
	('BR-MA','MA','BRA','Maranhāo'),
	('BR-MT','MT','BRA','Mato Grosso'),
	('BR-MS','MS','BRA','Mato Grosso do Sul'),
	('BR-MG','MG','BRA','Minas Gerais'),
	('BR-PA','PA','BRA','Pará'),
	('BR-PB','PB','BRA','Paraíba'),
	('BR-PR','PR','BRA','Paraná'),
	('BR-PE','PE','BRA','Pernambuco'),
	('BR-PI','PI','BRA','Piauí'),
	('BR-RJ','RJ','BRA','Rio de Janeiro'),
	('BR-RN','RN','BRA','Rio Grande do Norte'),
	('BR-RS','RS','BRA','Rio Grande do Sul'),
	('BR-R0','R0','BRA','Rondônia'),
	('BR-RR','RR','BRA','Roraima'),
	('BR-SC','SC','BRA','Santa Catarina'),
	('BR-SP','SP','BRA','São Paulo'),
	('BR-SE','SE','BRA','Sergipe'),
	('BR-TO','TO','BRA','Tocantins'),
	('BR-01','01','BRA','Acre'),
	('BR-02','02','BRA','Alagoas '),
	('BR-03','03','BRA','Amapa'),
	('BR-04','04','BRA','Amazonas '),
	('BR-05','05','BRA','Bahia'),
	('BR-06','06','BRA','Ceara'),
	('BR-07','07','BRA','Distrito Federal'),
	('BR-08','08','BRA','Espirito Santo'),
	('BR-11','11','BRA','Mato Grosso do Sul'),
	('BR-13','13','BRA','Maranhao '),
	('BR-14','14','BRA','Mato Grosso '),
	('BR-15','15','BRA','Minas Gerais'),
	('BR-16','16','BRA','Para'),
	('BR-17','17','BRA','Paraiba'),
	('BR-18','18','BRA','Parana'),
	('BR-20','20','BRA','Piaui'),
	('BR-21','21','BRA','Rio de Janeiro '),
	('BR-22','22','BRA','Rio Grande do Norte '),
	('BR-23','23','BRA','Rio Grande do Sul'),
	('BR-24','24','BRA','Rondonia'),
	('BR-25','25','BRA','Roraima'),
	('BR-26','26','BRA','Santa Catarina '),
	('BR-27','27','BRA','Sao Paulo'),
	('BR-28','28','BRA','Sergipe'),
	('BR-29','29','BRA','Goias'),
	('BR-30','30','BRA','Pernambuco '),
	('BR-31','31','BRA','Tocantins'),
	('BS-AC','AC','BHS','Acklins and Crooked Islands'),
	('BS-BI','BI','BHS','Bimini'),
	('BS-CI','CI','BHS','Cat Island'),
	('BS-EX','EX','BHS','Exuma'),
	('BS-FP','FP','BHS','Freeport'),
	('BS-FC','FC','BHS','Fresh Creek'),
	('BS-GH','GH','BHS','Governor's Harbour'),
	('BS-GT','GT','BHS','Green Turtle Cay'),
	('BS-HI','HI','BHS','Harbour Island'),
	('BS-HR','HR','BHS','High Rock'),
	('BS-IN','IN','BHS','Inagua'),
	('BS-KB','KB','BHS','Kemps Bay'),
	('BS-LI','LI','BHS','Long Island'),
	('BS-MH','MH','BHS','Marsh Harbour'),
	('BS-MG','MG','BHS','Mayaguana'),
	('BS-NP','NP','BHS','New Providence'),
	('BS-NB','NB','BHS','Nicholls Town and Berry Islands'),
	('BS-RI','RI','BHS','Ragged Island'),
	('BS-RS','RS','BHS','Rock Sound'),
	('BS-SP','SP','BHS','Sandy Point'),
	('BS-SR','SR','BHS','San Salvador and Rum Cay'),
	('BT-33','33','BTN','Bumthang'),
	('BT-12','12','BTN','Chhukha'),
	('BT-22','22','BTN','Dagana'),
	('BT-GA','GA','BTN','Gasa'),
	('BT-13','13','BTN','Ha'),
	('BT-44','44','BTN','Lhuentse'),
	('BT-42','42','BTN','Monggar'),
	('BT-11','11','BTN','Paro'),
	('BT-43','43','BTN','Pemagatshel'),
	('BT-23','23','BTN','Punakha'),
	('BT-45','45','BTN','Samdrup Jongkha'),
	('BT-14','14','BTN','Samtse'),
	('BT-31','31','BTN','Sarpang'),
	('BT-15','15','BTN','Thimphu'),
	('BT-41','41','BTN','Trashigang'),
	('BT-TY','TY','BTN','Trashi Yangtse'),
	('BT-32','32','BTN','Trongsa'),
	('BT-21','21','BTN','Tsirang'),
	('BT-24','24','BTN','Wangdue Phodrang'),
	('BT-34','34','BTN','Zhemgang'),
	('BV-BV','BV','BVT','Bouvet Island'),
	('BW-CE','CE','BWA','Central [Serowe-Palapye]'),
	('BW-CH','CH','BWA','Chobe'),
	('BW-GH','GH','BWA','Ghanzi'),
	('BW-KG','KG','BWA','Kgalagadi'),
	('BW-KL','KL','BWA','Kgatleng'),
	('BW-KW','KW','BWA','Kweneng'),
	('BW-NG','NG','BWA','Ngamiland [North-West]'),
	('BW-NE','NE','BWA','North-East'),
	('BW-SE','SE','BWA','South-East'),
	('BW-SO','SO','BWA','Southern [Ngwaketse]'),
	('BY-BR','BR','BLR','Brestskaya voblasts''),
	('BY-HO','HO','BLR','Homyel'skaya voblasts’'),
	('BY-HR','HR','BLR','Hrodnenskaya voblasts''),
	('BY-MA','MA','BLR','Mahilyowskaya voblasts''),
	('BY-MI','MI','BLR','Minskaya voblasts''),
	('BY-VI','VI','BLR','Vitsyebskaya voblasts''),
	('BY-','','BLR','Vitebsk'),
	('BZ-BZ','BZ','BLZ','Belize'),
	('BZ-CY','CY','BLZ','Cayo'),
	('BZ-CZL','CZL','BLZ','Corozal'),
	('BZ-OW','OW','BLZ','Orange Walk'),
	('BZ-SC','SC','BLZ','Stann Creek'),
	('BZ-TOL','TOL','BLZ','Toledo'),
	('CA-AB','AB','CAN','Alberta'),
	('CA-BC','BC','CAN','British Columbia (Colombie-Britannique)'),
	('CA-MB','MB','CAN','Manitoba'),
	('CA-NB','NB','CAN','New Brunswick (Nouveau-Brunswick)'),
	('CA-NL','NL','CAN','Newfoundland and Labrador (Terre-Neuve)'),
	('CA-NS','NS','CAN','Nova Scotia (Nouvelle-Écosse)'),
	('CA-ON','ON','CAN','Ontario'),
	('CA-PE','PE','CAN','Prince Edward Island (Île-du-Prince-Édouard)'),
	('CA-QC','QC','CAN','Quebec (Québec)'),
	('CA-SK','SK','CAN','Saskatchewan'),
	('CA-NT','NT','CAN','Northwest Territories (Territoires du Nord-Ouest)'),
	('CA-NU','NU','CAN','Nunavut'),
	('CA-YT','YT','CAN','Yukon Territory (Teritoire du Yukon)'),
	('CC-CC','CC','CCK','Cocos (Keeling) Islands'),
	('CD-KN','KN','COD','Kinshasa'),
	('CD-BN','BN','COD','Bandundu'),
	('CD-BC','BC','COD','Bas-Congo'),
	('CD-EQ','EQ','COD','Équateur'),
	('CD-HC','HC','COD','Haut-Congo'),
	('CD-KW','KW','COD','Kasai-Occidental'),
	('CD-KE','KE','COD','Kasai-Oriental'),
	('CD-KA','KA','COD','Katanga'),
	('CD-MA','MA','COD','Maniema'),
	('CD-NK','NK','COD','Nord-Kivu'),
	('CD-SK','SK','COD','Sud-Kivu'),
	('CF-BGF','BGF','CAF','Bangui'),
	('CF-BB','BB','CAF','Bamingui-Bangoran'),
	('CF-BK','BK','CAF','Basse-Kotto'),
	('CF-HK','HK','CAF','Haute-Kotto'),
	('CF-HM','HM','CAF','Haut-Mbomou'),
	('CF-KG','KG','CAF','Kémo'),
	('CF-LB','LB','CAF','Lobaye'),
	('CF-HS','HS','CAF','Mambéré-Kadéï'),
	('CF-MB','MB','CAF','Mbomou'),
	('CF-KB','KB','CAF','Nana-Grébizi'),
	('CF-NM','NM','CAF','Nana-Mambéré'),
	('CF-MP','MP','CAF','Ombella-Mpoko'),
	('CF-UK','UK','CAF','Ouaka'),
	('CF-AC','AC','CAF','Ouham'),
	('CF-OP','OP','CAF','Ouham-Pendé'),
	('CF-SE','SE','CAF','Sangha-Mbaéré'),
	('CF-VK','VK','CAF','Vakaga'),
	('CG-BZV','BZV','COG','Brazzaville'),
	('CG-11','11','COG','Bouenza'),
	('CG-8','8','COG','Cuvette'),
	('CG-15','15','COG','Cuvette-Ouest'),
	('CG-5','5','COG','Kouilou'),
	('CG-2','2','COG','Lékoumou'),
	('CG-7','7','COG','Likouala'),
	('CG-9','9','COG','Niari'),
	('CG-14','14','COG','Plateaux'),
	('CG-12','12','COG','Pool'),
	('CG-13','13','COG','Sangha'),
	('CH-AG','AG','CHE','Aargau'),
	('CH-AR','AR','CHE','Appenzell Ausser-Rhoden'),
	('CH-AI','AI','CHE','Appenzell Inner-Rhoden'),
	('CH-BL','BL','CHE','Basel-Landschaft'),
	('CH-BS','BS','CHE','Basel-Stadt'),
	('CH-BE','BE','CHE','Bern'),
	('CH-FR','FR','CHE','Freiburg'),
	('CH-GE','GE','CHE','Geneve'),
	('CH-GL','GL','CHE','Glarus'),
	('CH-GR','GR','CHE','Graubünden'),
	('CH-JU','JU','CHE','Jura'),
	('CH-LU','LU','CHE','Luzern'),
	('CH-NE','NE','CHE','Neuchatel'),
	('CH-NW','NW','CHE','Nidwalden'),
	('CH-OW','OW','CHE','Obwalden'),
	('CH-SG','SG','CHE','Sankt Gallen'),
	('CH-SH','SH','CHE','Schaffhausen'),
	('CH-SZ','SZ','CHE','Schwyz'),
	('CH-SO','SO','CHE','Solothurn'),
	('CH-TG','TG','CHE','Thurgau'),
	('CH-TI','TI','CHE','Ticino'),
	('CH-UR','UR','CHE','Uri'),
	('CH-VS','VS','CHE','Wallis'),
	('CH-VD','VD','CHE','Vaud'),
	('CH-ZG','ZG','CHE','Zug'),
	('CH-ZH','ZH','CHE','Zürich'),
	('CI-06','06','CIV','18 Montagnes (Région des)'),
	('CI-16','16','CIV','Agnébi (Région de l')'),
	('CI-09','09','CIV','Bas-Sassandra (Région du)'),
	('CI-10','10','CIV','Denguélé (Région du)'),
	('CI-02','02','CIV','Haut-Sassandra (Région du)'),
	('CI-07','07','CIV','Lacs (Région des)'),
	('CI-01','01','CIV','Lagunes (Région des)'),
	('CI-12','12','CIV','Marahoué (Région de la)'),
	('CI-05','05','CIV','Moyen-Comoé (Région du)'),
	('CI-11','11','CIV','Nzi-Comoé (Région)'),
	('CI-03','03','CIV','Savanes (Région des)'),
	('CI-15','15','CIV','Sud-Bandama (Région du)'),
	('CI-13','13','CIV','Sud-Comoé (Région du)'),
	('CI-04','04','CIV','Vallée du Bandama (Région de la)'),
	('CI-14','14','CIV','Worodougou (Région du)'),
	('CI-08','08','CIV','Zanzan (Région du)'),
	('CK-CK','CK','COK','Cook Islands'),
	('CL-AI','AI','CHL','Aisén del General Carlos Ibáñiez del Campo'),
	('CL-AN','AN','CHL','Antofagasta'),
	('CL-AR','AR','CHL','Araucanía'),
	('CL-AT','AT','CHL','Atacama'),
	('CL-BI','BI','CHL','Bío-Bío'),
	('CL-CO','CO','CHL','Coquimbo'),
	('CL-LI','LI','CHL','Libertador General Bernardo O'Higgins'),
	('CL-LL','LL','CHL','Los Lagos'),
	('CL-MA','MA','CHL','Magallanes'),
	('CL-ML','ML','CHL','Maule'),
	('CL-RM','RM','CHL','Regíon Metropolitana de Santiago'),
	('CL-TA','TA','CHL','Tarapacá'),
	('CL-VS','VS','CHL','Valparaiso'),
	('CL-01','01','CHL','Región de Valparaíso'),
	('CL-02','02','CHL','Región Aysén'),
	('CL-03','03','CHL','Región de Antofagasta'),
	('CL-04','04','CHL','Región de la Araucanía'),
	('CL-05','05','CHL','Región de Atacama'),
	('CL-06','06','CHL','Región del Biobío'),
	('CL-07','07','CHL','Región de Coquimbo'),
	('CL-08','08','CHL','Región del Libertador General Bernardo O’Higgins'),
	('CL-10','10','CHL','Región de Magallanes y Antártica Chilena'),
	('CL-11','11','CHL','Región del Maule'),
	('CL-12','12','CHL','Región Metropolitana'),
	('CL-14','14','CHL','Región de los Lagos'),
	('CL-15','15','CHL','Región de Tarapacá'),
	('CL-16','16','CHL','Región de Arica y Parinacota'),
	('CL-17','17','CHL','Región de los Ríos'),
	('CM-AD','AD','CMR','Adamaoua'),
	('CM-CE','CE','CMR','Centre'),
	('CM-ES','ES','CMR','Est'),
	('CM-EN','EN','CMR','Far North'),
	('CM-LT','LT','CMR','Littoral'),
	('CM-NO','NO','CMR','North'),
	('CM-NW','NW','CMR','North-West'),
	('CM-SU','SU','CMR','South'),
	('CM-SW','SW','CMR','South-West'),
	('CM-OU','OU','CMR','West'),
	('CN-11','11','CHN','Beijing'),
	('CN-50','50','CHN','Chongqing'),
	('CN-31','31','CHN','Shanghai'),
	('CN-12','12','CHN','Tianjin'),
	('CN-34','34','CHN','Anhui'),
	('CN-35','35','CHN','Fujian'),
	('CN-62','62','CHN','Gansu'),
	('CN-44','44','CHN','Guangdong'),
	('CN-52','52','CHN','Guizhou'),
	('CN-46','46','CHN','Hainan'),
	('CN-13','13','CHN','Hebei'),
	('CN-23','23','CHN','Heilongjiang'),
	('CN-41','41','CHN','Henan'),
	('CN-42','42','CHN','Hubei'),
	('CN-43','43','CHN','Hunan'),
	('CN-32','32','CHN','Jiangsu'),
	('CN-36','36','CHN','Jiangxi'),
	('CN-22','22','CHN','Jilin'),
	('CN-21','21','CHN','Liaoning'),
	('CN-63','63','CHN','Qinghai'),
	('CN-61','61','CHN','Shaanxi'),
	('CN-37','37','CHN','Shandong'),
	('CN-14','14','CHN','Shanxi'),
	('CN-51','51','CHN','Sichuan'),
	('CN-71','71','CHN','Taiwan'),
	('CN-53','53','CHN','Yunnan'),
	('CN-33','33','CHN','Zhejiang'),
	('CN-45','45','CHN','Guangxi'),
	('CN-15','15','CHN','Nei Monggol'),
	('CN-64','64','CHN','Ningxia'),
	('CN-65','65','CHN','Xinjiang'),
	('CN-54','54','CHN','Xizang'),
	('CN-91','91','CHN','Hong Kong'),
	('CO-DC','DC','COL','Distrito Capital de Santa Fe de Bogota'),
	('CO-AMA','AMA','COL','Amazonas'),
	('CO-ANT','ANT','COL','Antioguia'),
	('CO-ARA','ARA','COL','Arauca'),
	('CO-ATL','ATL','COL','Atlántico'),
	('CO-BOL','BOL','COL','Bolívar'),
	('CO-BOY','BOY','COL','Boyacá'),
	('CO-CAL','CAL','COL','Caldas'),
	('CO-CAQ','CAQ','COL','Caquetá'),
	('CO-CAS','CAS','COL','Casanare'),
	('CO-CAU','CAU','COL','Cauca'),
	('CO-CES','CES','COL','Cesar'),
	('CO-COR','COR','COL','Córdoba'),
	('CO-CUN','CUN','COL','Cundinamarca'),
	('CO-CHO','CHO','COL','Chocó'),
	('CO-GUA','GUA','COL','Guainía'),
	('CO-GUV','GUV','COL','Guaviare'),
	('CO-HUI','HUI','COL','Huila'),
	('CO-LAG','LAG','COL','La Guajira'),
	('CO-MAG','MAG','COL','Magdalena'),
	('CO-MET','MET','COL','Meta'),
	('CO-NAR','NAR','COL','Nariño'),
	('CO-NSA','NSA','COL','Norte de Santander'),
	('CO-PUT','PUT','COL','Putumayo'),
	('CO-QUI','QUI','COL','Quindío'),
	('CO-RIS','RIS','COL','Risaralda'),
	('CO-SAP','SAP','COL','San Andrés, Providencia y Santa Catalina'),
	('CO-SAN','SAN','COL','Santander'),
	('CO-SUC','SUC','COL','Sucre'),
	('CO-TOL','TOL','COL','Tolima'),
	('CO-VAC','VAC','COL','Valle del Cauca'),
	('CO-VAU','VAU','COL','Vaupés'),
	('CO-VID','VID','COL','Vichada'),
	('CO-01','01','COL','Amazonas'),
	('CO-02','02','COL','Antioquia'),
	('CO-03','03','COL','Arauca'),
	('CO-04','04','COL','Atlantico'),
	('CO-08','08','COL','Caqueta'),
	('CO-09','09','COL','Cauca'),
	('CO-10','10','COL','Cesar'),
	('CO-11','11','COL','Choco'),
	('CO-12','12','COL','Cordoba'),
	('CO-14','14','COL','Guaviare'),
	('CO-15','15','COL','Guainia'),
	('CO-16','16','COL','Huila'),
	('CO-17','17','COL','La Guajira'),
	('CO-19','19','COL','Meta'),
	('CO-20','20','COL','Nariño'),
	('CO-21','21','COL','Norte De Santander'),
	('CO-22','22','COL','Putumayo'),
	('CO-23','23','COL','Quindio'),
	('CO-24','24','COL','Risaralda'),
	('CO-25','25','COL','Archipielago De San Andres'),
	('CO-26','26','COL','Santander'),
	('CO-27','27','COL','Sucre'),
	('CO-28','28','COL','Tolima'),
	('CO-29','29','COL','Valle Del Cauca'),
	('CO-30','30','COL','Vaupes'),
	('CO-31','31','COL','Vichada'),
	('CO-32','32','COL','Casanare'),
	('CO-33','33','COL','Cundinamarca'),
	('CO-34','34','COL','Bogota, D.C.'),
	('CO-35','35','COL','Bolivar'),
	('CO-36','36','COL','Boyaca'),
	('CO-37','37','COL','Caldas'),
	('CO-38','38','COL','Magdalena'),
	('CR-A','A','CRI','Alajuela'),
	('CR-C','C','CRI','Cartago'),
	('CR-G','G','CRI','Guanacaste'),
	('CR-H','H','CRI','Heredia'),
	('CR-L','L','CRI','Limón'),
	('CR-P','P','CRI','Puntarenas'),
	('CR-SJ','SJ','CRI','San José'),
	('CR-01','01','CRI','Provincia de Alajuela'),
	('CR-02','02','CRI','Provincia de Cartago'),
	('CR-03','03','CRI','Provincia de Guanacaste'),
	('CR-04','04','CRI','Provincia de Heredia'),
	('CR-06','06','CRI','Provincia de Limón'),
	('CR-07','07','CRI','Provincia de Puntarenas'),
	('CR-08','08','CRI','Provincia de San José'),
	('CU-09','09','CUB','Camagüey'),
	('CU-03','03','CUB','Ciudad de La Habana'),
	('CU-12','12','CUB','Granma'),
	('CU-14','14','CUB','Guantánamo'),
	('CU-11','11','CUB','Holguín'),
	('CU-02','02','CUB','La Habana'),
	('CU-10','10','CUB','Las Tunas'),
	('CU-04','04','CUB','Matanzas'),
	('CU-01','01','CUB','Pinar del Río'),
	('CU-07','07','CUB','Sancti Spíritus'),
	('CU-13','13','CUB','Santiago de Cuba'),
	('CU-05','05','CUB','Villa Clara'),
	('CU-99','99','CUB','Isla de la Juventud'),
	('CV-B','B','CPV','Ilhas de Barlavento'),
	('CV-BV','BV','CPV','Boa Vista'),
	('CV-PA','PA','CPV','Paul'),
	('CV-PN','PN','CPV','Porto Novo'),
	('CV-RG','RG','CPV','Ribeira Grande'),
	('CV-SL','SL','CPV','Sal'),
	('CV-SN','SN','CPV','Sāo Nicolau'),
	('CV-SV','SV','CPV','Sāo Vicente'),
	('CV-S','S','CPV','Ilhas de Sotavento'),
	('CV-BR','BR','CPV','Brava'),
	('CV-FO','FO','CPV','Fogo'),
	('CV-MA','MA','CPV','Maio'),
	('CV-PR','PR','CPV','Praia'),
	('CV-CA','CA','CPV','Santa Catarina'),
	('CV-CR','CR','CPV','Santa Cruz'),
	('CV-TA','TA','CPV','Tarrafal'),
	('CX-CX','CX','CXR','Christmas Island'),
	('CY-04','04','CYP','Ammochostos (Mağusa)'),
	('CY-06','06','CYP','Keryneia (Girne)'),
	('CY-03','03','CYP','Larnaka'),
	('CY-01','01','CYP','Lefkosia (Lefkoşa)'),
	('CY-02','02','CYP','Lemesos (Leymosun)'),
	('CY-05','05','CYP','Pafos (Baf)'),
	('CZ-PRG','PRG','CZE','Praha'),
	('CZ-CJC','CJC','CZE','Jihočeský kraj'),
	('CZ-CJM','CJM','CZE','Jihomoravský kraj'),
	('CZ-CSC','CSC','CZE','Severočeský kraj'),
	('CZ-CSM','CSM','CZE','Severomoravský kraj'),
	('CZ-CST','CST','CZE','Středočeský kraj'),
	('CZ-CVC','CVC','CZE','Východočeský kraj'),
	('CZ-CZC','CZC','CZE','Západočeský kraj'),
	('CZ-','','CZE',''),
	('KM-A','A','COM','Anjouan (Ndzouani)'),
	('KM-G','G','COM','Grande Comore (Ngazidja)'),
	('KM-M','M','COM','Mohéli (Moili)'),
	('KY-KY','KY','CYM','Cayman Islands'),
	('TF-TF','TF','ATF','French Southern Territories'),
	('AN-AN','AN','ANT','Netherlands Antilles');
COMMIT;
ANALYZE;
