BEGIN;
INSERT INTO regions (iso3, iso2, country, name) VALUES
	('JE-','','JEY',''),
	('JM-13','13','JAM','Clarendon'),
	('JM-09','09','JAM','Hanover'),
	('JM-01','01','JAM','Kingston'),
	('JM-12','12','JAM','Manchester'),
	('JM-04','04','JAM','Portland'),
	('JM-02','02','JAM','Saint Andrew'),
	('JM-06','06','JAM','Saint Ann'),
	('JM-14','14','JAM','Saint Catherine'),
	('JM-11','11','JAM','Saint Elizabeth'),
	('JM-08','08','JAM','Saint James'),
	('JM-05','05','JAM','Saint Mary'),
	('JM-03','03','JAM','Saint Thomas'),
	('JM-07','07','JAM','Trelawny'),
	('JM-10','10','JAM','Westmoreland'),
	('JO-AJ','AJ','JOR','‘Ajlūn'),
	('JO-AQ','AQ','JOR','Al 'Aqaba'),
	('JO-BA','BA','JOR','Al Balqā''),
	('JO-KA','KA','JOR','Al Karak'),
	('JO-MA','MA','JOR','Al Mafraq'),
	('JO-AM','AM','JOR','‘Ammān'),
	('JO-AT','AT','JOR','Aţ Ţafīlah'),
	('JO-AZ','AZ','JOR','Az Zarqā''),
	('JO-IR','IR','JOR','Irbid'),
	('JO-JA','JA','JOR','Jarash'),
	('JO-MN','MN','JOR','Ma‘ān'),
	('JO-MD','MD','JOR','Mādaba'),
	('JP-23','23','JPN','Aiti [Aichi]'),
	('JP-05','05','JPN','Akita'),
	('JP-02','02','JPN','Aomori'),
	('JP-38','38','JPN','Ehime'),
	('JP-21','21','JPN','Gihu [Gifu]'),
	('JP-10','10','JPN','Gunma'),
	('JP-34','34','JPN','Hirosima [Hiroshima]'),
	('JP-01','01','JPN','Hokkaidô [Hokkaido]'),
	('JP-18','18','JPN','Hukui [Fukui]'),
	('JP-40','40','JPN','Hukuoka [Fukuoka]'),
	('JP-07','07','JPN','Hukusima [Fukushima]'),
	('JP-28','28','JPN','Hyôgo [Hyogo]'),
	('JP-08','08','JPN','Ibaraki'),
	('JP-17','17','JPN','Isikawa [Ishikawa]'),
	('JP-03','03','JPN','Iwate'),
	('JP-37','37','JPN','Kagawa'),
	('JP-46','46','JPN','Kagosima [Kagoshima]'),
	('JP-14','14','JPN','Kanagawa'),
	('JP-39','39','JPN','Kôti [Kochi]'),
	('JP-43','43','JPN','Kumamoto'),
	('JP-26','26','JPN','Kyôto [Kyoto]'),
	('JP-24','24','JPN','Mie'),
	('JP-04','04','JPN','Miyagi'),
	('JP-45','45','JPN','Miyazaki'),
	('JP-20','20','JPN','Nagano'),
	('JP-42','42','JPN','Nagasaki'),
	('JP-29','29','JPN','Nara'),
	('JP-15','15','JPN','Niigata'),
	('JP-44','44','JPN','Ôita [Oita]'),
	('JP-33','33','JPN','Okayama'),
	('JP-47','47','JPN','Okinawa'),
	('JP-27','27','JPN','Ôsaka [Osaka]'),
	('JP-41','41','JPN','Saga'),
	('JP-11','11','JPN','Saitama'),
	('JP-25','25','JPN','Siga [Shiga]'),
	('JP-22','22','JPN','Sizuoka [Shizuoka]'),
	('JP-12','12','JPN','Tiba [Chiba]'),
	('JP-09','09','JPN','Totigi [Tochigi]'),
	('JP-36','36','JPN','Tokusima [Tokushima]'),
	('JP-13','13','JPN','Tôkyô [Tokyo]'),
	('JP-31','31','JPN','Tottori'),
	('JP-16','16','JPN','Toyama'),
	('JP-30','30','JPN','Wakayama'),
	('JP-06','06','JPN','Yamagata'),
	('JP-35','35','JPN','Yamaguti [Yamaguchi]'),
	('JP-19','19','JPN','Yamanasi [Yamanashi]'),
	('JP-32','32','JPN','Osaka Fu'),
	('KE-110','110','KEN','Nairobi Municipality'),
	('KE-200','200','KEN','Central (Kati)'),
	('KE-300','300','KEN','Coast (Pwani)'),
	('KE-400','400','KEN','Eastern (Mashariki)'),
	('KE-500','500','KEN','North-Eastern (Kaskazini Mashariki)'),
	('KE-600','600','KEN','Nyanza'),
	('KE-700','700','KEN','Rift Valley'),
	('KE-900','900','KEN','Western (Magharibi)'),
	('KG-C','C','KGZ','Chu (Chuyskaya oblast')'),
	('KG-J','J','KGZ','Jalal-Abad (Dzhalal-Abadskaya oblast')'),
	('KG-N','N','KGZ','Naryn (Narynskaya Oblast’)'),
	('KG-O','O','KGZ','Osh (Oshskaya oblast')'),
	('KG-T','T','KGZ','Talas (Talasskaya oblast')'),
	('KG-Y','Y','KGZ','Ysyk-Köl (Issyk-Kul'skaya oblast')'),
	('KH-23','23','KHM','Krong Kaeb [Krŏng Kêb]'),
	('KH-18','18','KHM','Krong Preah Sihanouk [Krŏng Preăh Sihanouk]'),
	('KH-12','12','KHM','Phnom Penh [Phnum Pénh]'),
	('KH-2','2','KHM','Baat Dambang [Bătdâmbâng]'),
	('KH-1','1','KHM','Banteay Mean Chey [Bântéay Méanchey]'),
	('KH-3','3','KHM','Kampong Chaam [Kâmpóng Cham]'),
	('KH-4','4','KHM','Kampong Chhnang [Kâmpóng Chhnăng]'),
	('KH-5','5','KHM','Kampong Spueu [Kâmpóng Spœ]'),
	('KH-6','6','KHM','Kampong Thum [Kâmpóng Thum]'),
	('KH-7','7','KHM','Kampot [Kâmpôt]'),
	('KH-8','8','KHM','Kandaal [Kândal]'),
	('KH-10','10','KHM','Kracheh [Krâchéh]'),
	('KH-11','11','KHM','Mond01 Kiri [Môndól Kiri]'),
	('KH-22','22','KHM','Otdar Mean Chey [Ŏtdâr Méanchey]'),
	('KH-15','15','KHM','Pousaat [Poŭthĭsăt]'),
	('KH-13','13','KHM','Preah Vihear [Preăh Vihéar]'),
	('KH-14','14','KHM','Prey Veaeng [Prey Vêng]'),
	('KH-16','16','KHM','Rotanak Kiri [Rôtânôkiri]'),
	('KH-17','17','KHM','Siem Reab [Siĕmréab]'),
	('KH-19','19','KHM','Stueng Traeng [Stœng Trêng]'),
	('KH-20','20','KHM','Svaay Rieng [Svay Riĕng]'),
	('KH-21','21','KHM','Taakaev [Takêv]'),
	('KI-G','G','KIR','Gilbert Islands'),
	('KI-L','L','KIR','Line Islands'),
	('KI-P','P','KIR','Phoenix Islands'),
	('KN-KN','KN','KNA','Saint Kitts & Nevis'),
	('KR-11','11','KOR','Seoul Teugbyeolsi [ Seoul-T’ŭkpyŏlshi]'),
	('KR-26','26','KOR','Busan Gwang'yeogsi [Pusan-Kwangyŏkshi]'),
	('KR-27','27','KOR','Daegu Gwang'yeogsi [Taegu-Kwangyŏkshi)'),
	('KR-30','30','KOR','Daejeon Gwang'yeogsi [Taejŏn-Kwangyŏkshi]'),
	('KR-29','29','KOR','Gwangju Gwang'yeogsi [Kwangju-Kwangyŏkshi]'),
	('KR-28','28','KOR','Incheon Gwang'yeogsi [Inchŏn-Kwangyŏkshi]'),
	('KR-31','31','KOR','Ulsan Gwang'yeogsi [Ulsan-Kwangyŏkshi]'),
	('KR-43','43','KOR','Chungcheongbugdo [Ch'ungch'ŏngbuk-do]'),
	('KR-44','44','KOR','Chungcheongnamdo [Ch'ungch'ŏngnam-do]'),
	('KR-42','42','KOR','Gang'weondo [Kang-won-do]'),
	('KR-41','41','KOR','Gyeonggido [Kyŏnggi-do]'),
	('KR-47','47','KOR','Gyeongsangbugdo [Kyŏngsangbuk-do]'),
	('KR-48','48','KOR','Gyeongsangnamdo [Kyŏngsangnam-do]'),
	('KR-49','49','KOR','Jejudo [Cheju-do]'),
	('KR-45','45','KOR','Jeonrabugdo [Chŏllabuk-do)'),
	('KR-46','46','KOR','Jeonranamdo [Chŏllanam-do]'),
	('KR-01','01','KOR','제주특별자치도'),
	('KR-03','03','KOR','전라북도'),
	('KR-05','05','KOR','충청북도'),
	('KR-06','06','KOR','강원도'),
	('KR-10','10','KOR','부산광역시'),
	('KR-12','12','KOR','인천광역시'),
	('KR-13','13','KOR','경기도'),
	('KR-14','14','KOR','경상북도'),
	('KR-15','15','KOR','대구광역시'),
	('KR-16','16','KOR','전라남도'),
	('KR-17','17','KOR','충청남도'),
	('KR-18','18','KOR','광주광역시'),
	('KR-19','19','KOR','대전광역시'),
	('KR-20','20','KOR','경상남도'),
	('KR-21','21','KOR','울산광역시'),
	('KR-22','22','KOR','세종특별자치시'),
	('KW-AH','AH','KWT','Al Aḩmadi'),
	('KW-FA','FA','KWT','Al Farwānīyah'),
	('KW-JA','JA','KWT','Al Jahrah'),
	('KW-KU','KU','KWT','Al Kuwayt'),
	('KW-HA','HA','KWT','Ḩawallī'),
	('KZ-ALA','ALA','KAZ','Almaty'),
	('KZ-BAY','BAY','KAZ','Bayqonyr (Baykonyr)'),
	('KZ-ALM','ALM','KAZ','Almaty oblysy (Almatinskaya oblast')'),
	('KZ-AKM','AKM','KAZ','Aqmola oblysy (Akmolinskaya oblast')'),
	('KZ-AKT','AKT','KAZ','Aqtöbe oblysy (Aktyubinskaya oblast')'),
	('KZ-ATY','ATY','KAZ','Atyraü oblysy (Atyrauskaya oblast')'),
	('KZ-ZAP','ZAP','KAZ','Batys Kazakstan oblysy (Zapadno-Kazakhstanskaya oblast')'),
	('KZ-MAN','MAN','KAZ','Mangghystaū oblysy (Mangystauskaya oblast')'),
	('KZ-YUZ','YUZ','KAZ','Ongtüstik Kazakstan oblysy (Yuzhno-Kazakhstanskaya oblast')'),
	('KZ-PAV','PAV','KAZ','Pavlodar oblysy (Pavlodarskaya oblast')'),
	('KZ-KAR','KAR','KAZ','Qaraghandy oblysy (Karagandinskaya oblast')'),
	('KZ-KUS','KUS','KAZ','Qostanay oblysy (Kustanayskaya oblast')'),
	('KZ-KZY','KZY','KAZ','Qyzylorda oblysy (Kzylordinskaya oblast')'),
	('KZ-VOS','VOS','KAZ','Shyghys Kazakstan oblysy (Vostochno-Kazakhstanskaya oblast')'),
	('KZ-SEV','SEV','KAZ','Soltüstik Kazakstan oblysy (Severo-Kazakhstanskaya oblast')'),
	('KZ-ZHA','ZHA','KAZ','Zhambyl oblysy (Zhambylskaya Oblast')'),
	('LA-VT','VT','LAO','Vientiane'),
	('LA-AT','AT','LAO','Attapu [Attopeu]'),
	('LA-BK','BK','LAO','Bokèo'),
	('LA-BL','BL','LAO','Bolikhamxai [Borikhane]'),
	('LA-CH','CH','LAO','Champasak [Champassak]'),
	('LA-HO','HO','LAO','Houaphan'),
	('LA-KH','KH','LAO','Khammouan'),
	('LA-LM','LM','LAO','Louang Namtha'),
	('LA-LP','LP','LAO','Louangphabang [Louang Prabang]'),
	('LA-OU','OU','LAO','Oudômxai [Oudomsai]'),
	('LA-PH','PH','LAO','Phôngsali [Phong Saly]'),
	('LA-SL','SL','LAO','Salavan [Saravane]'),
	('LA-SV','SV','LAO','Savannakhét'),
	('LA-VI','VI','LAO','Vientiane'),
	('LA-XA','XA','LAO','Xaignabouli [Sayaboury]'),
	('LA-XE','XE','LAO','Xékong [Sékong]'),
	('LA-XI','XI','LAO','Xiangkhoang [Xieng Khouang]'),
	('LB-BA','BA','LBN','Beiroût (Bayrūt)'),
	('LB-BI','BI','LBN','El Béqaa (Al Biqā')'),
	('LB-JL','JL','LBN','Jabal Loubnâne (Jabal Lubnān)'),
	('LB-AS','AS','LBN','Loubnâne ech Chemâli (Ash Shamāl)'),
	('LB-JA','JA','LBN','Loubnâne ej Jnoûbi (Al Janūb)'),
	('LB-NA','NA','LBN','Nabatîyé (An Nabaţīyah'),
	('LC-LC','LC','LCA','Saint Lucia'),
	('LI-LI','LI','LIE','Liechtenstein'),
	('LI-7001','7001','LIE','Vaduz'),
	('LI-7002','7002','LIE','Triesen'),
	('LI-7003','7003','LIE','Balzers'),
	('LI-7004','7004','LIE','Triesenberg'),
	('LI-7005','7005','LIE','Schaan'),
	('LI-7006','7006','LIE','Planken'),
	('LI-7007','7007','LIE','Eschen'),
	('LI-7008','7008','LIE','Mauren'),
	('LI-7009','7009','LIE','Gamprin'),
	('LI-7010','7010','LIE','Ruggell'),
	('LI-7011','7011','LIE','Schellenberg'),
	('LK-1','1','LKA','Basnahira Palata (Western Province)'),
	('LK-11','11','LKA','Colombo'),
	('LK-12','12','LKA','Gampaha'),
	('LK-13','13','LKA','Kalutara'),
	('LK-3','3','LKA','Dakunu Palata (Southern Province)'),
	('LK-31','31','LKA','Galle'),
	('LK-33','33','LKA','Hambantota'),
	('LK-32','32','LKA','Matara'),
	('LK-2','2','LKA','Madhyama Palata (Central Province)'),
	('LK-21','21','LKA','Kandy'),
	('LK-22','22','LKA','Matale'),
	('LK-23','23','LKA','Nuwara Eliya'),
	('LK-5','5','LKA','Negenahira Palata (Eastern Province)'),
	('LK-52','52','LKA','Arnpara'),
	('LK-51','51','LKA','Batticaloa'),
	('LK-53','53','LKA','Trincomalee'),
	('LK-9','9','LKA','Sabaragamuwa Palata'),
	('LK-92','92','LKA','Kegalla'),
	('LK-91','91','LKA','Ratnapura'),
	('LK-7','7','LKA','Uturumeda Palata (North Central Province)'),
	('LK-71','71','LKA','Anuradhapura'),
	('LK-72','72','LKA','Polonnaruwa'),
	('LK-4','4','LKA','Uturu Palata (Northern Province)'),
	('LK-41','41','LKA','Jaffna'),
	('LK-42','42','LKA','Kilinochchi'),
	('LK-43','43','LKA','Mannar'),
	('LK-45','45','LKA','Mullaittivu'),
	('LK-44','44','LKA','Vavuniya'),
	('LK-8','8','LKA','Uva Palata'),
	('LK-81','81','LKA','Badulla'),
	('LK-82','82','LKA','Monaragala'),
	('LK-6','6','LKA','Wayamba Palata (North Western Province)'),
	('LK-61','61','LKA','Kurunegala'),
	('LK-62','62','LKA','Puttalam'),
	('LK-','','LKA',''),
	('LR-BM','BM','LBR','Bomi'),
	('LR-BG','BG','LBR','Bong'),
	('LR-GB','GB','LBR','Grand Bassa'),
	('LR-CM','CM','LBR','Grand Cape Mount'),
	('LR-GG','GG','LBR','Grand Gedeh'),
	('LR-GK','GK','LBR','Grand Kru'),
	('LR-LO','LO','LBR','Lofa'),
	('LR-MG','MG','LBR','Margibi'),
	('LR-MY','MY','LBR','Maryland'),
	('LR-MO','MO','LBR','Montserrado'),
	('LR-NI','NI','LBR','Nimba'),
	('LR-RI','RI','LBR','Rivercess'),
	('LR-SI','SI','LBR','Sinoe'),
	('LS-D','D','LSO','Berea'),
	('LS-B','B','LSO','Butha-Buthe'),
	('LS-C','C','LSO','Leribe'),
	('LS-E','E','LSO','Mafeteng'),
	('LS-A','A','LSO','Maseru'),
	('LS-F','F','LSO','Mohale's Hoek'),
	('LS-J','J','LSO','Mokhotlong'),
	('LS-H','H','LSO','Qacha's Nek'),
	('LS-G','G','LSO','Quthing'),
	('LS-K','K','LSO','Thaba-Tseka'),
	('LT-AL','AL','LTU','Alytaus Apskritis'),
	('LT-KU','KU','LTU','Kauno Apskritis'),
	('LT-KL','KL','LTU','Klaipėdos Apskritis'),
	('LT-MR','MR','LTU','Marijampolės Apskritis'),
	('LT-PN','PN','LTU','Panevėžio Apskritis'),
	('LT-SA','SA','LTU','Šiauliu Apskritis'),
	('LT-TA','TA','LTU','Tauragės Apskritis'),
	('LT-TE','TE','LTU','Telšiu Apskritis'),
	('LT-UT','UT','LTU','Utenos Apskritis'),
	('LT-VL','VL','LTU','Vilniaus Apskritis'),
	('LT-','','LTU',''),
	('LU-D','D','LUX','Diekirch'),
	('LU-G','G','LUX','Grevenmacher'),
	('LU-L','L','LUX','Luxembourg (Luxemburg)'),
	('LU-CA','CA','LUX','Capellen'),
	('LU-CL','CL','LUX','Clervaux'),
	('LU-DI','DI','LUX','Diekirch'),
	('LU-EC','EC','LUX','Echternach'),
	('LU-ES','ES','LUX','Esch-sur-Alzette'),
	('LU-GR','GR','LUX','Grevenmacher'),
	('LU-LU','LU','LUX','Luxembourg'),
	('LU-ME','ME','LUX','Mersch'),
	('LU-RD','RD','LUX','Redange'),
	('LU-RM','RM','LUX','Remich'),
	('LU-VD','VD','LUX','Vianden'),
	('LU-WI','WI','LUX','Wiltz'),
	('LV-AI','AI','LVA','Aizkraukles Aprinkis'),
	('LV-AL','AL','LVA','Alūksnes Aprinkis'),
	('LV-BL','BL','LVA','Balvu Aprinkis'),
	('LV-BU','BU','LVA','Bauskas Aprinkis'),
	('LV-CE','CE','LVA','Cēsu Aprinkis'),
	('LV-DA','DA','LVA','Daugavpils Aprinkis'),
	('LV-DO','DO','LVA','Dobeles Aprinkis'),
	('LV-GU','GU','LVA','Gulbenes Aprinkis'),
	('LV-JL','JL','LVA','Jelgavas Aprinkis'),
	('LV-JK','JK','LVA','Jēkabpils Aprinkis'),
	('LV-KR','KR','LVA','Krāslavas Aprinkis'),
	('LV-KU','KU','LVA','Kuldīgas Aprinkis'),
	('LV-LM','LM','LVA','Limbažu Aprinkis'),
	('LV-LE','LE','LVA','Liepājas Aprinkis'),
	('LV-LU','LU','LVA','Ludzas Aprinkis'),
	('LV-MA','MA','LVA','Madonas Aprinkis'),
	('LV-OG','OG','LVA','Ogres Aprinkis'),
	('LV-PR','PR','LVA','Preilu Aprinkis'),
	('LV-RE','RE','LVA','Rēzeknes Aprinkis'),
	('LV-RI','RI','LVA','Rīgas Aprinkis'),
	('LV-SA','SA','LVA','Saldus Aprinkis'),
	('LV-TA','TA','LVA','Talsu Aprinkis'),
	('LV-TU','TU','LVA','Tukuma Aprinkis'),
	('LV-VK','VK','LVA','Valkas Aprinkis'),
	('LV-VM','VM','LVA','Valmieras Aprinkis'),
	('LV-VE','VE','LVA','Ventspils Aprinkis'),
	('LV-DGV','DGV','LVA','Daugavpils'),
	('LV-JEL','JEL','LVA','Jelgava'),
	('LV-JUR','JUR','LVA','Jūrmala'),
	('LV-LPX','LPX','LVA','Liepāja'),
	('LV-REZ','REZ','LVA','Rēzekne'),
	('LV-RIX','RIX','LVA','Rīga'),
	('LV-VEN','VEN','LVA','Ventspils'),
	('LV-01','01','LVA','Aizkraukles nov.'),
	('LV-02','02','LVA','Alūksnes nov.'),
	('LV-03','03','LVA','Balvu nov.'),
	('LV-04','04','LVA','Bauskas nov.'),
	('LV-05','05','LVA','Cēsu nov.'),
	('LV-07','07','LVA','Daugavpils nov.'),
	('LV-08','08','LVA','Dobeles nov.'),
	('LV-09','09','LVA','Gulbenes nov.'),
	('LV-10','10','LVA','Jēkabpils nov.'),
	('LV-12','12','LVA','Jelgavas nov.'),
	('LV-14','14','LVA','Krāslavas nov.'),
	('LV-15','15','LVA','Kuldīgas nov.'),
	('LV-18','18','LVA','Limbažu nov.'),
	('LV-19','19','LVA','Ludzas nov.'),
	('LV-20','20','LVA','Madonas nov.'),
	('LV-21','21','LVA','Ogres nov.'),
	('LV-22','22','LVA','Preiļu nov.'),
	('LV-24','24','LVA','Rēzeknes nov.'),
	('LV-27','27','LVA','Saldus nov.'),
	('LV-28','28','LVA','Talsu nov.'),
	('LV-29','29','LVA','Tukuma nov.'),
	('LV-30','30','LVA','Valkas nov.'),
	('LV-33','33','LVA','Ventspils nov.'),
	('LV-34','34','LVA','Ādažu nov.'),
	('LV-35','35','LVA','Aglonas nov.'),
	('LV-37','37','LVA','Aizputes nov.'),
	('LV-38','38','LVA','Aknīstes nov.'),
	('LV-39','39','LVA','Alojas nov.'),
	('LV-40','40','LVA','Alsungas nov.'),
	('LV-42','42','LVA','Amatas nov.'),
	('LV-43','43','LVA','Apes nov.'),
	('LV-44','44','LVA','Auces nov.'),
	('LV-45','45','LVA','Babītes nov.'),
	('LV-46','46','LVA','Baldones nov.'),
	('LV-47','47','LVA','Baltinavas nov.'),
	('LV-50','50','LVA','Beverīnas nov.'),
	('LV-51','51','LVA','Brocēnu nov.'),
	('LV-52','52','LVA','Burtnieku nov.'),
	('LV-53','53','LVA','Carnikavas nov.'),
	('LV-55','55','LVA','Cesvaines nov.'),
	('LV-56','56','LVA','Ciblas nov.'),
	('LV-57','57','LVA','Dagdas nov.'),
	('LV-60','60','LVA','Dundagas nov.'),
	('LV-61','61','LVA','Durbes nov.'),
	('LV-62','62','LVA','Engures nov.'),
	('LV-63','63','LVA','Ērgļu nov.'),
	('LV-64','64','LVA','Garkalnes nov.'),
	('LV-65','65','LVA','Grobiņas nov.'),
	('LV-67','67','LVA','Iecavas nov.'),
	('LV-68','68','LVA','Ikšķiles nov.'),
	('LV-69','69','LVA','Ilūkstes nov.'),
	('LV-70','70','LVA','Inčukalna nov.'),
	('LV-71','71','LVA','Jaunjelgavas nov.'),
	('LV-72','72','LVA','Jaunpiebalgas nov.'),
	('LV-73','73','LVA','Jaunpils nov.'),
	('LV-77','77','LVA','Kandavas nov.'),
	('LV-78','78','LVA','Kārsavas nov.'),
	('LV-79','79','LVA','Ķeguma nov.'),
	('LV-80','80','LVA','Ķekavas nov.'),
	('LV-81','81','LVA','Kocēnu nov.'),
	('LV-82','82','LVA','Kokneses nov.'),
	('LV-84','84','LVA','Krimuldas nov.'),
	('LV-85','85','LVA','Krustpils nov.'),
	('LV-87','87','LVA','Lielvārdes nov.'),
	('LV-88','88','LVA','Līgatnes nov.'),
	('LV-90','90','LVA','Līvānu nov.'),
	('LV-91','91','LVA','Lubānas nov.'),
	('LV-94','94','LVA','Mālpils nov.'),
	('LV-95','95','LVA','Mārupes nov.'),
	('LV-96','96','LVA','Mazsalacas nov.'),
	('LV-97','97','LVA','Naukšēnu nov.'),
	('LV-98','98','LVA','Neretas nov.'),
	('LV-99','99','LVA','Nīcas nov.'),
	('LV-A2','A2','LVA','Olaines nov.'),
	('LV-A3','A3','LVA','Ozolnieku nov.'),
	('LV-A4','A4','LVA','Pārgaujas nov.'),
	('LV-A5','A5','LVA','Pāvilostas nov.'),
	('LV-A6','A6','LVA','Pļaviņu nov.'),
	('LV-A8','A8','LVA','Priekules nov.'),
	('LV-A9','A9','LVA','Priekuļu nov.'),
	('LV-B1','B1','LVA','Raunas nov.'),
	('LV-B3','B3','LVA','Riebiņu nov.'),
	('LV-B4','B4','LVA','Rojas nov.'),
	('LV-B5','B5','LVA','Ropažu nov.'),
	('LV-B6','B6','LVA','Rucavas nov.'),
	('LV-B7','B7','LVA','Rugāju nov.'),
	('LV-B8','B8','LVA','Rūjienas nov.'),
	('LV-B9','B9','LVA','Rundāles nov.'),
	('LV-C2','C2','LVA','Salas nov.'),
	('LV-C3','C3','LVA','Salaspils nov.'),
	('LV-C5','C5','LVA','Saulkrastu nov.'),
	('LV-C6','C6','LVA','Sējas nov.'),
	('LV-C7','C7','LVA','Siguldas nov.'),
	('LV-C8','C8','LVA','Skrīveru nov.'),
	('LV-C9','C9','LVA','Skrundas nov.'),
	('LV-D1','D1','LVA','Smiltenes nov.'),
	('LV-D2','D2','LVA','Stopiņu nov.'),
	('LV-D3','D3','LVA','Strenču nov.'),
	('LV-D5','D5','LVA','Tērvetes nov.'),
	('LV-D7','D7','LVA','Vaiņodes nov.'),
	('LV-E1','E1','LVA','Varakļānu nov.'),
	('LV-E2','E2','LVA','Vārkavas nov.'),
	('LV-E3','E3','LVA','Vecpiebalgas nov.'),
	('LV-E4','E4','LVA','Vecumnieku nov.'),
	('LV-E6','E6','LVA','Viesītes nov.'),
	('LV-E7','E7','LVA','Viļakas nov.'),
	('LV-E8','E8','LVA','Viļānu nov.'),
	('LV-E9','E9','LVA','Zilupes nov.'),
	('LV-F1','F1','LVA','Mērsraga nov.'),
	('LY-BU','BU','LBY','Al Buţnān'),
	('LY-JA','JA','LBY','Al Jabal al Akhḑar'),
	('LY-JG','JG','LBY','Al Jabal al Gharbī'),
	('LY-JU','JU','LBY','Al Jufrah'),
	('LY-WA','WA','LBY','Al Wāḩah'),
	('LY-WU','WU','LBY','Al Wusţá'),
	('LY-ZA','ZA','LBY','Az Zāwiyah'),
	('LY-BA','BA','LBY','Banghāzī'),
	('LY-FA','FA','LBY','Fazzān'),
	('LY-MI','MI','LBY','Mişrātah'),
	('LY-NA','NA','LBY','Naggaza'),
	('LY-SF','SF','LBY','Sawfajjin'),
	('LY-TB','TB','LBY','Ţarābulus');
COMMIT;
ANALYZE;
