BEGIN;
INSERT INTO regions (iso3, iso2, country, name) VALUES
	('DE-BW','BW','DEU','Baden-Württemberg'),
	('DE-BY','BY','DEU','Bayern'),
	('DE-BE','BE','DEU','Berlin'),
	('DE-BB','BB','DEU','Brandenburg'),
	('DE-HB','HB','DEU','Bremen'),
	('DE-HH','HH','DEU','Hamburg'),
	('DE-HE','HE','DEU','Hessen'),
	('DE-MV','MV','DEU','Mecklenburg-Vorpommern'),
	('DE-NI','NI','DEU','Niedersachsen'),
	('DE-NW','NW','DEU','Nordrhein-Westfalen'),
	('DE-RP','RP','DEU','Rheinland-Pfalz'),
	('DE-SL','SL','DEU','Saarland'),
	('DE-SN','SN','DEU','Sachsen'),
	('DE-ST','ST','DEU','Sachsen-Anhalt'),
	('DE-SH','SH','DEU','Schleswig-Holstein'),
	('DE-TH','TH','DEU','Thüringen'),
	('DJ-AS','AS','DJI','Ali Sabieh'),
	('DJ-DI','DI','DJI','Dikhil'),
	('DJ-DJ','DJ','DJI','Djibouti'),
	('DJ-OB','OB','DJI','Obock'),
	('DJ-TA','TA','DJI','Tadjoura'),
	('DK-147','147','DNK','Frederiksberg'),
	('DK-101','101','DNK','Kǿbenhavn'),
	('DK-040','040','DNK','Bornholm'),
	('DK-020','020','DNK','Frederiksborg'),
	('DK-042','042','DNK','Fyn'),
	('DK-015','015','DNK','Kǿbenhavn'),
	('DK-080','080','DNK','Nordjylland'),
	('DK-055','055','DNK','Ribe'),
	('DK-065','065','DNK','Ringkǿbing'),
	('DK-025','025','DNK','Roskilde'),
	('DK-035','035','DNK','Storstrǿm'),
	('DK-050','050','DNK','Sǿnderjylland'),
	('DK-060','060','DNK','Vejle'),
	('DK-030','030','DNK','Vestsjælland'),
	('DK-076','076','DNK','Viborg'),
	('DK-070','070','DNK','Århus'),
	('DK-18','18','DNK','Region Midtjylland'),
	('DK-20','20','DNK','Region Sjælland'),
	('DK-21','21','DNK','Region Syddanmark'),
	('DK-81','81','DNK','Region Nordjylland'),
	('DK-82','82','DNK','Region Midtjylland'),
	('DK-83','83','DNK','Region Syddanmark'),
	('DK-84','84','DNK','Region Hovedstaden'),
	('DK-85','85','DNK','Region Sjælland'),
	('DM-DM','DM','DMA','Dominica'),
	('DO-DN','DN','DOM','Distrito National (Santo Domingo)'),
	('DO-AZ','AZ','DOM','Azua'),
	('DO-BR','BR','DOM','Bahoruco'),
	('DO-BH','BH','DOM','Barahona'),
	('DO-DA','DA','DOM','Dajabón'),
	('DO-DU','DU','DOM','Duarte'),
	('DO-SE','SE','DOM','El Seibo'),
	('DO-EP','EP','DOM','La Estrelleta [Elías Piña]'),
	('DO-HM','HM','DOM','Hato Mayor'),
	('DO-IN','IN','DOM','Independencia'),
	('DO-AL','AL','DOM','La Altagracia'),
	('DO-RO','RO','DOM','La Romana'),
	('DO-VE','VE','DOM','La Vega'),
	('DO-MT','MT','DOM','María Trinidad Sánchez'),
	('DO-MN','MN','DOM','Monseñor Nouel'),
	('DO-MC','MC','DOM','Monte Cristi'),
	('DO-MP','MP','DOM','Monte Plata'),
	('DO-PN','PN','DOM','Pedernales'),
	('DO-PR','PR','DOM','Peravia'),
	('DO-PP','PP','DOM','Puerto Plata'),
	('DO-SC','SC','DOM','Salcedo'),
	('DO-SM','SM','DOM','Samaná'),
	('DO-SZ','SZ','DOM','Sanchez Ramírez'),
	('DO-CR','CR','DOM','San Cristóbal'),
	('DO-JU','JU','DOM','San Juan'),
	('DO-PM','PM','DOM','San Pedro de Macorís'),
	('DO-ST','ST','DOM','Santiago'),
	('DO-SR','SR','DOM','Santiago Rodríguez'),
	('DO-VA','VA','DOM','Valverde'),
	('DO-','','DOM',''),
	('DZ-01','01','DZA','Adrar'),
	('DZ-44','44','DZA','Aïn Defla'),
	('DZ-46','46','DZA','Aïn Témouchent'),
	('DZ-16','16','DZA','Alger'),
	('DZ-05','05','DZA','Batna'),
	('DZ-08','08','DZA','Béchar'),
	('DZ-06','06','DZA','Béjaïa'),
	('DZ-07','07','DZA','Biskra'),
	('DZ-09','09','DZA','Blida'),
	('DZ-34','34','DZA','Bordj Bou Arréridj'),
	('DZ-10','10','DZA','Bouira'),
	('DZ-35','35','DZA','Boumerdès'),
	('DZ-02','02','DZA','Chlef'),
	('DZ-25','25','DZA','Constantine'),
	('DZ-17','17','DZA','Djelfa'),
	('DZ-32','32','DZA','El Bayadh'),
	('DZ-39','39','DZA','El Oued'),
	('DZ-36','36','DZA','El Tarf'),
	('DZ-47','47','DZA','Ghardaïa'),
	('DZ-24','24','DZA','Guelma'),
	('DZ-33','33','DZA','Illizi'),
	('DZ-18','18','DZA','Jijel'),
	('DZ-40','40','DZA','Khenchela'),
	('DZ-03','03','DZA','Laghouat'),
	('DZ-29','29','DZA','Mascara'),
	('DZ-26','26','DZA','Médéa'),
	('DZ-43','43','DZA','Mila'),
	('DZ-27','27','DZA','Mostaganem'),
	('DZ-28','28','DZA','Msila'),
	('DZ-45','45','DZA','Naama'),
	('DZ-31','31','DZA','Oran'),
	('DZ-30','30','DZA','Ouargla'),
	('DZ-04','04','DZA','Oum el Bouaghi'),
	('DZ-48','48','DZA','Relizane'),
	('DZ-20','20','DZA','Saïda'),
	('DZ-19','19','DZA','Sétif'),
	('DZ-22','22','DZA','Sidi Bel Abbès'),
	('DZ-21','21','DZA','Skikda'),
	('DZ-41','41','DZA','Souk Ahras'),
	('DZ-11','11','DZA','Tamanghasset'),
	('DZ-12','12','DZA','Tébessa'),
	('DZ-14','14','DZA','Tiaret'),
	('DZ-37','37','DZA','Tindouf'),
	('DZ-42','42','DZA','Tipaza'),
	('DZ-38','38','DZA','Tissemsilt'),
	('DZ-15','15','DZA','Tizi Ouzou'),
	('DZ-13','13','DZA','Tlemcen'),
	('DZ-23','23','DZA','Annaba'),
	('EC-A','A','ECU','Azuay'),
	('EC-B','B','ECU','Bolívar'),
	('EC-F','F','ECU','Cañar'),
	('EC-C','C','ECU','Carchi'),
	('EC-X','X','ECU','Cotopaxi'),
	('EC-H','H','ECU','Chimborazo'),
	('EC-O','O','ECU','El Oro'),
	('EC-E','E','ECU','Esmeraldas'),
	('EC-W','W','ECU','Galápagos'),
	('EC-G','G','ECU','Guayas'),
	('EC-I','I','ECU','Imbabura'),
	('EC-L','L','ECU','Loja'),
	('EC-R','R','ECU','Los Ríos'),
	('EC-M','M','ECU','Manabí'),
	('EC-S','S','ECU','Morona-Santiago'),
	('EC-N','N','ECU','Napo'),
	('EC-Y','Y','ECU','Pastaza'),
	('EC-P','P','ECU','Pichincha'),
	('EC-U','U','ECU','Sucumbíos'),
	('EC-T','T','ECU','Tungurahua'),
	('EC-Z','Z','ECU','Zarnora-Chinchipe'),
	('EE-37','37','EST','Harjumaa'),
	('EE-39','39','EST','Hiiumaa'),
	('EE-44','44','EST','Ida-Virumaa'),
	('EE-49','49','EST','Jōgevamaa'),
	('EE-51','51','EST','Järvamaa'),
	('EE-57','57','EST','Läänemaa'),
	('EE-59','59','EST','Lääne-Virumaa'),
	('EE-65','65','EST','Pōlvamaa'),
	('EE-67','67','EST','Pärnumaa'),
	('EE-70','70','EST','Raplamaa'),
	('EE-74','74','EST','Saaremaa'),
	('EE-78','78','EST','Tartumaa'),
	('EE-82','82','EST','Valgamaa'),
	('EE-84','84','EST','Viljandimaa'),
	('EE-86','86','EST','Vōrumaa'),
	('EE-01','01','EST','Harju maakond'),
	('EE-02','02','EST','Hiiu maakond'),
	('EE-03','03','EST','Ida-Viru maakond'),
	('EE-04','04','EST','Järva maakond'),
	('EE-05','05','EST','Jõgeva maakond'),
	('EE-07','07','EST','Lääne maakond'),
	('EE-08','08','EST','Lääne-Viru maakond'),
	('EE-11','11','EST','Pärnu maakond'),
	('EE-12','12','EST','Põlva maakond'),
	('EE-13','13','EST','Rapla maakond'),
	('EE-14','14','EST','Saare maakond'),
	('EE-18','18','EST','Tartu maakond'),
	('EE-19','19','EST','Valga maakond'),
	('EE-20','20','EST','Viljandi maakond'),
	('EE-21','21','EST','Võru maakond'),
	('EG-DK','DK','EGY','Ad Daqahlīyah'),
	('EG-BA','BA','EGY','Al Baḩr al Aḩmar'),
	('EG-BH','BH','EGY','Al Buḩayrah'),
	('EG-FYM','FYM','EGY','Al Fayyūm'),
	('EG-GH','GH','EGY','Al Gharbīyah'),
	('EG-ALX','ALX','EGY','Al Iskandarīyah'),
	('EG-IS','IS','EGY','Al Ismā‘īlīyah'),
	('EG-GZ','GZ','EGY','Al Jīzah'),
	('EG-MNF','MNF','EGY','Al Minūfīyah'),
	('EG-MN','MN','EGY','Al Minyā'),
	('EG-C','C','EGY','Al Qāhirah'),
	('EG-KB','KB','EGY','Al Qalyūbīyah'),
	('EG-WAD','WAD','EGY','Al Wādī al Jadīd'),
	('EG-SHR','SHR','EGY','Ash Sharqīyah'),
	('EG-SUZ','SUZ','EGY','As Suways'),
	('EG-ASN','ASN','EGY','Aswān'),
	('EG-AST','AST','EGY','Asyūţ'),
	('EG-BNS','BNS','EGY','Banī Suwayf'),
	('EG-PTS','PTS','EGY','Būr Sa‘īd'),
	('EG-DT','DT','EGY','Dumyāţ'),
	('EG-JS','JS','EGY','Janūb Sīnā''),
	('EG-KFS','KFS','EGY','Kafr ash Shaykh'),
	('EG-MT','MT','EGY','Maţrūḩ'),
	('EG-KN','KN','EGY','Qinā'),
	('EG-SIN','SIN','EGY','Shamāl Sīnā''),
	('EG-SHG','SHG','EGY','Sūhāj'),
	('EH-EH','EH','ESH','Western Sahara'),
	('ER-AG','AG','ERI','Akele Guzai [Akalä Guzay]'),
	('ER-AS','AS','ERI','Asmara [Asmära]'),
	('ER-BA','BA','ERI','Barka'),
	('ER-DE','DE','ERI','Denkalia [Dänkali]'),
	('ER-GS','GS','ERI','Gash-Setit [Gaš enna Sätit]'),
	('ER-HA','HA','ERI','Hamasien [Hamasén]'),
	('ER-SA','SA','ERI','Sahel'),
	('ER-SM','SM','ERI','Semhar [Sämhar]'),
	('ER-SN','SN','ERI','Senhit [Sänhet]'),
	('ER-SR','SR','ERI','Seraye [Särayé]'),
	('ES-AN','AN','ESP','Andalucía'),
	('ES-AL','AL','ESP','Almería'),
	('ES-CA','CA','ESP','Cádiz'),
	('ES-CO','CO','ESP','Córdoba'),
	('ES-GR','GR','ESP','Granada'),
	('ES-H','H','ESP','Huelva'),
	('ES-J','J','ESP','Jaén'),
	('ES-MA','MA','ESP','Málaga'),
	('ES-SE','SE','ESP','Sevilla'),
	('ES-AR','AR','ESP','Aragón'),
	('ES-HU','HU','ESP','Huesca'),
	('ES-TE','TE','ESP','Teruel'),
	('ES-Z','Z','ESP','Zaragoza'),
	('ES-O','O','ESP','Asturias'),
	('ES-CN','CN','ESP','Canarias'),
	('ES-GC','GC','ESP','Las Palmas'),
	('ES-TF','TF','ESP','Santa Cruz De Tenerife'),
	('ES-S','S','ESP','Cantabria'),
	('ES-CM','CM','ESP','Castilla-La Mancha'),
	('ES-AB','AB','ESP','Albacete'),
	('ES-CR','CR','ESP','Ciudad Real'),
	('ES-CU','CU','ESP','Cuenca'),
	('ES-GU','GU','ESP','Guadalajara'),
	('ES-TO','TO','ESP','Toledo'),
	('ES-CL','CL','ESP','Castilla y León'),
	('ES-AV','AV','ESP','Ávila'),
	('ES-BU','BU','ESP','Burgos'),
	('ES-LE','LE','ESP','León'),
	('ES-P','P','ESP','Palencia'),
	('ES-SA','SA','ESP','Salamanca'),
	('ES-SG','SG','ESP','Segovia'),
	('ES-SO','SO','ESP','Soria'),
	('ES-VA','VA','ESP','Valladolid'),
	('ES-ZA','ZA','ESP','Zamora'),
	('ES-CT','CT','ESP','Cataluña'),
	('ES-B','B','ESP','Barcelona'),
	('ES-GE','GE','ESP','Gerona'),
	('ES-L','L','ESP','Lérida'),
	('ES-T','T','ESP','Tarragona'),
	('ES-EX','EX','ESP','Extremadura'),
	('ES-BA','BA','ESP','Badajoz'),
	('ES-CC','CC','ESP','Cáceres'),
	('ES-GA','GA','ESP','Galicia'),
	('ES-C','C','ESP','La Coruña'),
	('ES-LU','LU','ESP','Lugo'),
	('ES-OR','OR','ESP','Orense'),
	('ES-PO','PO','ESP','Pontevedra'),
	('ES-PM','PM','ESP','Baleares'),
	('ES-LO','LO','ESP','La Rioja'),
	('ES-M','M','ESP','Madrid'),
	('ES-MU','MU','ESP','Murcia'),
	('ES-NA','NA','ESP','Navarra'),
	('ES-PV','PV','ESP','País Vasco'),
	('ES-VI','VI','ESP','Álava'),
	('ES-SS','SS','ESP','Guipúzcoa'),
	('ES-BI','BI','ESP','Vizcaya'),
	('ES-VC','VC','ESP','Valenciana, Comunidad'),
	('ES-A','A','ESP','Alicante'),
	('ES-CS','CS','ESP','Castellón'),
	('ES-V','V','ESP','Valencia'),
	('ES-AS','AS','ESP','Asturias'),
	('ES-CB','CB','ESP','Cantabria'),
	('ES-CE','CE','ESP','Ceuta'),
	('ES-IB','IB','ESP','Baleares'),
	('ES-MC','MC','ESP','Murcia'),
	('ES-MD','MD','ESP','Madrid'),
	('ES-ML','ML','ESP','Melilla'),
	('ES-NC','NC','ESP','Navarra'),
	('ES-RI','RI','ESP','La Rioja'),
	('ET-AA','AA','ETH','Addis Ababa [Addis Abeba]'),
	('ET-AF','AF','ETH','Afar'),
	('ET-AM','AM','ETH','Amara [Amhara]'),
	('ET-BE','BE','ETH','Benshangul-Gumaz [Bénishangul]'),
	('ET-GA','GA','ETH','Gambela Peoples [Gambéla]'),
	('ET-HA','HA','ETH','Harari People [Harer]'),
	('ET-OR','OR','ETH','Oromia [Oromo]'),
	('ET-SO','SO','ETH','Somali'),
	('ET-SN','SN','ETH','Southern Nations, Nationalities and Peoples'),
	('ET-TI','TI','ETH','Tigrai [Tegré]'),
	('FI-AL','AL','FIN','Ahvenanmaan lääni'),
	('FI-ES','ES','FIN','Etelä-Suomen lääni'),
	('FI-IS','IS','FIN','Itä-Suomen lääni'),
	('FI-LL','LL','FIN','Lapin lääni'),
	('FI-LS','LS','FIN','Länsi-Suomen lääni'),
	('FI-OL','OL','FIN','Oulun lääni'),
	('FI-01','01','FIN','Uusimaa'),
	('FI-02','02','FIN','Southwest Finland'),
	('FI-04','04','FIN','Satakunta'),
	('FI-05','05','FIN','Kanta-Häme'),
	('FI-06','06','FIN','Pirkanmaa'),
	('FI-07','07','FIN','Päijänne Tavastia'),
	('FI-08','08','FIN','Kymenlaakso'),
	('FI-09','09','FIN','South Karelia'),
	('FI-10','10','FIN','Southern Savonia'),
	('FI-11','11','FIN','Northern Savo'),
	('FI-12','12','FIN','North Karelia'),
	('FI-13','13','FIN','Central Finland Region'),
	('FI-14','14','FIN','South Ostrobothnia Region'),
	('FI-15','15','FIN','Ostrobothnia Region'),
	('FI-16','16','FIN','Central Ostrobothnia Region'),
	('FI-17','17','FIN','North Ostrobothnia Region'),
	('FI-18','18','FIN','Kainuu'),
	('FI-19','19','FIN','Lapland'),
	('FJ-C','C','FJI','Central'),
	('FJ-E','E','FJI','Eastern'),
	('FJ-N','N','FJI','Northern'),
	('FJ-W','W','FJI','Western'),
	('FJ-R','R','FJI','Rotuma'),
	('FK-FK','FK','FLK','Falkland Islands (Malvinas)'),
	('FM-TRK','TRK','FSM','chuuk'),
	('FM-KSA','KSA','FSM','Kosrae'),
	('FM-PNI','PNI','FSM','Pohnpei'),
	('FM-YAP','YAP','FSM','Yap'),
	('FM-01','01','FSM','State of Kosrae'),
	('FM-02','02','FSM','State of Pohnpei'),
	('FM-03','03','FSM','State of Chuuk'),
	('FM-04','04','FSM','State of Yap'),
	('FO-FO','FO','FRO','Faroe Islands'),
	('FO-','','FRO',''),
	('FR-A','A','FRA','Alsace'),
	('FR-67','67','FRA','Bas-Rhin'),
	('FR-68','68','FRA','Haut-Rhin'),
	('FR-B','B','FRA','Aquitaine'),
	('FR-79','79','FRA','Deux-Sèvres'),
	('FR-24','24','FRA','Dordogne'),
	('FR-33','33','FRA','Gironde'),
	('FR-40','40','FRA','Landes'),
	('FR-47','47','FRA','Lot-et-Garonne'),
	('FR-64','64','FRA','Pyrénées-Atlantiques'),
	('FR-C','C','FRA','Auvergne'),
	('FR-03','03','FRA','Allier'),
	('FR-15','15','FRA','Cantal'),
	('FR-43','43','FRA','Haute-Loire'),
	('FR-63','63','FRA','Puy-de-Dôme'),
	('FR-P','P','FRA','Basse-Normandie'),
	('FR-14','14','FRA','Calvados'),
	('FR-50','50','FRA','Manche'),
	('FR-61','61','FRA','Orne'),
	('FR-D','D','FRA','Bourgogne'),
	('FR-21','21','FRA','Côte-d'Or'),
	('FR-58','58','FRA','Nièvre'),
	('FR-71','71','FRA','Saône-et-Loire'),
	('FR-89','89','FRA','Yonne'),
	('FR-E','E','FRA','Bretagne'),
	('FR-22','22','FRA','Cotes-d'Armor'),
	('FR-29','29','FRA','Finistère'),
	('FR-35','35','FRA','Ille-et-Vilaine'),
	('FR-56','56','FRA','Morbihan'),
	('FR-F','F','FRA','Centre'),
	('FR-18','18','FRA','Cher'),
	('FR-28','28','FRA','Eure-et-Loir'),
	('FR-36','36','FRA','Indre'),
	('FR-37','37','FRA','Indre-et-Loire'),
	('FR-41','41','FRA','Loir-et-Cher'),
	('FR-45','45','FRA','Loiret'),
	('FR-G','G','FRA','Champagne-Ardenne'),
	('FR-08','08','FRA','Ardennes'),
	('FR-10','10','FRA','Aube'),
	('FR-52','52','FRA','Haute-Marne'),
	('FR-51','51','FRA','Marne'),
	('FR-H','H','FRA','Corse'),
	('FR-2A','2A','FRA','Corse-du-Sud'),
	('FR-2B','2B','FRA','Haute-Corse'),
	('FR-I','I','FRA','Franche-Comté'),
	('FR-25','25','FRA','Doubs'),
	('FR-70','70','FRA','Haute-Saône'),
	('FR-39','39','FRA','Jura'),
	('FR-90','90','FRA','Territoire de Belfort'),
	('FR-Q','Q','FRA','Haute-Normandie'),
	('FR-27','27','FRA','Eure'),
	('FR-76','76','FRA','Seine-Maritime'),
	('FR-J','J','FRA','Île-de-France'),
	('FR-91','91','FRA','Essonne'),
	('FR-92','92','FRA','Hauts-de-Seine'),
	('FR-75','75','FRA','Paris'),
	('FR-77','77','FRA','Seine-et-Marne'),
	('FR-93','93','FRA','Seine-Saint-Denis'),
	('FR-94','94','FRA','Val-de-Marne'),
	('FR-95','95','FRA','Val-d'Oise'),
	('FR-78','78','FRA','Yvelines'),
	('FR-K','K','FRA','Languedoc-Roussillon'),
	('FR-11','11','FRA','Aude'),
	('FR-30','30','FRA','Gard'),
	('FR-34','34','FRA','Hérault'),
	('FR-48','48','FRA','Lozère'),
	('FR-66','66','FRA','Pyrénées-Orientales'),
	('FR-L','L','FRA','Limousin'),
	('FR-19','19','FRA','Corrèze'),
	('FR-23','23','FRA','Creuse'),
	('FR-87','87','FRA','Haute-Vienne'),
	('FR-M','M','FRA','Lorraine'),
	('FR-54','54','FRA','Meurthe-et-Moselle'),
	('FR-55','55','FRA','Meuse'),
	('FR-57','57','FRA','Moselle'),
	('FR-88','88','FRA','Vosges'),
	('FR-N','N','FRA','Midi-Pyrénées'),
	('FR-09','09','FRA','Ariège'),
	('FR-12','12','FRA','Aveyron'),
	('FR-32','32','FRA','Gers'),
	('FR-31','31','FRA','Haute-Garonne'),
	('FR-65','65','FRA','Hautes-Pyrénées'),
	('FR-46','46','FRA','Lot'),
	('FR-81','81','FRA','Tarn'),
	('FR-82','82','FRA','Tarn-et-Garonne'),
	('FR-O','O','FRA','Nord-Pas-de-Calais'),
	('FR-59','59','FRA','Nord'),
	('FR-62','62','FRA','Pas-de-Calais'),
	('FR-R','R','FRA','Pays de la Loire'),
	('FR-44','44','FRA','Loire-Atlantique'),
	('FR-49','49','FRA','Maine-et-Loire'),
	('FR-53','53','FRA','Mayenne'),
	('FR-72','72','FRA','Sarthe'),
	('FR-85','85','FRA','Vendée'),
	('FR-S','S','FRA','Picardie'),
	('FR-02','02','FRA','Aisne'),
	('FR-60','60','FRA','Oise'),
	('FR-80','80','FRA','Somme'),
	('FR-T','T','FRA','Poitou-Charentes'),
	('FR-16','16','FRA','Charente'),
	('FR-17','17','FRA','Charente-Maritime'),
	('FR-86','86','FRA','Vienne'),
	('FR-U','U','FRA','Provence-Alpes-Côte d'Azur'),
	('FR-04','04','FRA','Alpes-de-Haute-Provence'),
	('FR-06','06','FRA','Alpes-Maritimes'),
	('FR-13','13','FRA','Bauches-du-Rhône'),
	('FR-05','05','FRA','Hautes-Alpes'),
	('FR-83','83','FRA','Var'),
	('FR-84','84','FRA','Vaucluse'),
	('FR-V','V','FRA','Rhône-Alpes'),
	('FR-01','01','FRA','Ain'),
	('FR-07','07','FRA','Ardèche'),
	('FR-26','26','FRA','Drôme'),
	('FR-74','74','FRA','Haute-Savoie'),
	('FR-38','38','FRA','Isère'),
	('FR-42','42','FRA','Loire'),
	('FR-69','69','FRA','Rhône'),
	('FR-73','73','FRA','Savoie'),
	('FR-GP','GP','FRA','Guadeloupe'),
	('FR-GF','GF','FRA','Guyane (francaise)'),
	('FR-MQ','MQ','FRA','Martinique'),
	('FR-RE','RE','FRA','Réunion'),
	('FR-YT','YT','FRA','Mayotte'),
	('FR-PM','PM','FRA','Saint-Pierre-et-Miquelon'),
	('FR-NC','NC','FRA','Nouvelle-Calédonie'),
	('FR-PF','PF','FRA','Polynésie française'),
	('FR-TF','TF','FRA','Terres Australes'),
	('FR-WF','WF','FRA','Wallis et Futuna'),
	('FR-','','FRA','');
COMMIT;
ANALYZE;
