BEGIN;
INSERT INTO regions (iso3, iso2, country, name) VALUES
	('MA-CE','CE','MAR','Centre'),
	('MA-AZI','AZI','MAR','Azilal'),
	('MA-BEM','BEM','MAR','Beni Mellal'),
	('MA-BES','BES','MAR','Ben Slimane'),
	('MA-BOM','BOM','MAR','Boulemane'),
	('MA-CAS','CAS','MAR','Casablanca [Dar el Beïda]'),
	('MA-JDI','JDI','MAR','El Jadida'),
	('MA-KHO','KHO','MAR','Khouribga'),
	('MA-SET','SET','MAR','Settat'),
	('MA-CN','CN','MAR','Centre-Nord'),
	('MA-HOC','HOC','MAR','Al Hoceïma'),
	('MA-FES','FES','MAR','Fès'),
	('MA-SEF','SEF','MAR','Sefrou'),
	('MA-TAO','TAO','MAR','Taounate'),
	('MA-TAZ','TAZ','MAR','Taza'),
	('MA-CS','CS','MAR','Centre-Sud'),
	('MA-HAJ','HAJ','MAR','El Hajeb'),
	('MA-ERR','ERR','MAR','Errachidia'),
	('MA-IFR','IFR','MAR','Ifrane'),
	('MA-KHN','KHN','MAR','Khenifra'),
	('MA-MEK','MEK','MAR','Meknès'),
	('MA-ES','ES','MAR','Est'),
	('MA-BER','BER','MAR','Berkane'),
	('MA-FIG','FIG','MAR','Figuig'),
	('MA-IRA','IRA','MAR','Jrada'),
	('MA-NAD','NAD','MAR','Nador'),
	('MA-OUJ','OUJ','MAR','Oujda'),
	('MA-NO','NO','MAR','Nord-Ouest'),
	('MA-CHE','CHE','MAR','Chefchaouene'),
	('MA-KEN','KEN','MAR','Kénitra'),
	('MA-KHE','KHE','MAR','Khemisset'),
	('MA-LAR','LAR','MAR','Larache'),
	('MA-RBA','RBA','MAR','Rabat-Salé'),
	('MA-SIK','SIK','MAR','Sidi Kacem'),
	('MA-TNG','TNG','MAR','Tanger'),
	('MA-TET','TET','MAR','Tétouan'),
	('MA-SU','SU','MAR','Sud'),
	('MA-AGD','AGD','MAR','Agadir'),
	('MA-BAH','BAH','MAR','Aït Baha'),
	('MA-MEL','MEL','MAR','Aït Melloul'),
	('MA-ASZ','ASZ','MAR','Assa-Zag'),
	('MA-BOD','BOD','MAR','Boujdour (EH)'),
	('MA-ESM','ESM','MAR','Es Semara (EH)'),
	('MA-GUE','GUE','MAR','Guelmim'),
	('MA-LAA','LAA','MAR','Laayoune (EH)'),
	('MA-OUA','OUA','MAR','Ouarzazate'),
	('MA-OUD','OUD','MAR','Oued ed Dahab (EH)'),
	('MA-TNT','TNT','MAR','Tan-Tan'),
	('MA-TAR','TAR','MAR','Taroudannt'),
	('MA-TAT','TAT','MAR','Tata'),
	('MA-TIZ','TIZ','MAR','Tiznit'),
	('MA-TS','TS','MAR','Tensift'),
	('MA-HAO','HAO','MAR','Al Haouz'),
	('MA-CHI','CHI','MAR','Chichaoua'),
	('MA-ESI','ESI','MAR','Essaouira'),
	('MA-KES','KES','MAR','Kelaat Sraghna'),
	('MA-MAR','MAR','MAR','Marrakech'),
	('MA-SAF','SAF','MAR','Safi'),
	('MC-MC','MC','MCO','Monaco'),
	('MC-01','01','MCO','Monaco'),
	('MD-BAL','BAL','MDA','Bălţi'),
	('MD-CAH','CAH','MDA','Cahul'),
	('MD-CHI','CHI','MDA','Chişinău'),
	('MD-DUB','DUB','MDA','Dubăsari'),
	('MD-ORH','ORH','MDA','Orhei'),
	('MD-RIB','RIB','MDA','Rîbniţa'),
	('MD-SOC','SOC','MDA','Soroca'),
	('MD-TIG','TIG','MDA','Tighina'),
	('MD-TIR','TIR','MDA','Tiraspol'),
	('MD-UNG','UNG','MDA','Ungheni'),
	('MD-ANE','ANE','MDA','Anenii Noi'),
	('MD-BAS','BAS','MDA','Basarabeasca'),
	('MD-BRI','BRI','MDA','Brinceni'),
	('MD-CHL','CHL','MDA','Cahul'),
	('MD-CAM','CAM','MDA','Camenca'),
	('MD-CAN','CAN','MDA','Cantemir'),
	('MD-CAI','CAI','MDA','Căinari'),
	('MD-CAL','CAL','MDA','Călăraşi'),
	('MD-CAS','CAS','MDA','Căuşeni'),
	('MD-CIA','CIA','MDA','Ciadîr-Lunga'),
	('MD-CIM','CIM','MDA','Cimişlia'),
	('MD-COM','COM','MDA','Comrat'),
	('MD-CRI','CRI','MDA','Criuleni'),
	('MD-DON','DON','MDA','Donduşeni'),
	('MD-DRO','DRO','MDA','Drochia'),
	('MD-DBI','DBI','MDA','Dubăsari'),
	('MD-EDI','EDI','MDA','Edineţ'),
	('MD-FAL','FAL','MDA','Făleşti'),
	('MD-FLO','FLO','MDA','Floreşti'),
	('MD-GLO','GLO','MDA','Glodeni'),
	('MD-GRI','GRI','MDA','Grigoriopol'),
	('MD-HIN','HIN','MDA','Hînceşti'),
	('MD-IAL','IAL','MDA','Ialoveni'),
	('MD-LEO','LEO','MDA','Leova'),
	('MD-NIS','NIS','MDA','Nisporeni'),
	('MD-OCN','OCN','MDA','Ocniţa'),
	('MD-OHI','OHI','MDA','Orhei'),
	('MD-REZ','REZ','MDA','Rezina'),
	('MD-RIT','RIT','MDA','Rîbniţa'),
	('MD-RIS','RIS','MDA','Rîşcani'),
	('MD-SIN','SIN','MDA','Sîngerei'),
	('MD-SLO','SLO','MDA','Slobozia'),
	('MD-SOA','SOA','MDA','Soroca'),
	('MD-STR','STR','MDA','Străşeni'),
	('MD-SOL','SOL','MDA','Şoldăneşti'),
	('MD-STE','STE','MDA','Ştefan Vodă'),
	('MD-TAR','TAR','MDA','Taraclia'),
	('MD-TEL','TEL','MDA','Teleneşti'),
	('MD-UGI','UGI','MDA','Ungheni'),
	('MD-VUL','VUL','MDA','Vulcăneşti'),
	('MD-','','MDA','Mun.Chisinau'),
	('MG-T','T','MDG','Antananarivo'),
	('MG-D','D','MDG','Antsiranana'),
	('MG-F','F','MDG','Fianarantsoa'),
	('MG-M','M','MDG','Mahajanga'),
	('MG-A','A','MDG','Toamasina'),
	('MG-U','U','MDG','Toliara'),
	('MH-L','L','MHL','Ralik chain'),
	('MH-ALL','ALL','MHL','Ailinglapalap'),
	('MH-EBO','EBO','MHL','Ebon'),
	('MH-ENI','ENI','MHL','Eniwetok'),
	('MH-JAL','JAL','MHL','Jaluit'),
	('MH-KIL','KIL','MHL','Kili'),
	('MH-KWA','KWA','MHL','Kwajalein'),
	('MH-LAE','LAE','MHL','Lae'),
	('MH-LIB','LIB','MHL','Lib'),
	('MH-NMK','NMK','MHL','Namorik'),
	('MH-NMU','NMU','MHL','Namu'),
	('MH-RON','RON','MHL','Rongelap'),
	('MH-UJA','UJA','MHL','Ujae'),
	('MH-UJL','UJL','MHL','Ujelang'),
	('MH-WTH','WTH','MHL','Wotho'),
	('MH-T','T','MHL','Ratak chain'),
	('MH-ALK','ALK','MHL','Ailuk'),
	('MH-ARN','ARN','MHL','Arno'),
	('MH-AUR','AUR','MHL','Aur'),
	('MH-LIK','LIK','MHL','Likiep'),
	('MH-MAJ','MAJ','MHL','Majuro'),
	('MH-MAL','MAL','MHL','Maloelap'),
	('MH-MEJ','MEJ','MHL','Mejit'),
	('MH-MIL','MIL','MHL','Mili'),
	('MH-UTI','UTI','MHL','Utirik'),
	('MH-WTJ','WTJ','MHL','Wotje'),
	('MH-68','68','MHL','Mh'),
	('MK-MK','MK','MKD','Macedonia'),
	('MK-','','MKD',''),
	('ML-BKO','BKO','MLI','Bamako'),
	('ML-7','7','MLI','Gao'),
	('ML-1','1','MLI','Kayes'),
	('ML-8','8','MLI','Kidal'),
	('ML-2','2','MLI','Koulikoro'),
	('ML-5','5','MLI','Mopti'),
	('ML-4','4','MLI','Ségou'),
	('ML-3','3','MLI','Sikasso'),
	('ML-6','6','MLI','Tombouctou'),
	('MM-07','07','MMR','Ayeyarwady'),
	('MM-02','02','MMR','Bago'),
	('MM-03','03','MMR','Magway'),
	('MM-04','04','MMR','Mandalay'),
	('MM-01','01','MMR','Sagaing'),
	('MM-05','05','MMR','Tanintharyi'),
	('MM-06','06','MMR','Yangon'),
	('MM-14','14','MMR','Chin'),
	('MM-11','11','MMR','Kachin'),
	('MM-12','12','MMR','Kayah'),
	('MM-13','13','MMR','Kayin'),
	('MM-15','15','MMR','Mon'),
	('MM-16','16','MMR','Rakhine'),
	('MM-17','17','MMR','Shan'),
	('MN-1','1','MNG','Ulaanbaatar'),
	('MN-073','073','MNG','Arhangay'),
	('MN-069','069','MNG','Bayanhongor'),
	('MN-071','071','MNG','Bayan-Ölgiy'),
	('MN-067','067','MNG','Bulgan'),
	('MN-037','037','MNG','Darhan uul'),
	('MN-061','061','MNG','Dornod'),
	('MN-063','063','MNG','Dornogovĭ'),
	('MN-059','059','MNG','Dundgovĭ'),
	('MN-057','057','MNG','Dzavhan'),
	('MN-065','065','MNG','Govĭ-Altay'),
	('MN-064','064','MNG','Govĭ-Sümber'),
	('MN-039','039','MNG','Hentiy'),
	('MN-043','043','MNG','Hovd'),
	('MN-041','041','MNG','Hövsgöl'),
	('MN-053','053','MNG','Ömnögovĭ'),
	('MN-035','035','MNG','Orhon'),
	('MN-055','055','MNG','Övörhangay'),
	('MN-049','049','MNG','Selenge'),
	('MN-051','051','MNG','Sühbaatar'),
	('MN-047','047','MNG','Töv'),
	('MN-046','046','MNG','Uvs'),
	('MO-MO','MO','MAC','Macau'),
	('MP-MP','MP','MNP','Northern Mariana Islands'),
	('MP-100','100','MNP','Rota'),
	('MP-110','110','MNP','Saipan'),
	('MP-120','120','MNP','Tinian'),
	('MQ-MQ','MQ','MTQ','Martinique'),
	('MR-NKC','NKC','MRT','Nouakchott'),
	('MR-07','07','MRT','Adrar'),
	('MR-03','03','MRT','Assaba'),
	('MR-05','05','MRT','Brakna'),
	('MR-08','08','MRT','Dakhlet Nouādhibou'),
	('MR-04','04','MRT','Gorgol'),
	('MR-10','10','MRT','Guidimaka'),
	('MR-01','01','MRT','Hodh ech Chargui'),
	('MR-02','02','MRT','Hodh el Gharbi'),
	('MR-12','12','MRT','Inchiri'),
	('MR-09','09','MRT','Tagant'),
	('MR-11','11','MRT','Tiris Zemmour'),
	('MR-06','06','MRT','Trarza'),
	('MS-MS','MS','MSR','Montserrat'),
	('MT-MT','MT','MLT','Malta'),
	('MT-01','01','MLT','Attard'),
	('MT-02','02','MLT','Balzan'),
	('MT-03','03','MLT','Il-Birgu'),
	('MT-04','04','MLT','Birkirkara'),
	('MT-05','05','MLT','Birżebbuġa'),
	('MT-06','06','MLT','Bormla'),
	('MT-07','07','MLT','Dingli'),
	('MT-08','08','MLT','Il-Fgura'),
	('MT-09','09','MLT','Il-Furjana'),
	('MT-10','10','MLT','Il-Fontana'),
	('MT-11','11','MLT','Għajnsielem'),
	('MT-12','12','MLT','L-Għarb'),
	('MT-13','13','MLT','Ħal Għargħur'),
	('MT-14','14','MLT','L-Għasri'),
	('MT-15','15','MLT','Ħal Għaxaq'),
	('MT-16','16','MLT','Il-Gudja'),
	('MT-17','17','MLT','Il-Gżira'),
	('MT-18','18','MLT','Il-Ħamrun'),
	('MT-19','19','MLT','L-Iklin'),
	('MT-20','20','MLT','L-Imdina'),
	('MT-21','21','MLT','L-Imġarr'),
	('MT-22','22','MLT','L-Imqabba'),
	('MT-23','23','MLT','L-Imsida'),
	('MT-24','24','MLT','L-Imtarfa'),
	('MT-25','25','MLT','L-Isla'),
	('MT-26','26','MLT','Il-Kalkara'),
	('MT-27','27','MLT','Ta’ Kerċem'),
	('MT-28','28','MLT','Kirkop'),
	('MT-29','29','MLT','Lija'),
	('MT-30','30','MLT','Luqa'),
	('MT-31','31','MLT','Il-Marsa'),
	('MT-32','32','MLT','Marsaskala'),
	('MT-33','33','MLT','Marsaxlokk'),
	('MT-34','34','MLT','Il-Mellieħa'),
	('MT-35','35','MLT','Il-Mosta'),
	('MT-36','36','MLT','Il-Munxar'),
	('MT-37','37','MLT','In-Nadur'),
	('MT-38','38','MLT','In-Naxxar'),
	('MT-39','39','MLT','Paola'),
	('MT-40','40','MLT','Pembroke'),
	('MT-41','41','MLT','Tal-Pietà'),
	('MT-42','42','MLT','Il-Qala'),
	('MT-43','43','MLT','Qormi'),
	('MT-44','44','MLT','Il-Qrendi'),
	('MT-45','45','MLT','Ir-Rabat'),
	('MT-46','46','MLT','Victoria'),
	('MT-47','47','MLT','Safi'),
	('MT-48','48','MLT','Saint John'),
	('MT-49','49','MLT','Saint Julian's'),
	('MT-50','50','MLT','Saint Lawrence'),
	('MT-51','51','MLT','Saint Lucia'),
	('MT-52','52','MLT','Saint Paul’s Bay'),
	('MT-53','53','MLT','Saint Venera'),
	('MT-54','54','MLT','Sannat'),
	('MT-55','55','MLT','Is-Siġġiewi'),
	('MT-56','56','MLT','Tas-Sliema'),
	('MT-57','57','MLT','Is-Swieqi'),
	('MT-58','58','MLT','Tarxien'),
	('MT-59','59','MLT','Ta’ Xbiex'),
	('MT-60','60','MLT','Il-Belt Valletta'),
	('MT-61','61','MLT','Ix-Xagħra'),
	('MT-62','62','MLT','Ix-Xewkija'),
	('MT-63','63','MLT','Ix-Xgħajra'),
	('MT-64','64','MLT','Ħaż-Żabbar'),
	('MT-65','65','MLT','Ħaż-Żebbuġ'),
	('MT-66','66','MLT','Iż-Żebbuġ'),
	('MT-67','67','MLT','Iż-Żejtun'),
	('MT-68','68','MLT','Iż-Żurrieq'),
	('MU-BR','BR','MUS','Beau Bassin-Rose Hill'),
	('MU-CU','CU','MUS','Curepipe'),
	('MU-PL','PL','MUS','Port Louis'),
	('MU-QB','QB','MUS','Quatre Bornes'),
	('MU-VP','VP','MUS','Vacoas-Phoenix'),
	('MU-BL','BL','MUS','Black River'),
	('MU-FL','FL','MUS','Flacq'),
	('MU-GP','GP','MUS','Grand Port'),
	('MU-MO','MO','MUS','Moka'),
	('MU-PA','PA','MUS','Pamplemousses'),
	('MU-PW','PW','MUS','Plaines Wilhems'),
	('MU-RR','RR','MUS','Rivière du Rempart'),
	('MU-SA','SA','MUS','Savanne'),
	('MU-AG','AG','MUS','Agalega Islands'),
	('MU-CC','CC','MUS','Cargados Carajos Shoals [Saint Brandon Islands]'),
	('MU-RO','RO','MUS','Rodrigues Island'),
	('MV-MLE','MLE','MDV','Male'),
	('MV-02','02','MDV','Alif'),
	('MV-20','20','MDV','Baa'),
	('MV-17','17','MDV','Dhaalu'),
	('MV-14','14','MDV','Faafu'),
	('MV-27','27','MDV','Gaaf Alif'),
	('MV-28','28','MDV','Gaafu Dhaalu'),
	('MV-29','29','MDV','Gnaviyani'),
	('MV-07','07','MDV','Haa Alif'),
	('MV-23','23','MDV','Haa Dhaalu'),
	('MV-26','26','MDV','Kaafu'),
	('MV-05','05','MDV','Laamu'),
	('MV-03','03','MDV','Lhaviyani'),
	('MV-12','12','MDV','Meemu'),
	('MV-25','25','MDV','Noonu'),
	('MV-13','13','MDV','Raa'),
	('MV-01','01','MDV','Seenu'),
	('MV-24','24','MDV','Shaviyani'),
	('MV-08','08','MDV','Thaa'),
	('MV-04','04','MDV','Vaavu'),
	('MW-C','C','MWI','Central'),
	('MW-DE','DE','MWI','Dedza'),
	('MW-DO','DO','MWI','Dowa'),
	('MW-KS','KS','MWI','Kasungu'),
	('MW-LI','LI','MWI','Lilongwe'),
	('MW-MC','MC','MWI','Mchinji'),
	('MW-NK','NK','MWI','Nkhotakota'),
	('MW-NU','NU','MWI','Ntcheu'),
	('MW-NI','NI','MWI','Ntchisi'),
	('MW-SA','SA','MWI','Salima'),
	('MW-N','N','MWI','Northern'),
	('MW-CT','CT','MWI','Chitipa'),
	('MW-KR','KR','MWI','Karonga'),
	('MW-MZ','MZ','MWI','Mzimba'),
	('MW-NB','NB','MWI','Nkhata Bay'),
	('MW-RU','RU','MWI','Rumphi'),
	('MW-S','S','MWI','Southern'),
	('MW-BL','BL','MWI','Blantyre'),
	('MW-CK','CK','MWI','Chikwawa'),
	('MW-CR','CR','MWI','Chiradzulu'),
	('MW-MH','MH','MWI','Machinga'),
	('MW-MG','MG','MWI','Mangochi'),
	('MW-MU','MU','MWI','Mulanje'),
	('MW-MW','MW','MWI','Mwanza'),
	('MW-NS','NS','MWI','Nsanje'),
	('MW-TH','TH','MWI','Thyolo'),
	('MW-ZO','ZO','MWI','Zomba'),
	('MX-DIF','DIF','MEX','Distrito Federal'),
	('MX-AGU','AGU','MEX','Aguascalientes'),
	('MX-BCN','BCN','MEX','Baja California'),
	('MX-BCS','BCS','MEX','Baja California Sur'),
	('MX-CAM','CAM','MEX','Campeche'),
	('MX-COA','COA','MEX','Coahuila'),
	('MX-COL','COL','MEX','Colima'),
	('MX-CHP','CHP','MEX','Chiapas'),
	('MX-CHH','CHH','MEX','Chihuahua'),
	('MX-DUR','DUR','MEX','Durango'),
	('MX-GRO','GRO','MEX','Guerrero'),
	('MX-GUA','GUA','MEX','Guanajuato'),
	('MX-HID','HID','MEX','Hidalgo'),
	('MX-JAL','JAL','MEX','Jalisco'),
	('MX-MEX','MEX','MEX','México'),
	('MX-MIC','MIC','MEX','Michoacán'),
	('MX-MOR','MOR','MEX','Morelos'),
	('MX-NAY','NAY','MEX','Nayarit'),
	('MX-NLE','NLE','MEX','Nuevo León'),
	('MX-OAX','OAX','MEX','Oaxaca'),
	('MX-PUE','PUE','MEX','Puebla'),
	('MX-QUE','QUE','MEX','Queretaro'),
	('MX-ROO','ROO','MEX','Quintana Roo'),
	('MX-SLP','SLP','MEX','San Luis Potosí'),
	('MX-SIN','SIN','MEX','Sinaloa'),
	('MX-SON','SON','MEX','Sonora'),
	('MX-TAB','TAB','MEX','Tabasco'),
	('MX-TAM','TAM','MEX','Tamaulipas'),
	('MX-TLA','TLA','MEX','Tlaxcala'),
	('MX-VER','VER','MEX','Veracruz'),
	('MX-YUC','YUC','MEX','Yucatán'),
	('MX-ZAC','ZAC','MEX','Zacatecas'),
	('MX-01','01','MEX','Aguascalientes'),
	('MX-02','02','MEX','Baja California'),
	('MX-03','03','MEX','Baja California Sur'),
	('MX-04','04','MEX','Campeche'),
	('MX-05','05','MEX','Coahuila de Zaragoza'),
	('MX-06','06','MEX','Colima'),
	('MX-07','07','MEX','Chiapas'),
	('MX-08','08','MEX','Chihuahua'),
	('MX-09','09','MEX','Distrito Federal'),
	('MX-10','10','MEX','Durango'),
	('MX-11','11','MEX','Guanajuato'),
	('MX-12','12','MEX','Guerrero'),
	('MX-13','13','MEX','Hidalgo'),
	('MX-14','14','MEX','Jalisco'),
	('MX-15','15','MEX','México'),
	('MX-16','16','MEX','Michoacán de Ocampo'),
	('MX-17','17','MEX','Morelos'),
	('MX-18','18','MEX','Nayarit'),
	('MX-19','19','MEX','Nuevo León'),
	('MX-20','20','MEX','Oaxaca'),
	('MX-21','21','MEX','Puebla'),
	('MX-22','22','MEX','Querétaro'),
	('MX-23','23','MEX','Quintana Roo'),
	('MX-24','24','MEX','San Luis Potosí'),
	('MX-25','25','MEX','Sinaloa'),
	('MX-26','26','MEX','Sonora'),
	('MX-27','27','MEX','Tabasco'),
	('MX-28','28','MEX','Tamaulipas'),
	('MX-29','29','MEX','Tlaxcala'),
	('MX-30','30','MEX','Veracruz de Ignacio de la Llave'),
	('MX-31','31','MEX','Yucatán'),
	('MX-32','32','MEX','Zacatecas'),
	('MY-W','W','MYS','Wilayah Persekutuan Kuala Lumpur'),
	('MY-L','L','MYS','Wilayah Persekutuan Labuan'),
	('MY-J','J','MYS','Johor'),
	('MY-K','K','MYS','Kedah'),
	('MY-D','D','MYS','Kelantan'),
	('MY-M','M','MYS','Melaka'),
	('MY-N','N','MYS','Negeri Sembilan'),
	('MY-C','C','MYS','Pahang'),
	('MY-A','A','MYS','Perak'),
	('MY-R','R','MYS','Perlis'),
	('MY-P','P','MYS','Pulau Pinang'),
	('MY-SA','SA','MYS','Sabah'),
	('MY-SK','SK','MYS','Sarawak'),
	('MY-B','B','MYS','Selangor'),
	('MY-T','T','MYS','Terengganu'),
	('MY-JHR','JHR','MYS','Johor'),
	('MY-KDH','KDH','MYS','Kedah'),
	('MY-KTN','KTN','MYS','Kelantan'),
	('MY-KUL','KUL','MYS','Kuala Lumpur'),
	('MY-LBN','LBN','MYS','Labuan'),
	('MY-MLK','MLK','MYS','Melaka'),
	('MY-NSN','NSN','MYS','Negeri Sembilan'),
	('MY-PHG','PHG','MYS','Pahang'),
	('MY-PJY','PJY','MYS','Putrajaya'),
	('MY-PLS','PLS','MYS','Perlis'),
	('MY-PNG','PNG','MYS','Pulau Pinang'),
	('MY-PRK','PRK','MYS','Perak'),
	('MY-SBH','SBH','MYS','Sabah'),
	('MY-SGR','SGR','MYS','Selangor'),
	('MY-SRW','SRW','MYS','Sarawak'),
	('MY-TRG','TRG','MYS','Terengganu'),
	('MZ-MPM','MPM','MOZ','Maputo'),
	('MZ-P','P','MOZ','Cabo Delgado'),
	('MZ-G','G','MOZ','Gaza'),
	('MZ-I','I','MOZ','Inhambane'),
	('MZ-B','B','MOZ','Manica'),
	('MZ-L','L','MOZ','Maputo'),
	('MZ-N','N','MOZ','Nampula'),
	('MZ-A','A','MOZ','Niassa'),
	('MZ-S','S','MOZ','Sofala'),
	('MZ-T','T','MOZ','Tete'),
	('MZ-Q','Q','MOZ','Zambézia'),
	('NA-CA','CA','NAM','Caprivi'),
	('NA-ER','ER','NAM','Erongo'),
	('NA-HA','HA','NAM','Hardap'),
	('NA-KA','KA','NAM','Karas'),
	('NA-KH','KH','NAM','Khomas'),
	('NA-KU','KU','NAM','Kunene'),
	('NA-OW','OW','NAM','Ohangwena'),
	('NA-OK','OK','NAM','Okavango'),
	('NA-OH','OH','NAM','Omaheke'),
	('NA-OS','OS','NAM','Omusati'),
	('NA-ON','ON','NAM','Oshana'),
	('NA-OT','OT','NAM','Oshikoto'),
	('NA-OD','OD','NAM','Otjozondjupa'),
	('NC-NC','NC','NCL','New Caledonia'),
	('NC-01','01','NCL','Province Nord'),
	('NC-02','02','NCL','Province Sud'),
	('NC-03','03','NCL','Îles Loyauté'),
	('NE-8','8','NER','Niamey'),
	('NE-1','1','NER','Agadez'),
	('NE-2','2','NER','Diffa'),
	('NE-3','3','NER','Dosso'),
	('NE-4','4','NER','Maradi'),
	('NE-5','5','NER','Tahoua'),
	('NE-6','6','NER','Tillaberi'),
	('NE-7','7','NER','Zinder'),
	('NF-NF','NF','NFK','Norfolk Island'),
	('NG-FC','FC','NGA','Abuja Capital Territory'),
	('NG-AB','AB','NGA','Abia'),
	('NG-AD','AD','NGA','Adamawa'),
	('NG-AK','AK','NGA','Akwa Ibom'),
	('NG-AN','AN','NGA','Anambra'),
	('NG-BA','BA','NGA','Bauchi'),
	('NG-BE','BE','NGA','Benue'),
	('NG-BO','BO','NGA','Borno'),
	('NG-CR','CR','NGA','Cross River'),
	('NG-DE','DE','NGA','Delta'),
	('NG-ED','ED','NGA','Edo'),
	('NG-EN','EN','NGA','Enugu'),
	('NG-IM','IM','NGA','Imo'),
	('NG-JI','JI','NGA','Jigawa'),
	('NG-KD','KD','NGA','Kaduna'),
	('NG-KN','KN','NGA','Kano'),
	('NG-KT','KT','NGA','Katsina'),
	('NG-KE','KE','NGA','Kebbi'),
	('NG-KO','KO','NGA','Kogi'),
	('NG-KW','KW','NGA','Kwara'),
	('NG-LA','LA','NGA','Lagos'),
	('NG-NI','NI','NGA','Niger'),
	('NG-OG','OG','NGA','Ogun'),
	('NG-ON','ON','NGA','Ondo'),
	('NG-OS','OS','NGA','Osun'),
	('NG-OY','OY','NGA','Oyo'),
	('NG-PL','PL','NGA','Plateau'),
	('NG-RI','RI','NGA','Rivers'),
	('NG-SO','SO','NGA','Sokoto'),
	('NG-TA','TA','NGA','Taraba'),
	('NG-YO','YO','NGA','Yobe'),
	('NI-BO','BO','NIC','Boaco'),
	('NI-CA','CA','NIC','Carazo'),
	('NI-CI','CI','NIC','Chinandega'),
	('NI-CO','CO','NIC','Chontales'),
	('NI-ES','ES','NIC','Estelí'),
	('NI-GR','GR','NIC','Granada'),
	('NI-JI','JI','NIC','Jinotega'),
	('NI-LE','LE','NIC','León'),
	('NI-MD','MD','NIC','Madriz'),
	('NI-MN','MN','NIC','Manaqua'),
	('NI-MS','MS','NIC','Masaya'),
	('NI-MT','MT','NIC','Matagalpa'),
	('NI-NS','NS','NIC','Nueva Segovia'),
	('NI-SJ','SJ','NIC','Río San Juan'),
	('NI-RI','RI','NIC','Rivas'),
	('NI-ZE','ZE','NIC','Zelaya'),
	('NL-DR','DR','NLD','Drenthe'),
	('NL-FL','FL','NLD','Flevoland'),
	('NL-FR','FR','NLD','Friesland'),
	('NL-GE','GE','NLD','Gelderland'),
	('NL-GR','GR','NLD','Groningen'),
	('NL-LI','LI','NLD','Limburg'),
	('NL-NB','NB','NLD','Noord-Brabant'),
	('NL-NH','NH','NLD','Noord-Holland'),
	('NL-OV','OV','NLD','Overijssel'),
	('NL-UT','UT','NLD','Utrecht'),
	('NL-ZE','ZE','NLD','Zeeland'),
	('NL-ZH','ZH','NLD','Zuid-Holland'),
	('NL-01','01','NLD','Drenthe'),
	('NL-02','02','NLD','Friesland'),
	('NL-03','03','NLD','Gelderland'),
	('NL-04','04','NLD','Groningen'),
	('NL-05','05','NLD','Limburg'),
	('NL-06','06','NLD','Noord-Brabant'),
	('NL-07','07','NLD','Noord-Holland'),
	('NL-09','09','NLD','Utrecht'),
	('NL-10','10','NLD','Zeeland'),
	('NL-11','11','NLD','Zuid-Holland'),
	('NL-15','15','NLD','Overijssel'),
	('NL-16','16','NLD','Flevoland'),
	('NO-02','02','NOR','Akershus'),
	('NO-09','09','NOR','Aust-Agder'),
	('NO-06','06','NOR','Buskerud'),
	('NO-20','20','NOR','Finnmark'),
	('NO-04','04','NOR','Hedmark'),
	('NO-12','12','NOR','Hordaland'),
	('NO-15','15','NOR','Møre og Romsdal'),
	('NO-18','18','NOR','Nordland'),
	('NO-17','17','NOR','Nord-Trøndelag'),
	('NO-05','05','NOR','Oppland'),
	('NO-03','03','NOR','Oslo'),
	('NO-11','11','NOR','Rogaland'),
	('NO-14','14','NOR','Sogn og Fjordane'),
	('NO-16','16','NOR','Sør-Trøndelag'),
	('NO-08','08','NOR','Telemark'),
	('NO-19','19','NOR','Troms'),
	('NO-10','10','NOR','Vest-Agder'),
	('NO-07','07','NOR','Vestfold'),
	('NO-01','01','NOR','Østfold'),
	('NO-22','22','NOR','Jan Mayen (Arctic Region)'),
	('NO-21','21','NOR','Svalbard (Arctic Region)'),
	('NO-13','13','NOR','Østfold fylke'),
	('NP-1','1','NPL','Madhyamanchal'),
	('NP-BA','BA','NPL','Bagmati'),
	('NP-JA','JA','NPL','Janakpur'),
	('NP-NA','NA','NPL','Narayani'),
	('NP-2','2','NPL','Madhya Pashchimanchal'),
	('NP-BH','BH','NPL','Bheri'),
	('NP-KA','KA','NPL','Karnali'),
	('NP-RA','RA','NPL','Rapti'),
	('NP-3','3','NPL','Pashchimanchal'),
	('NP-DH','DH','NPL','Dhawalagiri'),
	('NP-GA','GA','NPL','Gandaki'),
	('NP-LU','LU','NPL','Lumbini'),
	('NP-4','4','NPL','Purwanchal'),
	('NP-KO','KO','NPL','Kosi [Koshi]'),
	('NP-ME','ME','NPL','Mechi'),
	('NP-SA','SA','NPL','Sagarmatha'),
	('NP-5','5','NPL','Sudur Pashchimanchal'),
	('NP-MA','MA','NPL','Mahakali'),
	('NP-SE','SE','NPL','Seti'),
	('NR-NR','NR','NRU','Nauru'),
	('NU-NU','NU','NIU','Niue'),
	('NZ-N','N','NZL','North Island'),
	('NZ-AUK','AUK','NZL','Auckland'),
	('NZ-BOP','BOP','NZL','Bay of Plenty'),
	('NZ-GIS','GIS','NZL','Gisborne'),
	('NZ-HKB','HKB','NZL','Hawkes's Bay'),
	('NZ-MWT','MWT','NZL','Manawatu-Wanganui'),
	('NZ-NTL','NTL','NZL','Northland'),
	('NZ-TKI','TKI','NZL','Taranaki'),
	('NZ-WKO','WKO','NZL','Waikato'),
	('NZ-WGN','WGN','NZL','Wellington'),
	('NZ-S','S','NZL','South Island'),
	('NZ-CAN','CAN','NZL','Canterbury'),
	('NZ-MBH','MBH','NZL','Marlborough'),
	('NZ-NSN','NSN','NZL','Nelson'),
	('NZ-OTA','OTA','NZL','Otago'),
	('NZ-STL','STL','NZL','Southland'),
	('NZ-TAS','TAS','NZL','Tasman'),
	('NZ-WTC','WTC','NZL','West Coast'),
	('NZ-E7','E7','NZL','Auckland'),
	('NZ-E8','E8','NZL','Bay of Plenty'),
	('NZ-E9','E9','NZL','Canterbury'),
	('NZ-F1','F1','NZL','Gisborne'),
	('NZ-F2','F2','NZL','Hawke's Bay'),
	('NZ-F3','F3','NZL','Manawatu-Wanganui'),
	('NZ-F4','F4','NZL','Marlborough'),
	('NZ-F5','F5','NZL','Nelson'),
	('NZ-F6','F6','NZL','Northland'),
	('NZ-F7','F7','NZL','Otago'),
	('NZ-F8','F8','NZL','Southland'),
	('NZ-F9','F9','NZL','Taranaki'),
	('NZ-G1','G1','NZL','Waikato'),
	('NZ-G2','G2','NZL','Wellington'),
	('NZ-G3','G3','NZL','West Coast'),
	('NZ-','','NZL',''),
	('OM-DA','DA','OMN','Ad Dākhilīyah'),
	('OM-BA','BA','OMN','Al Bāţinah'),
	('OM-JA','JA','OMN','Al Janūbīyah [Zufār]'),
	('OM-WU','WU','OMN','Al Wusţā'),
	('OM-SH','SH','OMN','Ash Sharqīyah'),
	('OM-ZA','ZA','OMN','Az Zāhirah'),
	('OM-MA','MA','OMN','Masqaţ'),
	('OM-MU','MU','OMN','Musandam'),
	('YT-YT','YT','MYT','Mayotte'),
	('YT-00','00','MYT','Mayotte (general)'),
	('YT-97601','97601','MYT','Acoua'),
	('YT-97602','97602','MYT','Bandraboua'),
	('YT-97603','97603','MYT','Bandrele'),
	('YT-97604','97604','MYT','Bouéni'),
	('YT-97605','97605','MYT','Chiconi'),
	('YT-97606','97606','MYT','Chirongui'),
	('YT-97607','97607','MYT','Dembeni'),
	('YT-97608','97608','MYT','Dzaoudzi'),
	('YT-97609','97609','MYT','Kani-Kéli'),
	('YT-97610','97610','MYT','Koungou'),
	('YT-97611','97611','MYT','Mamoudzou'),
	('YT-97612','97612','MYT','Mtsamboro'),
	('YT-97613','97613','MYT','M'Tsangamouji'),
	('YT-97614','97614','MYT','Ouangani'),
	('YT-97615','97615','MYT','Pamandzi'),
	('YT-97616','97616','MYT','Sada'),
	('YT-97617','97617','MYT','Tsingoni');
COMMIT;
ANALYZE;
