BEGIN;
INSERT INTO regions (iso3, iso2, country, name) VALUES
	('GA-1','1','GAB','Estuaire'),
	('GA-2','2','GAB','Haut-Ogooué'),
	('GA-3','3','GAB','Moyen-Ogooué'),
	('GA-4','4','GAB','Ngounié'),
	('GA-5','5','GAB','Nyanga'),
	('GA-6','6','GAB','Ogooué-Ivindo'),
	('GA-7','7','GAB','Ogooué-Lolo'),
	('GA-8','8','GAB','Ogooué-Maritime'),
	('GA-9','9','GAB','Woleu-Ntem'),
	('GB-CHA','CHA','GBR','Channel Islands'),
	('GB-GSY','GSY','GBR','Guernsey (Guernesey)'),
	('GB-JSY','JSY','GBR','Jersey'),
	('GB-ENG','ENG','GBR','England'),
	('GB-BDG','BDG','GBR','Barking And Dagenham'),
	('GB-BNE','BNE','GBR','Barnet'),
	('GB-BNS','BNS','GBR','Barnsley'),
	('GB-BAS','BAS','GBR','Bath And North East Somerset'),
	('GB-BDF','BDF','GBR','Bedfordshire'),
	('GB-BEX','BEX','GBR','Bexley'),
	('GB-BIR','BIR','GBR','Birmingham (City Of)'),
	('GB-BBD','BBD','GBR','Blackburn With Darwen'),
	('GB-BPL','BPL','GBR','Blackpool'),
	('GB-BOL','BOL','GBR','Bolton'),
	('GB-BMH','BMH','GBR','Bournemouth'),
	('GB-BRC','BRC','GBR','Bracknell Forest'),
	('GB-BRD','BRD','GBR','Bradford (City Of)'),
	('GB-BEN','BEN','GBR','Brent'),
	('GB-BNH','BNH','GBR','Brighton And Hove'),
	('GB-BST','BST','GBR','Bristol, City Of'),
	('GB-BRY','BRY','GBR','Bromley'),
	('GB-BKM','BKM','GBR','Buckinghamshire'),
	('GB-BUR','BUR','GBR','Bury'),
	('GB-CLD','CLD','GBR','Calderdale'),
	('GB-CAM','CAM','GBR','Cambridgeshire'),
	('GB-CMD','CMD','GBR','Camden'),
	('GB-CHS','CHS','GBR','Cheshire'),
	('GB-CON','CON','GBR','Cornwall'),
	('GB-COV','COV','GBR','Coventry (City Of)'),
	('GB-CRY','CRY','GBR','Croydon'),
	('GB-CMA','CMA','GBR','Cumbria'),
	('GB-DAL','DAL','GBR','Darlington'),
	('GB-DER','DER','GBR','Derby (City Of)'),
	('GB-DBY','DBY','GBR','Derbyshire'),
	('GB-DEV','DEV','GBR','Devon'),
	('GB-DNC','DNC','GBR','Doncaster'),
	('GB-DOR','DOR','GBR','Dorset'),
	('GB-DUD','DUD','GBR','Dudley'),
	('GB-DUR','DUR','GBR','Durharn'),
	('GB-EAL','EAL','GBR','Ealing'),
	('GB-ERY','ERY','GBR','East Riding Of Yorkshire'),
	('GB-ESX','ESX','GBR','East Sussex'),
	('GB-ENF','ENF','GBR','Enfield'),
	('GB-ESS','ESS','GBR','Essex'),
	('GB-GAT','GAT','GBR','Gateshead'),
	('GB-GLS','GLS','GBR','Gloucestershire'),
	('GB-GRE','GRE','GBR','Greenwich'),
	('GB-HCK','HCK','GBR','Hackney'),
	('GB-HAL','HAL','GBR','Haiton'),
	('GB-HMF','HMF','GBR','Hammersmith And Fulham'),
	('GB-HAM','HAM','GBR','Hampshire'),
	('GB-HRY','HRY','GBR','Haringey'),
	('GB-HRW','HRW','GBR','Harrow'),
	('GB-HPL','HPL','GBR','Hartlepool'),
	('GB-HAV','HAV','GBR','Havering'),
	('GB-HEF','HEF','GBR','Herefordshire, County Of'),
	('GB-HRT','HRT','GBR','Hertfordshire'),
	('GB-HIL','HIL','GBR','Hillingdon'),
	('GB-HNS','HNS','GBR','Hounslow'),
	('GB-IOW','IOW','GBR','Isle Of Wight'),
	('GB-IOS','IOS','GBR','Isles Of Scilly'),
	('GB-ISL','ISL','GBR','Islington'),
	('GB-KEC','KEC','GBR','Kensington And Chelsea'),
	('GB-KEN','KEN','GBR','Kent'),
	('GB-KHL','KHL','GBR','Kingston Upon Hull, City Of'),
	('GB-KTT','KTT','GBR','Kingston Upon Thames'),
	('GB-KIR','KIR','GBR','Kirklees'),
	('GB-KWL','KWL','GBR','Knowsley'),
	('GB-LBH','LBH','GBR','Lambeth'),
	('GB-LAN','LAN','GBR','Lancashire'),
	('GB-LDS','LDS','GBR','Leeds (City Of)'),
	('GB-LCE','LCE','GBR','Leitester (City Of)'),
	('GB-LEC','LEC','GBR','Leicestershire'),
	('GB-LEW','LEW','GBR','Lewisham'),
	('GB-LIN','LIN','GBR','Lincolnshire'),
	('GB-LIV','LIV','GBR','Liverpool (City Of)'),
	('GB-LND','LND','GBR','London, City Of'),
	('GB-LUT','LUT','GBR','Luton'),
	('GB-MAN','MAN','GBR','Manchester (City Of)'),
	('GB-MDW','MDW','GBR','Medway'),
	('GB-MRT','MRT','GBR','Merton'),
	('GB-MDB','MDB','GBR','Middlesbrough'),
	('GB-MIK','MIK','GBR','Milton Keynes'),
	('GB-NET','NET','GBR','Newcastle Upon Tyne (City Of)'),
	('GB-NWM','NWM','GBR','Newham'),
	('GB-NFK','NFK','GBR','Norfolk'),
	('GB-NEL','NEL','GBR','North East Lincolnshire'),
	('GB-NLN','NLN','GBR','North Lincolnshire'),
	('GB-NSM','NSM','GBR','North Somerset'),
	('GB-NTY','NTY','GBR','North Tyneside'),
	('GB-NYK','NYK','GBR','North Yorkshire'),
	('GB-NTH','NTH','GBR','Northamptonshire'),
	('GB-NBL','NBL','GBR','Northumberland'),
	('GB-NGM','NGM','GBR','Nottingham (City Of)'),
	('GB-NTT','NTT','GBR','Nottinghamshire'),
	('GB-OLD','OLD','GBR','Oldham'),
	('GB-OXF','OXF','GBR','Oxfordshire'),
	('GB-PTE','PTE','GBR','Peterborough'),
	('GB-PLY','PLY','GBR','Plymouth (City Of)'),
	('GB-POL','POL','GBR','Poole'),
	('GB-POR','POR','GBR','Portsmouth (City Of)'),
	('GB-RDG','RDG','GBR','Reading'),
	('GB-RDB','RDB','GBR','Redbridge'),
	('GB-RCC','RCC','GBR','Redcar And Cleveland'),
	('GB-RIC','RIC','GBR','Richmond Upon Thames'),
	('GB-RCH','RCH','GBR','Rochdale'),
	('GB-ROT','ROT','GBR','Rotherharn'),
	('GB-RUT','RUT','GBR','Rutland'),
	('GB-SHN','SHN','GBR','St. Helens'),
	('GB-SLF','SLF','GBR','Salford (City Of)'),
	('GB-SAW','SAW','GBR','Sandweil'),
	('GB-SFT','SFT','GBR','Sefton'),
	('GB-SHF','SHF','GBR','Sheffield (City Of)'),
	('GB-SHR','SHR','GBR','Shropshire'),
	('GB-SLG','SLG','GBR','Slough'),
	('GB-SOL','SOL','GBR','Solihull'),
	('GB-SOM','SOM','GBR','Somerset'),
	('GB-SGC','SGC','GBR','South Gloucestershire'),
	('GB-STY','STY','GBR','South Tyneside'),
	('GB-STH','STH','GBR','Southampton (City Of)'),
	('GB-SOS','SOS','GBR','Southend-On-Sea'),
	('GB-SWK','SWK','GBR','Southwark'),
	('GB-STS','STS','GBR','Staffordshire'),
	('GB-SKP','SKP','GBR','Stockport'),
	('GB-STT','STT','GBR','Stockton-On-Tees'),
	('GB-STE','STE','GBR','Stoke-On-Trent (City Of)'),
	('GB-SFK','SFK','GBR','Suffolk'),
	('GB-SND','SND','GBR','Sunderland (City Of)'),
	('GB-SRY','SRY','GBR','Surrey'),
	('GB-STN','STN','GBR','Sutton'),
	('GB-SWD','SWD','GBR','Swindon'),
	('GB-TAM','TAM','GBR','Tameside'),
	('GB-TFW','TFW','GBR','Telford And Wrekin'),
	('GB-THR','THR','GBR','Thurrock'),
	('GB-TOB','TOB','GBR','Torbay'),
	('GB-TWH','TWH','GBR','Tower Hamlets'),
	('GB-TRF','TRF','GBR','Trafford'),
	('GB-WKF','WKF','GBR','Wakefield (City Of)'),
	('GB-WLL','WLL','GBR','Walsall'),
	('GB-WFT','WFT','GBR','Waltham Forest'),
	('GB-WND','WND','GBR','Wandsworth'),
	('GB-WRT','WRT','GBR','Warrington'),
	('GB-WAR','WAR','GBR','Warwickshire'),
	('GB-WBK','WBK','GBR','West Berkshire'),
	('GB-WSX','WSX','GBR','West Sussex'),
	('GB-WSM','WSM','GBR','Westminster (City Of)'),
	('GB-WGN','WGN','GBR','Wigan'),
	('GB-WIL','WIL','GBR','Wiltshire'),
	('GB-WNM','WNM','GBR','Windsor And Maidenhead'),
	('GB-WRL','WRL','GBR','Wirral'),
	('GB-WOK','WOK','GBR','Wokingham'),
	('GB-WLV','WLV','GBR','Wolverhampton'),
	('GB-WOR','WOR','GBR','Worcestershire'),
	('GB-YOR','YOR','GBR','York (City Of)'),
	('GB-IOM','IOM','GBR','Isle Of Man'),
	('GB-NIR','NIR','GBR','Northern Ireland'),
	('GB-ANT','ANT','GBR','Antrim'),
	('GB-ARD','ARD','GBR','Ards'),
	('GB-ARM','ARM','GBR','Armagh'),
	('GB-BLA','BLA','GBR','Ballymena'),
	('GB-BLY','BLY','GBR','Ballymoney'),
	('GB-BNB','BNB','GBR','Banbridge'),
	('GB-BFS','BFS','GBR','Belfast (City Of)'),
	('GB-CKF','CKF','GBR','Carrickfergus'),
	('GB-CSR','CSR','GBR','Castlereagh'),
	('GB-CLR','CLR','GBR','Coleraine'),
	('GB-CKT','CKT','GBR','Cookstown'),
	('GB-CGV','CGV','GBR','Craigavon'),
	('GB-DRY','DRY','GBR','Derry (City Of)'),
	('GB-DOW','DOW','GBR','Down'),
	('GB-DGN','DGN','GBR','Dungannon'),
	('GB-FER','FER','GBR','Fermanagh'),
	('GB-LRN','LRN','GBR','Larne'),
	('GB-LMV','LMV','GBR','Limavady'),
	('GB-LSB','LSB','GBR','Lisburn'),
	('GB-MFT','MFT','GBR','Magherafelt'),
	('GB-MYL','MYL','GBR','Moyle'),
	('GB-NYM','NYM','GBR','Newry And Mourne'),
	('GB-NTA','NTA','GBR','Newtownabbey'),
	('GB-NDN','NDN','GBR','North Down'),
	('GB-OMH','OMH','GBR','Omagh'),
	('GB-STB','STB','GBR','Strabane'),
	('GB-SCT','SCT','GBR','Scotland'),
	('GB-ABE','ABE','GBR','Aberdeen City'),
	('GB-ABD','ABD','GBR','Aberdeenshire'),
	('GB-ANS','ANS','GBR','Angus'),
	('GB-AGB','AGB','GBR','Argyll And Bute'),
	('GB-CLK','CLK','GBR','Clackmannanshire'),
	('GB-DGY','DGY','GBR','Dumfries And Galloway'),
	('GB-DND','DND','GBR','Dundee City'),
	('GB-EAY','EAY','GBR','East Ayrshire'),
	('GB-EDU','EDU','GBR','East Dunbartonshire'),
	('GB-ELN','ELN','GBR','East Lothian'),
	('GB-ERW','ERW','GBR','East Renfrewshire'),
	('GB-EDH','EDH','GBR','Edinburgh, City Of'),
	('GB-ELS','ELS','GBR','Eilean Siar'),
	('GB-FAL','FAL','GBR','Falkirk'),
	('GB-FIF','FIF','GBR','Fife'),
	('GB-GLG','GLG','GBR','Glasgow City'),
	('GB-HLD','HLD','GBR','Highland'),
	('GB-IVC','IVC','GBR','Inverclyde'),
	('GB-MLN','MLN','GBR','Midlothian'),
	('GB-MRY','MRY','GBR','Moray'),
	('GB-NAY','NAY','GBR','North Ayrshire'),
	('GB-NLK','NLK','GBR','North Lanarkshire'),
	('GB-ORK','ORK','GBR','Orkney Islands'),
	('GB-PKN','PKN','GBR','Perth And Kinross'),
	('GB-RFW','RFW','GBR','Renfrewshire'),
	('GB-SCB','SCB','GBR','Scottish Borders, The'),
	('GB-ZET','ZET','GBR','Shetland Islands'),
	('GB-SAY','SAY','GBR','South Ayrshire'),
	('GB-SLK','SLK','GBR','South Lanarkshire'),
	('GB-STG','STG','GBR','Stirling'),
	('GB-WDU','WDU','GBR','West Dunbartonshire'),
	('GB-WLN','WLN','GBR','West Lothian'),
	('GB-WLS','WLS','GBR','Wales (Cymru)'),
	('GB-BGW','BGW','GBR','Blaenau Gwent'),
	('GB-BGE','BGE','GBR','Bridgend (Pen-Y-Bont Ar Ogwr GB-POG)'),
	('GB-CAY','CAY','GBR','Caerphilly (Caerffili GB-CAF)'),
	('GB-CRF','CRF','GBR','Cardiff (City Of) (Caerdydd GB-CRD)'),
	('GB-CMN','CMN','GBR','Carmarthenshire (Sir Gaerfyrddin GB-GFY)'),
	('GB-CGN','CGN','GBR','Ceredigion (Sir Ceredigion)'),
	('GB-CWY','CWY','GBR','Conwy'),
	('GB-DEN','DEN','GBR','Denbighshire (Sir Ddinbych GB-DDB)'),
	('GB-FLN','FLN','GBR','Flintshire (Sir Y Fflint GB-FFL)'),
	('GB-GWN','GWN','GBR','Gwynedd'),
	('GB-AGY','AGY','GBR','Isle Of Anglesey (Sir Ynys Man GB-YNM)'),
	('GB-MTY','MTY','GBR','Merthyr Tydfil (Merthyr Tudful GB-MTU)'),
	('GB-MON','MON','GBR','Monmouthshire (Sir Fynwy GB-FYN)'),
	('GB-NTL','NTL','GBR','Neath Port Talbot (Castell-Nedd Port Talbot GB-CTL)'),
	('GB-NWP','NWP','GBR','Newport (Casnewydd GB-CNW)'),
	('GB-PEM','PEM','GBR','Pembrokeshire (Sir Benfro CB-BNF)'),
	('GB-POW','POW','GBR','Powys'),
	('GB-RCT','RCT','GBR','Rhondda, Cynon, Taff (Rhondda, Cynon, Taf)'),
	('GB-SWA','SWA','GBR','Swansea (City Of) (Abertawe GB-ATA)'),
	('GB-TOF','TOF','GBR','Torfaen (Tor-Faen)'),
	('GB-VGL','VGL','GBR','Vale Of Glamorgan, The (Bro Morgannwg GB-BMG)'),
	('GB-WRX','WRX','GBR','Wrexham (Wrecsam GB-WRC)'),
	('GB-','','GBR',''),
	('GD-GD','GD','GRD','Grenada'),
	('GE-AB','AB','GEO','Ap''Khazet''Is Avtonomiuri Respublika (Abkhazia)'),
	('GE-AJ','AJ','GEO','Acharis Avtonomiuri Respublika (Ajaria)'),
	('GE-BUS','BUS','GEO','Bat''Umi'),
	('GE-CHI','CHI','GEO','Chiat''Ura'),
	('GE-GAG','GAG','GEO','Gagra'),
	('GE-GOR','GOR','GEO','Gori'),
	('GE-KUT','KUT','GEO','K''Ut''Aisi'),
	('GE-PTI','PTI','GEO','P''Ot''I'),
	('GE-RUS','RUS','GEO','Rust''Avi'),
	('GE-SUI','SUI','GEO','Sokhumi'),
	('GE-TBS','TBS','GEO','T''Bilisi'),
	('GE-TQI','TQI','GEO','Tqibuli'),
	('GE-TQV','TQV','GEO','Tqvarch''Eli'),
	('GE-TSQ','TSQ','GEO','Tsqalmbo'),
	('GE-ZUG','ZUG','GEO','Zugdidi'),
	('GE-01','01','GEO','Abashis Raioni'),
	('GE-02','02','GEO','Adigenis Raioni'),
	('GE-03','03','GEO','Akhalgoris Raioni'),
	('GE-04','04','GEO','Akhalk''Alak''Is Raioni'),
	('GE-05','05','GEO','Akhalts''Ikhis Raioni'),
	('GE-06','06','GEO','Akhmetis Raioni'),
	('GE-07','07','GEO','Ambrolauris Raioni'),
	('GE-08','08','GEO','Aspindzis Raioni'),
	('GE-09','09','GEO','Baghdat''Is Raioni'),
	('GE-10','10','GEO','Bolnisis Raioni'),
	('GE-11','11','GEO','Borjomis Raioni'),
	('GE-12','12','GEO','Ch''Khorotsqus Raioni'),
	('GE-13','13','GEO','Ch''Okhatauris Raioni'),
	('GE-14','14','GEO','Dedop''Listsqaros Raioni'),
	('GE-15','15','GEO','Dmanisis Raioni'),
	('GE-16','16','GEO','Dushet''Is Raioni'),
	('GE-17','17','GEO','Galis Raioni'),
	('GE-18','18','GEO','Gardabnis Raioni'),
	('GE-19','19','GEO','Goris Raioni'),
	('GE-20','20','GEO','Gudaut''Is Raioni'),
	('GE-21','21','GEO','Gulrip''Shis Raioni'),
	('GE-22','22','GEO','Gurjaanis Raioni'),
	('GE-23','23','GEO','Javis Raioni'),
	('GE-24','24','GEO','K''Arelis Raioni'),
	('GE-25','25','GEO','Kaspis Raioni'),
	('GE-26','26','GEO','K''Edis Raioni'),
	('GE-27','27','GEO','Kharagaulis Raioni'),
	('GE-28','28','GEO','Khashuris Raioni'),
	('GE-29','29','GEO','Khelvach''Auris Raioni'),
	('GE-30','30','GEO','Khobis Raioni'),
	('GE-31','31','GEO','Khonis Raioni'),
	('GE-32','32','GEO','Khulos Raioni'),
	('GE-33','33','GEO','K''Obuletis Raioni'),
	('GE-34','34','GEO','Lagodekhis Raioni'),
	('GE-35','35','GEO','Lanch''Khut''Is Raioni'),
	('GE-36','36','GEO','Lentekhis Raioni'),
	('GE-37','37','GEO','Marneulis Raioni'),
	('GE-38','38','GEO','Martvilis Raioni'),
	('GE-39','39','GEO','Mestiis Raioni'),
	('GE-40','40','GEO','Mts''Khet''Is Raioni'),
	('GE-41','41','GEO','Ninotsmindis Raioni'),
	('GE-42','42','GEO','Och''Amch''Iris Raioni'),
	('GE-43','43','GEO','Onis Raioni'),
	('GE-44','44','GEO','Ozurget''Is Raioni'),
	('GE-45','45','GEO','Qazbegis Raioni'),
	('GE-46','46','GEO','Qvarlis Raioni'),
	('GE-47','47','GEO','Sach''Kheris Raioni'),
	('GE-48','48','GEO','Sagarejos Raioni'),
	('GE-49','49','GEO','Samtrediis Raioni'),
	('GE-50','50','GEO','Senakis Raioni'),
	('GE-51','51','GEO','Shuakhevis Raioni'),
	('GE-52','52','GEO','Sighnaghis Raioni'),
	('GE-53','53','GEO','Sokhumis Raioni'),
	('GE-54','54','GEO','T''Elavis Raioni'),
	('GE-55','55','GEO','T''Erjolis Raioni'),
	('GE-56','56','GEO','T''Et''Ritsqaros Raioni'),
	('GE-57','57','GEO','T''Ianet''Is Raioni'),
	('GE-58','58','GEO','Ts''Ageris Raioni'),
	('GE-59','59','GEO','Tsalenjikhis Raioni'),
	('GE-60','60','GEO','Tsalkis Raioni'),
	('GE-61','61','GEO','Vanis Raioni'),
	('GE-62','62','GEO','Zestap''Onis Raioni'),
	('GE-63','63','GEO','Zugdidis Raioni'),
	('GF-GF','GF','GUF','French Guiana'),
	('GG-','','GGY',''),
	('GH-AH','AH','GHA','Ashanti'),
	('GH-BA','BA','GHA','Brong-Ahafo'),
	('GH-CP','CP','GHA','Central'),
	('GH-EP','EP','GHA','Eastern'),
	('GH-AA','AA','GHA','Greater Accra'),
	('GH-NP','NP','GHA','Northern'),
	('GH-UE','UE','GHA','Upper East'),
	('GH-UW','UW','GHA','Upper West'),
	('GH-TV','TV','GHA','Volta'),
	('GH-WP','WP','GHA','Western'),
	('GI-GI','GI','GIB','Gibraltar'),
	('GL-GL','GL','GRL','Greenland'),
	('GL-','','GRL',''),
	('GM-B','B','GMB','Banjul'),
	('GM-L','L','GMB','Lower River'),
	('GM-M','M','GMB','MacCarthy Island'),
	('GM-N','N','GMB','North Bank'),
	('GM-U','U','GMB','Upper River'),
	('GM-W','W','GMB','Western'),
	('GN-B','B','GIN','Bake, Gouvernorat De'),
	('GN-BF','BF','GIN','Boffa'),
	('GN-BK','BK','GIN','Boké'),
	('GN-FR','FR','GIN','Fria'),
	('GN-GA','GA','GIN','Gaoual'),
	('GN-KD','KD','GIN','Kindia'),
	('GN-C','C','GIN','Conakry, Gouvernorat De'),
	('GN-F','F','GIN','Faranah, Gouvernorat De'),
	('GN-DB','DB','GIN','Dabola'),
	('GN-DI','DI','GIN','Dinguiraye'),
	('GN-FA','FA','GIN','Faranah'),
	('GN-KS','KS','GIN','Kissidougou'),
	('GN-K','K','GIN','Kankan, Gouvernorat De'),
	('GN-KA','KA','GIN','Kankan'),
	('GN-KE','KE','GIN','Kérouané'),
	('GN-KO','KO','GIN','Kouroussa'),
	('GN-MD','MD','GIN','Mandiana'),
	('GN-SI','SI','GIN','Siguiri'),
	('GN-D','D','GIN','Kindia, Gouvernorat De'),
	('GN-CO','CO','GIN','Coyah'),
	('GN-DU','DU','GIN','Dubréka'),
	('GN-FO','FO','GIN','Forécariah'),
	('GN-TE','TE','GIN','Télimélé'),
	('GN-L','L','GIN','Labé, Gouvernorat De'),
	('GN-KB','KB','GIN','Koubia'),
	('GN-LA','LA','GIN','Labé'),
	('GN-LE','LE','GIN','Lélouma'),
	('GN-ML','ML','GIN','Mali'),
	('GN-TO','TO','GIN','Tougué'),
	('GN-M','M','GIN','Mamou, Gouvernorat De'),
	('GN-DL','DL','GIN','Dalaba'),
	('GN-MM','MM','GIN','Mamou'),
	('GN-PI','PI','GIN','Pita'),
	('GN-N','N','GIN','Nzérékoré, Gouvernorat De'),
	('GN-BE','BE','GIN','Beyla'),
	('GN-GU','GU','GIN','Guékédou'),
	('GN-LO','LO','GIN','Lola'),
	('GN-MC','MC','GIN','Macenta'),
	('GN-NZ','NZ','GIN','Nzérékoré'),
	('GN-YO','YO','GIN','Yomou'),
	('GP-GP','GP','GLP','Guadeloupe'),
	('GQ-C','C','GNQ','Región Continental'),
	('GQ-CS','CS','GNQ','Centro Sur'),
	('GQ-KN','KN','GNQ','Kie-Ntem'),
	('GQ-LI','LI','GNQ','Litoral'),
	('GQ-WN','WN','GNQ','Wele-Nzás'),
	('GQ-I','I','GNQ','Región Insular'),
	('GQ-AN','AN','GNQ','Annobón'),
	('GQ-BN','BN','GNQ','Bioko Norte'),
	('GQ-BS','BS','GNQ','Bioko Sur'),
	('GR-I','I','GRC','Anatoliki Makedonia Kai Thraki'),
	('GR-52','52','GRC','Drama'),
	('GR-71','71','GRC','Evros'),
	('GR-55','55','GRC','Kavalla'),
	('GR-73','73','GRC','Rodopi'),
	('GR-72','72','GRC','Xanthi'),
	('GR-IX','IX','GRC','Attiki'),
	('GR-A1','A1','GRC','Attiki'),
	('GR-VII','VII','GRC','Dytiki Ellada'),
	('GR-13','13','GRC','Achaïa'),
	('GR-01','01','GRC','Aitolia-Akarnania'),
	('GR-14','14','GRC','Ileia'),
	('GR-III','III','GRC','Dytiki Makedonia'),
	('GR-63','63','GRC','Florina'),
	('GR-51','51','GRC','Grevena'),
	('GR-56','56','GRC','Kastoria'),
	('GR-58','58','GRC','Kozani'),
	('GR-VI','VI','GRC','Ionioi Nisoi'),
	('GR-23','23','GRC','Kefallinia'),
	('GR-22','22','GRC','Kerkyra'),
	('GR-24','24','GRC','Lefkas'),
	('GR-21','21','GRC','Zakynthos'),
	('GR-IV','IV','GRC','Ipeiros'),
	('GR-31','31','GRC','Arta'),
	('GR-33','33','GRC','Ioannina'),
	('GR-34','34','GRC','Preveza'),
	('GR-32','32','GRC','Thesprotia'),
	('GR-II','II','GRC','Kentriki Makedonia'),
	('GR-64','64','GRC','Chalkidiki'),
	('GR-53','53','GRC','Imathia'),
	('GR-57','57','GRC','Kilkis'),
	('GR-59','59','GRC','Pella'),
	('GR-61','61','GRC','Pieria'),
	('GR-62','62','GRC','Serrai'),
	('GR-54','54','GRC','Thessaloniki'),
	('GR-XIII','XIII','GRC','Kriti'),
	('GR-94','94','GRC','Chania'),
	('GR-91','91','GRC','Irakleion'),
	('GR-92','92','GRC','Lasithion'),
	('GR-93','93','GRC','Rethymnon'),
	('GR-XII','XII','GRC','Notio Aigaio'),
	('GR-81','81','GRC','Dodekanisos'),
	('GR-82','82','GRC','Kyklades'),
	('GR-X','X','GRC','Peloponnisos'),
	('GR-11','11','GRC','Argolis'),
	('GR-12','12','GRC','Arkadia'),
	('GR-15','15','GRC','Korinthia'),
	('GR-16','16','GRC','Lakonia'),
	('GR-17','17','GRC','Messinia'),
	('GR-VIII','VIII','GRC','Sterea Ellada'),
	('GR-05','05','GRC','Evrytania'),
	('GR-04','04','GRC','Evvoia'),
	('GR-07','07','GRC','Fokis'),
	('GR-06','06','GRC','Fthiotis'),
	('GR-03','03','GRC','Voiotia'),
	('GR-V','V','GRC','Thessalia'),
	('GR-41','41','GRC','Karditsa'),
	('GR-42','42','GRC','Larisa'),
	('GR-43','43','GRC','Magnisia'),
	('GR-44','44','GRC','Trikala'),
	('GR-XI','XI','GRC','Voreio Aigaio'),
	('GR-85','85','GRC','Chios'),
	('GR-83','83','GRC','Lesvos'),
	('GR-84','84','GRC','Samos'),
	('GT-AV','AV','GTM','Alta Verapaz'),
	('GT-BV','BV','GTM','Baja Verapaz'),
	('GT-CM','CM','GTM','Chimaltenango'),
	('GT-CQ','CQ','GTM','Chiquimula'),
	('GT-PR','PR','GTM','El Progreso'),
	('GT-ES','ES','GTM','Escuintla'),
	('GT-GU','GU','GTM','Guatemala'),
	('GT-HU','HU','GTM','Huehuetenango'),
	('GT-IZ','IZ','GTM','Izabal'),
	('GT-JA','JA','GTM','Jalapa'),
	('GT-JU','JU','GTM','Jutiapa'),
	('GT-PE','PE','GTM','Petén'),
	('GT-QZ','QZ','GTM','Quezaltenango'),
	('GT-QC','QC','GTM','Quiché'),
	('GT-RE','RE','GTM','Retalhuleu'),
	('GT-SA','SA','GTM','Sacatepéquez'),
	('GT-SM','SM','GTM','San Marcos'),
	('GT-SR','SR','GTM','Santa Rosa'),
	('GT-SO','SO','GTM','Sololá'),
	('GT-SU','SU','GTM','Suchitepéquez'),
	('GT-TO','TO','GTM','Totonicapán'),
	('GT-ZA','ZA','GTM','Zacapa'),
	('GT-01','01','GTM','DEPTO DE ALTA VERAPAZ'),
	('GT-02','02','GTM','DEPTO DE BAJA VERAPAZ'),
	('GT-03','03','GTM','DEPTO DE CHIMALTENANGO'),
	('GT-04','04','GTM','DEPTO DE CHIQUIMULA'),
	('GT-06','06','GTM','DEPTO DE ESCUINTLA'),
	('GT-07','07','GTM','Ciudad de Guatemala'),
	('GT-08','08','GTM','DEPTO DE HUEHUETENANGO'),
	('GT-09','09','GTM','DEPTO DE IZABAL'),
	('GT-10','10','GTM','DEPTO DE JALAPA'),
	('GT-11','11','GTM','DEPTO DE JUTIAPA'),
	('GT-12','12','GTM','DEPTO DE PETEN'),
	('GT-13','13','GTM','DEPTO DE QUETZALTENANGO'),
	('GT-14','14','GTM','DEPTO DEL QUICHE'),
	('GT-15','15','GTM','DEPTO DE RETALHULEU'),
	('GT-16','16','GTM','DEPTO DE SACATEPEQUEZ'),
	('GT-17','17','GTM','DEPTO DE SAN MARCOS'),
	('GT-18','18','GTM','DEPTO DE SANTA ROSA'),
	('GT-19','19','GTM','DEPTO DE SOLOLA'),
	('GT-20','20','GTM','DEPTO DE SUCHITEPEQUEZ'),
	('GT-21','21','GTM','DEPTO DE TOTONICAPAN'),
	('GT-22','22','GTM','DEPTO DE ZACAPA'),
	('GU-GU','GU','GUM','Guam'),
	('GU-66','66','GUM','Gu'),
	('GW-BS','BS','GNB','Bissau'),
	('GW-BA','BA','GNB','Bafatá'),
	('GW-BM','BM','GNB','Biombo'),
	('GW-BL','BL','GNB','Bolama'),
	('GW-CA','CA','GNB','Cacheu'),
	('GW-GA','GA','GNB','Gabú'),
	('GW-OI','OI','GNB','Oio'),
	('GW-QU','QU','GNB','Quinara'),
	('GY-BA','BA','GUY','Barima-Waini'),
	('GY-CU','CU','GUY','Cuyuni-Mazaruni'),
	('GY-DE','DE','GUY','Demerara-Mahaica'),
	('GY-EB','EB','GUY','East Berbice-Corentyne'),
	('GY-ES','ES','GUY','Essequibo Islands-West Demerara'),
	('GY-MA','MA','GUY','Mahaica-Berbice'),
	('GY-PM','PM','GUY','Pomeroon-Supenaam'),
	('GY-PT','PT','GUY','Potaro-Siparuni'),
	('GY-UD','UD','GUY','Upper Demerara-Berbice'),
	('GY-UT','UT','GUY','Upper Takutu-Upper Essequibo'),
	('HK-HK','HK','HKG','Hong Kong'),
	('HM-HM','HM','HMD','Heard & McDonald Islands'),
	('HN-AT','AT','HND','Atlántida'),
	('HN-CL','CL','HND','Colón'),
	('HN-CM','CM','HND','Comayagua'),
	('HN-CP','CP','HND','Copán'),
	('HN-CR','CR','HND','Cortés'),
	('HN-CH','CH','HND','Choluteca'),
	('HN-EP','EP','HND','El Paraíso'),
	('HN-FM','FM','HND','Francisco Morazán'),
	('HN-GD','GD','HND','Gracias A Dios'),
	('HN-IN','IN','HND','Intibucá'),
	('HN-IB','IB','HND','Islas De La Bahía'),
	('HN-LP','LP','HND','La Paz'),
	('HN-LE','LE','HND','Lempira'),
	('HN-OC','OC','HND','Ocotepeque'),
	('HN-OL','OL','HND','Olancho'),
	('HN-SB','SB','HND','Santa Bárbara'),
	('HN-VA','VA','HND','Valle'),
	('HN-YO','YO','HND','Yoro'),
	('HR-07','07','HRV','Bjelovarsko-Bilogorska Županija'),
	('HR-12','12','HRV','Brodsko-Posavska Županija'),
	('HR-19','19','HRV','Dubrovačko-Neretvanska Županija'),
	('HR-18','18','HRV','Istarska Županija'),
	('HR-04','04','HRV','Karlovačka Županija'),
	('HR-06','06','HRV','Koprivničkco-Križevačka Županija'),
	('HR-02','02','HRV','Krapinsko-Zagorska Županija'),
	('HR-09','09','HRV','Ličko-Senjska Županija'),
	('HR-20','20','HRV','Medjimurska Županija'),
	('HR-14','14','HRV','Osječko-Baranjska Županija'),
	('HR-11','11','HRV','Požeško-Slavonska Županija'),
	('HR-08','08','HRV','Primorsko-Goranska Županija'),
	('HR-03','03','HRV','Sisaško-Moslavačka Županija'),
	('HR-17','17','HRV','Splitsko-Dalmatinska Županija'),
	('HR-15','15','HRV','Šibensko-Kninska Županija'),
	('HR-05','05','HRV','Varaždinska Županija'),
	('HR-10','10','HRV','Virovitičko-Podravska Županija'),
	('HR-16','16','HRV','Vukovarsko-Srijemska Županija'),
	('HR-13','13','HRV','Zadarska Županija'),
	('HR-01','01','HRV','Zagrebačka Županija'),
	('HR-21','21','HRV','Grad Zagreb'),
	('HT-AR','AR','HTI','Artibonite'),
	('HT-CE','CE','HTI','Centre'),
	('HT-GA','GA','HTI','Grande-Anse'),
	('HT-ND','ND','HTI','Nord'),
	('HT-NE','NE','HTI','Nord-Est'),
	('HT-NO','NO','HTI','Nord-Ouest'),
	('HT-OU','OU','HTI','Ouest'),
	('HT-SD','SD','HTI','Sud'),
	('HT-SE','SE','HTI','Sud-Est'),
	('HU-BU','BU','HUN','Budapest'),
	('HU-BK','BK','HUN','Bács-Kiskun'),
	('HU-BA','BA','HUN','Baranya'),
	('HU-BE','BE','HUN','Békés'),
	('HU-BZ','BZ','HUN','Borsod-Abaúj-Zemplén'),
	('HU-CS','CS','HUN','Csongrád'),
	('HU-FE','FE','HUN','Fejér'),
	('HU-GS','GS','HUN','Gyór-Moson-Sopron'),
	('HU-HB','HB','HUN','Hajdú-Bihar'),
	('HU-HE','HE','HUN','Heves'),
	('HU-JN','JN','HUN','Jasz-Nagykun-Szolnok'),
	('HU-KE','KE','HUN','Komárom-Esztergom'),
	('HU-NO','NO','HUN','Nógrád'),
	('HU-PE','PE','HUN','Pest'),
	('HU-SO','SO','HUN','Somogy'),
	('HU-SZ','SZ','HUN','Szabolcs-Szatmár-Bereg'),
	('HU-TO','TO','HUN','Tolna'),
	('HU-VA','VA','HUN','Vas'),
	('HU-VE','VE','HUN','Veszprém'),
	('HU-ZA','ZA','HUN','Zala'),
	('HU-BC','BC','HUN','Békéscsaba'),
	('HU-DE','DE','HUN','Debrecen'),
	('HU-DU','DU','HUN','Dunaújváros'),
	('HU-EG','EG','HUN','Eger'),
	('HU-GY','GY','HUN','Gyór'),
	('HU-HV','HV','HUN','Hódmezóvásárhely'),
	('HU-KV','KV','HUN','Kaposvár'),
	('HU-KM','KM','HUN','Kecskemét'),
	('HU-MI','MI','HUN','Miskolc'),
	('HU-NK','NK','HUN','Nagykanizsa'),
	('HU-NY','NY','HUN','Nyíregyháza'),
	('HU-PS','PS','HUN','Pécs'),
	('HU-ST','ST','HUN','Salgótarján'),
	('HU-SN','SN','HUN','Sopron'),
	('HU-SD','SD','HUN','Szeged'),
	('HU-SF','SF','HUN','Székesfehérvár'),
	('HU-SS','SS','HUN','Szekszárd'),
	('HU-SK','SK','HUN','Szolnok'),
	('HU-SH','SH','HUN','Szombathely'),
	('HU-TB','TB','HUN','Tatabánya'),
	('HU-VM','VM','HUN','Veszprém'),
	('HU-ZE','ZE','HUN','Zalaegerszeg'),
	('ID-IJU','IJU','IDN','Irian Jaya'),
	('ID-IJ','IJ','IDN','Irian Jaya'),
	('ID-JWU','JWU','IDN','Jawa'),
	('ID-JB','JB','IDN','Jawa Barat'),
	('ID-JT','JT','IDN','Jawa Tengah'),
	('ID-JI','JI','IDN','Jawa Timur'),
	('ID-JK','JK','IDN','Jakarta Raya'),
	('ID-YO','YO','IDN','Yogyakarta'),
	('ID-KAU','KAU','IDN','Kalimantan'),
	('ID-KB','KB','IDN','Kalimantan Barat'),
	('ID-KS','KS','IDN','Kalimantan Selatan'),
	('ID-KT','KT','IDN','Kalimantan Tengah'),
	('ID-KI','KI','IDN','Kalimantan Timur'),
	('ID-MAU','MAU','IDN','Maluku'),
	('ID-MA','MA','IDN','Maluku'),
	('ID-NUU','NUU','IDN','Nusa Tenggara'),
	('ID-BA','BA','IDN','Bali'),
	('ID-NB','NB','IDN','Nusa Tenggara Barat'),
	('ID-NT','NT','IDN','Nusa Tenggara Timur'),
	('ID-TT','TT','IDN','Timor Timur'),
	('ID-SLU','SLU','IDN','Sulawesi'),
	('ID-SN','SN','IDN','Sulawesi Selatan'),
	('ID-ST','ST','IDN','Sulawesi Tengah'),
	('ID-SG','SG','IDN','Sulawesi Tenggara'),
	('ID-SA','SA','IDN','Sulawesi Utara'),
	('ID-SMU','SMU','IDN','Sumatera'),
	('ID-BE','BE','IDN','Bengkulu'),
	('ID-JA','JA','IDN','Jambi'),
	('ID-LA','LA','IDN','Lampung'),
	('ID-RI','RI','IDN','Riau'),
	('ID-SB','SB','IDN','Sumatera Barat'),
	('ID-SS','SS','IDN','Sumatera Selatan'),
	('ID-SU','SU','IDN','Sumatera Utara'),
	('ID-AC','AC','IDN','Aceh'),
	('IE-CP','CP','IRL','Connaught (Connacht)'),
	('IE-G','G','IRL','Galway (Gaillimh)'),
	('IE-LM','LM','IRL','Leitrim (Liatroim)'),
	('IE-MO','MO','IRL','Mayo (Maigh Eo)'),
	('IE-RN','RN','IRL','Roscommon (Ros Comáin)'),
	('IE-SO','SO','IRL','Sligo (Sligeach)'),
	('IE-LP','LP','IRL','Leinster (Laighin)'),
	('IE-CW','CW','IRL','Carlow (Ceatharlach)'),
	('IE-D','D','IRL','Dublin (Baile Átha Cliath)'),
	('IE-KE','KE','IRL','Kildare (Cill Dara)'),
	('IE-KK','KK','IRL','Kilkenny (Cill Chainnigh)'),
	('IE-LS','LS','IRL','Laois (Laois)'),
	('IE-LD','LD','IRL','Longford (An Longfort)'),
	('IE-LH','LH','IRL','Louth (Lú)'),
	('IE-MH','MH','IRL','Meath (An Mhí)'),
	('IE-OY','OY','IRL','Offaly (Uíbh Fhailí)'),
	('IE-WH','WH','IRL','Westmeath (An Iarmhí)'),
	('IE-WX','WX','IRL','Wexford (Loch Garman)'),
	('IE-WW','WW','IRL','Wicklow (Cill Mhantáin)'),
	('IE-M','M','IRL','Munster (An Mhumhain)'),
	('IE-UP','UP','IRL','Ulster (Ulaidh)'),
	('IE-CN','CN','IRL','Cavan (An Cabhán)'),
	('IE-DL','DL','IRL','Donegal (Dún Na NGall)'),
	('IE-MN','MN','IRL','Monaghan (Muineachán)'),
	('IE-','','IRL',''),
	('IL-D','D','ISR','HaDarom (El Janūbī)'),
	('IL-M','M','ISR','HaMerkaz (El Awsat)'),
	('IL-2','2','ISR','HaZafon (Esh Shamālī)'),
	('IL-HA','HA','ISR','Hefa (Heifā)'),
	('IL-TA','TA','ISR','Tel-Aviv (Tell Abīb)'),
	('IL-JM','JM','ISR','Yerushalayim (Al Quds)'),
	('IM-','','IMN',''),
	('IN-AP','AP','IND','Andhra Pradesh'),
	('IN-AR','AR','IND','Arunachal Pradesh'),
	('IN-AS','AS','IND','Assam'),
	('IN-BR','BR','IND','Bihar'),
	('IN-GA','GA','IND','Goa'),
	('IN-GJ','GJ','IND','Gujarat'),
	('IN-HR','HR','IND','Haryana'),
	('IN-HP','HP','IND','Himachal Pradesh'),
	('IN-JK','JK','IND','Jammu And Kashmir'),
	('IN-KA','KA','IND','Karnataka'),
	('IN-KL','KL','IND','Kerala'),
	('IN-MP','MP','IND','Madhya Pradesh'),
	('IN-MH','MH','IND','Maharashtra'),
	('IN-MN','MN','IND','Manipur'),
	('IN-ML','ML','IND','Meghalaya'),
	('IN-MZ','MZ','IND','Mizoram'),
	('IN-NL','NL','IND','Nagaland'),
	('IN-OR','OR','IND','Orissa'),
	('IN-PB','PB','IND','Punjab'),
	('IN-RJ','RJ','IND','Rajasthan'),
	('IN-SK','SK','IND','Sikkim'),
	('IN-TN','TN','IND','Tamil Nadu'),
	('IN-TR','TR','IND','Tripura'),
	('IN-UP','UP','IND','Uttar Pradesh'),
	('IN-WB','WB','IND','West Bengal'),
	('IN-AN','AN','IND','Andaman And Nicobar Islands'),
	('IN-CH','CH','IND','Chandigarh'),
	('IN-DN','DN','IND','Dadra And Nagar Haveli'),
	('IN-DD','DD','IND','Daman And Diu'),
	('IN-DL','DL','IND','Delhi'),
	('IN-LD','LD','IND','Lakshadweep'),
	('IN-PY','PY','IND','Pondicherry'),
	('IN-01','01','IND','Andaman & Nicobar Islands'),
	('IN-02','02','IND','Andhra Pradesh'),
	('IN-03','03','IND','Assam'),
	('IN-05','05','IND','Chandigarh'),
	('IN-06','06','IND','Dadra & Nagar Haveli'),
	('IN-07','07','IND','Delhi'),
	('IN-09','09','IND','Gujarat'),
	('IN-10','10','IND','Haryana'),
	('IN-11','11','IND','Himachal Pradesh'),
	('IN-12','12','IND','Jammu & Kashmir'),
	('IN-13','13','IND','Kerala'),
	('IN-14','14','IND','Lakshadweep'),
	('IN-16','16','IND','Maharashtra'),
	('IN-17','17','IND','Manipur'),
	('IN-18','18','IND','Meghalaya'),
	('IN-19','19','IND','Karnataka'),
	('IN-20','20','IND','Nagaland'),
	('IN-21','21','IND','Odisha'),
	('IN-22','22','IND','Pondicherry'),
	('IN-23','23','IND','Punjab'),
	('IN-24','24','IND','Rajasthan'),
	('IN-25','25','IND','Tamil Nadu'),
	('IN-26','26','IND','Tripura'),
	('IN-28','28','IND','West Bengal'),
	('IN-29','29','IND','Sikkim'),
	('IN-30','30','IND','Arunachal Pradesh'),
	('IN-31','31','IND','Mizoram'),
	('IN-32','32','IND','Daman & Diu'),
	('IN-33','33','IND','Goa'),
	('IN-34','34','IND','Bihar'),
	('IN-35','35','IND','Madhya Pradesh'),
	('IN-36','36','IND','Uttar Pradesh'),
	('IN-37','37','IND','Chattisgarh'),
	('IN-38','38','IND','Jharkhand'),
	('IN-39','39','IND','Uttarakhand'),
	('IN-40','40','IND','Telangana'),
	('IO-IO','IO','IOT','British Indian Ocean Territory'),
	('IQ-AN','AN','IRQ','Al Anbār'),
	('IQ-BA','BA','IRQ','Al Başrah'),
	('IQ-MU','MU','IRQ','Al Muthanná'),
	('IQ-QA','QA','IRQ','Al Qādisīyah'),
	('IQ-NA','NA','IRQ','An Najaf'),
	('IQ-AR','AR','IRQ','Arbīl'),
	('IQ-SU','SU','IRQ','As Sulaymānīyah'),
	('IQ-TS','TS','IRQ','At Ta''Mīm'),
	('IQ-BB','BB','IRQ','Bābil'),
	('IQ-BG','BG','IRQ','Baghdād'),
	('IQ-DA','DA','IRQ','Dahūk'),
	('IQ-DQ','DQ','IRQ','Dhī Qār'),
	('IQ-DI','DI','IRQ','Diyālá'),
	('IQ-KA','KA','IRQ','Karbalā'''),
	('IQ-MA','MA','IRQ','Maysān'),
	('IQ-NI','NI','IRQ','Nīnawá'),
	('IQ-SD','SD','IRQ','Şalāḩ Ad Dīn'),
	('IQ-WA','WA','IRQ','Wāsiţ'),
	('IR-03','03','IRN','Ardabīl'),
	('IR-02','02','IRN','Āzarbāyjān-E-Gharbī'),
	('IR-01','01','IRN','Āzarbāyjān-E-Sharqī'),
	('IR-06','06','IRN','Būshehr'),
	('IR-08','08','IRN','Chahār Maḩāll Vā Bakhtīārī'),
	('IR-04','04','IRN','Eşfahān'),
	('IR-14','14','IRN','Fārs'),
	('IR-19','19','IRN','Gīlān'),
	('IR-24','24','IRN','Hamadān'),
	('IR-23','23','IRN','Hormozgān'),
	('IR-05','05','IRN','Īlām'),
	('IR-15','15','IRN','Kermān'),
	('IR-17','17','IRN','Kermānshāhān'),
	('IR-09','09','IRN','Khorāsān'),
	('IR-10','10','IRN','Khūzestān'),
	('IR-18','18','IRN','Kohkīlūyeh Va Būyer Aḩmadī'),
	('IR-16','16','IRN','Kordestān'),
	('IR-20','20','IRN','Lorestān'),
	('IR-22','22','IRN','Markazī'),
	('IR-21','21','IRN','Māzandarān'),
	('IR-26','26','IRN','Qom'),
	('IR-12','12','IRN','Semnān'),
	('IR-13','13','IRN','Sīstān Va Balūchestān'),
	('IR-07','07','IRN','Tehrān'),
	('IR-25','25','IRN','Yazd'),
	('IR-11','11','IRN','Zanjān'),
	('IS-7','7','ISL','Austurland'),
	('IS-1','1','ISL','Höfudborgarsvædi Utan Reykjavíkur'),
	('IS-6','6','ISL','Nordurland Eystra'),
	('IS-5','5','ISL','Nordurland Vestra'),
	('IS-0','0','ISL','Reykjavīk'),
	('IS-8','8','ISL','Sudurland'),
	('IS-2','2','ISL','Sudurnes'),
	('IS-4','4','ISL','Vestfirdir'),
	('IS-3','3','ISL','Vesturland'),
	('IS-','','ISL',''),
	('IT-65','65','ITA','Abruzzo'),
	('IT-CH','CH','ITA','Chieti'),
	('IT-AQ','AQ','ITA','L''Aquila'),
	('IT-PE','PE','ITA','Pescara'),
	('IT-TE','TE','ITA','Teramo'),
	('IT-77','77','ITA','Basilicata'),
	('IT-MT','MT','ITA','Matera'),
	('IT-PZ','PZ','ITA','Potenza'),
	('IT-78','78','ITA','Calabria'),
	('IT-CZ','CZ','ITA','Catanzaro'),
	('IT-CS','CS','ITA','Cosenza'),
	('IT-KR','KR','ITA','Crotone'),
	('IT-RC','RC','ITA','Reggio Calabria'),
	('IT-W','W','ITA','Vibo Valentia'),
	('IT-72','72','ITA','Campania'),
	('IT-AV','AV','ITA','Avellino'),
	('IT-BN','BN','ITA','Benevento'),
	('IT-CE','CE','ITA','Caserta'),
	('IT-NA','NA','ITA','Napoli'),
	('IT-SA','SA','ITA','Salerno'),
	('IT-45','45','ITA','Emilia-Romagna'),
	('IT-BO','BO','ITA','Bologna'),
	('IT-FE','FE','ITA','Ferrara'),
	('IT-FO','FO','ITA','Forlì'),
	('IT-MO','MO','ITA','Modena'),
	('IT-PR','PR','ITA','Parma'),
	('IT-PC','PC','ITA','Piacenza'),
	('IT-RA','RA','ITA','Ravenna'),
	('IT-RE','RE','ITA','Reggio Emilia'),
	('IT-RN','RN','ITA','Rimini'),
	('IT-36','36','ITA','Friuli-Venezia Giulia'),
	('IT-GO','GO','ITA','Gorizia'),
	('IT-PN','PN','ITA','Pordenone'),
	('IT-TS','TS','ITA','Trieste'),
	('IT-UD','UD','ITA','Udine'),
	('IT-62','62','ITA','Lazio'),
	('IT-FR','FR','ITA','Frosinone'),
	('IT-LT','LT','ITA','Latina'),
	('IT-RI','RI','ITA','Rieti'),
	('IT-RM','RM','ITA','Roma'),
	('IT-VT','VT','ITA','Viterbo'),
	('IT-42','42','ITA','Liguria'),
	('IT-GE','GE','ITA','Genova'),
	('IT-IM','IM','ITA','Imperia'),
	('IT-SP','SP','ITA','La Spezia'),
	('IT-SV','SV','ITA','Savona'),
	('IT-25','25','ITA','Lombardia'),
	('IT-BG','BG','ITA','Bergamo'),
	('IT-BS','BS','ITA','Brescia'),
	('IT-CO','CO','ITA','Como'),
	('IT-CR','CR','ITA','Cremona'),
	('IT-LC','LC','ITA','Lecco'),
	('IT-LO','LO','ITA','Lodi'),
	('IT-MN','MN','ITA','Mantova'),
	('IT-MI','MI','ITA','Milano'),
	('IT-PV','PV','ITA','Pavia'),
	('IT-SO','SO','ITA','Sondrio'),
	('IT-VA','VA','ITA','Varese'),
	('IT-57','57','ITA','Marche'),
	('IT-AN','AN','ITA','Ancona'),
	('IT-AP','AP','ITA','Ascoli Piceno'),
	('IT-MC','MC','ITA','Macerata'),
	('IT-PS','PS','ITA','Pesaro'),
	('IT-67','67','ITA','Molise'),
	('IT-CB','CB','ITA','Campobasso'),
	('IT-IS','IS','ITA','Isernia'),
	('IT-21','21','ITA','Piemonte'),
	('IT-AL','AL','ITA','Alessandria'),
	('IT-AT','AT','ITA','Asti'),
	('IT-BI','BI','ITA','Biella'),
	('IT-CN','CN','ITA','Cuneo'),
	('IT-NO','NO','ITA','Novara'),
	('IT-TO','TO','ITA','Torino'),
	('IT-VB','VB','ITA','Verbano-Cusio-Ossola'),
	('IT-VC','VC','ITA','Vercelli'),
	('IT-75','75','ITA','Puglia'),
	('IT-BA','BA','ITA','Bari'),
	('IT-BR','BR','ITA','Brindisi'),
	('IT-FG','FG','ITA','Foggia'),
	('IT-LE','LE','ITA','Lecce'),
	('IT-TA','TA','ITA','Taranto'),
	('IT-88','88','ITA','Sardegna'),
	('IT-CA','CA','ITA','Cagliari'),
	('IT-NU','NU','ITA','Nuoro'),
	('IT-OR','OR','ITA','Oristano'),
	('IT-SS','SS','ITA','Sassari'),
	('IT-82','82','ITA','Sicilia'),
	('IT-AG','AG','ITA','Agrigento'),
	('IT-CL','CL','ITA','Caltanissetta'),
	('IT-CT','CT','ITA','Catania'),
	('IT-EN','EN','ITA','Enna'),
	('IT-ME','ME','ITA','Mesaina'),
	('IT-PA','PA','ITA','Palermo'),
	('IT-RG','RG','ITA','Ragusa'),
	('IT-SR','SR','ITA','Siracusa'),
	('IT-TP','TP','ITA','Trapani'),
	('IT-52','52','ITA','Toscana'),
	('IT-AR','AR','ITA','Arezzo'),
	('IT-FI','FI','ITA','Firenze'),
	('IT-GR','GR','ITA','Grosseto'),
	('IT-LI','LI','ITA','Livorno'),
	('IT-LU','LU','ITA','Lucca'),
	('IT-MS','MS','ITA','Massa'),
	('IT-PI','PI','ITA','Pisa'),
	('IT-PT','PT','ITA','Pistoia'),
	('IT-PO','PO','ITA','Prato'),
	('IT-SI','SI','ITA','Siena'),
	('IT-32','32','ITA','Trentino-Alte Adige (Trentino-Südtirol)'),
	('IT-BZ','BZ','ITA','Bolzano (Bozen)'),
	('IT-TN','TN','ITA','Trento'),
	('IT-55','55','ITA','Umbria'),
	('IT-PG','PG','ITA','Perugia'),
	('IT-TR','TR','ITA','Terni'),
	('IT-23','23','ITA','Valle D''Aosta (Vallée D''Aoste)'),
	('IT-AO','AO','ITA','Aosta (Aoste)'),
	('IT-34','34','ITA','Veneto'),
	('IT-BL','BL','ITA','Belluno'),
	('IT-PD','PD','ITA','Padova'),
	('IT-RO','RO','ITA','Rovigo'),
	('IT-TV','TV','ITA','Treviso'),
	('IT-VE','VE','ITA','Venezia'),
	('IT-VR','VR','ITA','Verona'),
	('IT-VI','VI','ITA','Vicenza'),
	('IT-AB','AB','ITA','Abruzzi'),
	('IT-BC','BC','ITA','Basilicata'),
	('IT-CI','CI','ITA','Calabria'),
	('IT-CM','CM','ITA','Campania'),
	('IT-ER','ER','ITA','Emilia-Romagna'),
	('IT-FV','FV','ITA','Friuli-Venezia Giulia'),
	('IT-LG','LG','ITA','Liguria'),
	('IT-LM','LM','ITA','Lombardia'),
	('IT-LZ','LZ','ITA','Lazio'),
	('IT-MH','MH','ITA','Marche'),
	('IT-ML','ML','ITA','Molise'),
	('IT-PM','PM','ITA','Piemonte'),
	('IT-PU','PU','ITA','Puglia'),
	('IT-SC','SC','ITA','Sicilia'),
	('IT-SD','SD','ITA','Sardegna'),
	('IT-TC','TC','ITA','Toscana'),
	('IT-TT','TT','ITA','Trentino-Alto Adige'),
	('IT-UM','UM','ITA','Umbria'),
	('IT-VD','VD','ITA','Valle D''Aosta'),
	('IT-VN','VN','ITA','Veneto');
COMMIT;
ANALYZE;
